### ISSUE TITLE
No feedback on removing a nonexistent contract 

### ISSUE THREAD

**Issue by sideninja** [onflow/cadence#1014]
### Problem
If you try to remove a nonexistent contract on the account, you don't get an error and the transaction is executed. 

The transaction sent to remove the contract gets committed and is included in the new block.

### Steps to Reproduce
Remove a nonexistent contract on the account. Example using flow CLI: 

`flow accounts remove-contract Foo` 

Output:
```
INFO[0015] ⭐  Transaction executed                       txID=9d5760154f5a959ce0ac62eec018911e66092f263de87775559a07e3b825230a
DEBU[0015] 📦  Block #4 committed                         blockHeight=4 blockID=530fd5fcbbf09376bc120dca947d5b44bda8ab52637c3f6952568f98e178d6f6
DEBU[0015] 📝  GetTransactionResult called                txID=9d5760154f5a959ce0ac62eec018911e66092f263de87775559a07e3b825230a
DEBU[0015] 👤  GetAccountAtLatestBlock called             address=f8d6e0586b0a20c7
```

### Acceptance Criteria
A transaction that removes a contract from the account could return the name of the removed contract and thus being an idempotent action, or it could produce an error in case there is no contract by that name on the account, which would then revert the transaction as it didn't change the state.

### Context
This behaviour might cause a problem when you need to know if a contract was removed or not, so this would require another request of the account to check the deployed contracts.

**Comment by bluesign** [comment]
I agree failing the transaction with error can be good on this. 

On a side note: when you remove a contract you are getting the event: `flow.AccountContractRemoved`so basically you don't need to make another request other than checking the transaction result.

**Comment by sideninja** [comment]
> I agree failing the transaction with error can be good on this.
> 
> On a side note: when you remove a contract you are getting the event: `flow.AccountContractRemoved`so basically you don't need to make another request other than checking the transaction result.

Right yeah, in case the contract gets removed there is an event, good point, but anyhow it feels to me it could be more explicit.

**Comment by bluesign** [comment]
On the other hand, some testing scripts can benefit from current logic, for example if I want to set up an account: 

instead of: 

- check contract exists
- remove if exists 
- deploy contract

you can use simpler script like:

- remove contract
- deploy contract

**Comment by turbolent** [comment]
Thank you for flagging this!

This isn't really a bug, but a design decision to allow for both use cases:
The function returns an optional, the contract that was deployed, if any existed.

So in case you want to deploy a new contract without having knowledge if an existing contract was deployed you can attempt to remove it, and in the case where there was no contract, it will return `nil`.

In the case where you want to ensure the contract that is removed existed, you could for example panic, e.g. `contracts.remove("MyCoolContract") ?? panic("contract MyCoolContract did not exist")`
