### ISSUE TITLE
Improve cryptographic signatures doc

### ISSUE THREAD

**Issue by tarakby** [onflow/cadence#1021]
### Context

More details should be provided about how to generate signatures that are valid with regards to the Cadence signature verification API: https://github.com/onflow/cadence/blob/master/docs/language/crypto.mdx

This also includes more details about the following points:
 - [x] clean up the hashing section
 - [x] KMAC128 parameters.
 - [x] BLS hashing to curve details. 
 - [x] how to generate a valid PoP
 - [x] ECDSA accepts all tags
 - [x] ECDSA : more emphasis on the empty tag
 - [x] more details about public key validation 
 - [x] BLS multi-sig functions 
 - [x] Keccak can be used in ECDSA and HashWithTag

**Comment by turbolent** [comment]
@tarakby What's the current status here? Is this done?

**Comment by tarakby** [comment]
Not yet! I wanted to make some updates on the crypto lib first (https://github.com/dapperlabs/flow-go/issues/5647)

**Comment by j1010001** [comment]
Hey @tarakby , what is the status here ?

**Comment by tarakby** [comment]
I need to work on it before April spork. I didn't get to it this sprint though.
