### ISSUE TITLE
'Never' typed expressions get skipped from certain type-checks

### ISSUE THREAD

**Issue by SupunS** [onflow/cadence#1031]
### Problem

`Never` is the subtype of all types. Hence it gets passed through the `IsSubType` check for contexts where the `Never` type shouldn't be allowed.

### Steps to Reproduce
e.g:

(1)
```kotlin
var a: Never = "c"    // no errors reported
```

(2)
```kotlin
pub fun test(a: Never, b: Never) {
    var x: Int = a + b  // no errors reported
}
```

### Acceptance Criteria

- [ ] Differentiate checking `IsSubType` Vs checking whether a type belongs to a particular 'kind' of type (e.g: is `T` of type `Integer`?). Can introduce a separate method for the later.
- [ ] Update the usages of `IsSubType` to use the proper method out of the two, depending on the context.

**Comment by turbolent** [comment]
I don't think this is necessarily a bug, it's just that the such definitions are not useful.

I agree that it would be nice to improve the user experience, though this is not a high priority.
