### ISSUE TITLE
OMT: Design, prototype, implement, benchmark, and optimize (new storage layer design)

### ISSUE THREAD

**Issue by fxamacker** [onflow/cadence#1058]
### Issue To Be Solved

Storage can be faster and require less network traffic for large maps.

### Suggestion

See design doc and atree repo for more info about OMT (Ordered Map Type).

- [x] design OMT (@ramtinms with feedback from team)
- [x] implement OMT (@fxamacker)
- [ ] document postponed/possible optimizations (@fxamacker) 
- [ ] benchmark OMT (@ramtinms @fxamacker )
- [ ] minimally optimize OMT if time allows (@fxamacker )
- [ ] code reviews and discussions (@ramtinms @turbolent @fxamacker)
- [ ] present findings
- [x] Implement storage reporter uin FVM that allows testing hash functions to determine hash collision rate (@turbolent) 
  onflow/flow-go#1016

**Comment by Kay-Zee** [comment]
This can be considered Done
