### ISSUE TITLE
Select and set up CI for existing fuzzing

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#1061]
## Context

We have an existing fuzzer test, and we are going to write more.  We need some infrastructure to actually build and run and monitor them, and collect their results into a human-usable format, preferably through a web-interface, or as automatically created github issues.  We evaluated 8 options, shortlisted to 3 and have trialed 2.  There is 1 left to try, and that attempt is just beginning today.

## Definition of Done

What do we need to achieve to consider this issue resolved?

* A system that pulls automatically from this GH repo, builds and runs the fuzzers that it finds, and creates browseable lists of issues that the fuzzers find.

## PR Review 

Who is your Code Partner/Who can provide external eyes? TBD

## Internal Testing 
Maybe a dummy fuzzer that produces a bunch of known issues, to test that the CI integration works and continues to do so.

## Estimation Breakdown
- Dev work: More than a day, less than a week
- Testing: Two days
- Review: TBD

**Comment by jsatdapr** [comment]
Evaluation matrix: https://www.notion.so/dapperlabs/567f1ab827104f87adc8a13c84d29c91?v=bee9aaba473445e99b31fb7f6a6a3318

Have applied for trial account, company accepted, awaiting delivery of account details.

**Comment by jsatdapr** [comment]
Awaiting delivery of personal trial account details, or acquisition of internal company license which is proceeding independently.  Further setup is blocked on having a license.

**Comment by Kay-Zee** [comment]
@jsatdapr Now that we have FuzzBuzz set up, can we consider this finished?

**Comment by robert-e-davidson3** [comment]
Deprecating this ticket in favor of epic https://github.com/onflow/cadence/issues/1309.
