### ISSUE TITLE
Grammar-based fuzzing

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#1062]
## Context

The existing fuzz.go spends most of its time searching for valid utf8 streams and valid token streams.  We want a fuzzer that is able to skip those steps and fuzz valid grammars directly.

A separate approach does not require a formal grammar, and can proceed immediately: #1077  

The approach described in this issue requires a formal grammar.

We have one in docs/cadence.ebnf but it's not obviously correct.

In order to verify some level of correctness, we'd like to generate a parser from this grammar.  i.e. This depends on #1078

In all of the test cases that involve parsing cadence, parse twice: once with the existing hand-written parser, and once with the generated parser.  Then verify that the resulting ASTs are identical.  #1051 helps because it guarantees that comparing JSON marshalled ASTs is _sufficient_.

## Definition of Done

1. Have a correct grammar.
2. Use it to generate cadence
3. Wrap it up in a fuzzer.

## Estimation Breakdown
- Dev work: 
- Testing: 
- Review:

**Comment by robert-e-davidson3** [comment]
Deprecating this ticket in favor of epic https://github.com/onflow/cadence/issues/1309.
