### ISSUE TITLE
PublicAccount contracts and contract names

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#1075]
### Issue To Be Solved

Currently it is only possible to get a known deployed contract from an authorized account (`AuthAccount.Contracts.get`). 

`PublicAccount` does not provide a way to get a deployed contract.

In addition, it would be nice to also query the names of all deployed contracts of any account.

### Suggest A Solution

- [ ] Add a function `fun getNames(): [String]` to `AuthAccount.Contracts`, which returns the names of all deployed contracts of the account
  - [ ] This requires adding a function (e.g. `GetAccountContractNames`) to the `runtime.Interface` and implementing it in flow-go's FVM. The data is already available there
- [ ] Add the `PublicAccount.Contracts` type (similar to `AuthAccount.Contracts`), which only exposes a `get` function and a `getNames` function like in `AuthAccount.Contracts`

### Context

We need this functionality to evaluate the impact of changes made to Cadence on contracts deployed to the existing networks. Similar to the Source Compatiblity Suite, we would query all contracts deployed to a network, and parse and check them first with the current version, and then again with the modified version of Cadence. This way we can detect potential regressions in the parser and checker

**Comment by turbolent** [comment]
@SupunS Would you be able to take this on?

**Comment by SupunS** [comment]
This seems a useful feature!

What do you think of using `names()` as the function name (inplace of `getNames`)? 
Just a personal flavour: for getter functions, I think the `get` prefix could be omitted, but can still be intuitive.

**Comment by turbolent** [comment]
@SupunS Ah, yeah, actually I think it might be even better to just follow what we do elsewhere, e.g. for dictionaries, and have a computed field `let names: [String]`
