### ISSUE TITLE
Update and verify docs/cadence.ebnf

### ISSUE THREAD

**Issue by jsatdapr** [onflow/cadence#1078]
### Issue To Be Solved

docs/cadence.ebnf is not obviously correct.  In order to be certain that it is, we should generate a parser from it and compare it against the existing handwritten parser.

### Solution

* Try YEAP: https://github.com/vnmakarov/yaep
* Depends on #1051 for comparing JSON.Marshal()d ASTs.

### Context

This is meant to unblock #1062.

**Comment by robert-e-davidson3** [comment]
Deprecating this ticket in favor of epic https://github.com/onflow/cadence/issues/1309.
