### ISSUE TITLE
Performance improvement by changing map to array type

### ISSUE THREAD

**Issue by jwinkler2083233** [onflow/cadence#1079]
### Instructions

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.

### Problem

Excessive CPU is dedicated to Cadence parsing.

### Steps to Reproduce

Performance profile yields:
 0.54%     0.01%  app      app                [.] github.com/onflow/cadence/runtime/parser2.applyExprNullDenotation
             --0.53%--github.com/onflow/cadence/runtime/parser2.applyExprNullDenotation

  1.28%     0.00%  app      app                [.] github.com/onflow/cadence/runtime/parser2.parseBlock
             --1.28%--github.com/onflow/cadence/runtime/parser2.parseBlock
                        --1.25%--github.com/onflow/cadence/runtime/parser2.parseStatements
                                   --1.20%--github.com/onflow/cadence/runtime/parser2.parseStatement
                                              --0.94%--github.com/onflow/cadence/runtime/parser2.parseDeclaration
                                                         --0.94%--github.com/onflow/cadence/runtime/parser2.parseVariableDeclaration
                                                                    --0.82%--github.com/onflow/cadence/runtime/parser2.parseExpression
                                                                               --0.71%--github.com/onflow/cadence/runtime/parser2.applyExprMetaLeftDenotation

### Acceptance Criteria

The parsing of a null denotation should require minimal CPU time.

### Context

Performance needs to hit > 300 TPS within a year

**Comment by jwinkler2083233** [comment]
Update:  The latest branch is passing unit tests.
The next test I want to try is integrating this with the nodes to get a good comparison.

**Comment by turbolent** [comment]
@jwinkler2083233 please assign this to yourself if you are working on it

**Comment by jwinkler2083233** [comment]
For future use, the command to use a specific branch or commit of Cadence with flow-go is:

go get github.com/onflow/cadence@<commit hash>

from within the flow-go directory.
