### ISSUE TITLE
Panic when value is inserted into container with incorrect type

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#1098]
### Issue To Be Solved

It should not be possible to store a value in a container that is not a subtype of the container's static type.

### Suggested Solution

When a value is inserted into a container (array or dictionary), check that the dynamic type of the inserted value is a subtype of the containers static type, i.e array static type's element type, or dictionary static type's key/value type.

**Comment by SupunS** [comment]
Closing since this was added in #1103
