### ISSUE TITLE
Add support for casting String to *Path (StoragePath or CapabilityPath)

### ISSUE THREAD

**Issue by allenoooo** [onflow/cadence#1105]
### Issue To Be Solved
A convenience method to cast a String to *Path would be convenient and ergonomic from a developer perspective. It would allow for easy dynamic path specification for resources/capabilities, such that one wouldn't need to 'hardcode' entire *Paths.

### Suggested Solution
Add the following methods to String:

* `"/storage/somePath".to_storagePath()`
* `"/public/somePath".to_capabilityPath()`

These methods will simply cast the path contained in the String to their corresponding *Path type.

**Comment by turbolent** [comment]
Instead of having the conversion functions on `String`, it might be better to define constructor functions for each path type, e.g. `StoragePath(identifier: "somePath")`

**Comment by VladislavIvanov** [comment]
It would be really great if we have it! 🙏

**Comment by turbolent** [comment]
cc @srinjoyc @psiemens
