### ISSUE TITLE
Create a toString() method on Int types

### ISSUE THREAD

**Issue by allenoooo** [onflow/cadence#1106]
### Issue To Be Solved

Currently, there is no way to cast Int types to String types. This would be a useful feature, especially when combined with my other feature request to cast String types to *Path types #1105. Together, all of these new casting methods would allow for ergonomic dynamic creation of paths for resources/capabilities/whatever. Consider the following pseudo-code (Cadence and Go Frankenstein): 

```
var myPaths: [StoragePath]

func createPaths() [StoragePath] {
    prefix := "/storage/someVectorOfObject"
    for i := 0; i <= 10; i++ {
        suffix: Int = i.toString()
        fqdn: String = prefix.concat(suffix)
        myPath: StoragePath = fqdn.to_storagePath()
       append(myPaths, myPath)
    }
}
```

### Suggested Solution
Add Itoa - toString method for Int types. i.e. `10.toString()`

**Comment by 10thfloor** [comment]
Can we avoid the heritage C++ method name, and just call it `toString` ?

**Comment by allenoooo** [comment]
> Instead of adopting the C++ method name, could we use the Java/JavaScript `toString` instead?

Great idea - more modern and easily grokked. Sure, let's call the method `toString` as you suggest. I'll update the body of the feature request.

**Comment by turbolent** [comment]
Such an integer-to-string conversion function already exists for all integer types, and is already named `toString`:

```
$ flow cadence
Welcome to Cadence v0.18.0!
Type '.help' for assistance.

1> let a = 1
2> a.toString()
"1"
```

Please let me know if that works for you

**Comment by allenoooo** [comment]
Ah, I missed this one. Cool, this will work. My oversight.
