### ISSUE TITLE
Use Docgen in CI

### ISSUE THREAD

**Issue by bjartek** [onflow/cadence#1121]
### Instructions

I want to use docgen to generate documentation for my cadence code and put it somewhere using ci. 
https://github.com/onflow/cadence/blob/master/tools/docgen/README.md

If i try to go get and go install the cmd folder here it gives me a binaray called cmd, would it be possible to structure this so that I can get the tool as `docgen` or even better `cadence-docgen`?

Other features that I feel would be nice:
 - allow input to be a list of files and create a index file in the root of doc and put them all there.
 - create output dir if it does not exist.

**Comment by bjartek** [comment]
I tried running it locally now and it is blazingly fast! 

Another feature request, if the output dir does not exist create it.

**Comment by turbolent** [comment]
You can choose the binary name, see e.g. https://stackoverflow.com/questions/25093129/how-to-configure-binary-name-in-go-without-changing-path

**Comment by bjartek** [comment]
Awesome
