### ISSUE TITLE
Empty contract call

### ISSUE THREAD

**Issue by MaxStalker** [onflow/cadence#1123]
### Problem
It's possible to leave contract declaration without actually calling any methods or accessing it's fields. For example, this is a valid code, which will be executed:
```rust
import HelloWorld from 0x01

transaction {
  prepare(signer: AuthAccount) {
    // Is this OK? 👇
    HelloWorld

    log("all cool") // this line will be called normally and output message in the log stream
  }
}
```

### Steps to Reproduce
You can go to this Playground:
https://play.onflow.org/f7610cb6-1b6d-4f2b-a05e-f0911f6fd045?type=tx&id=4b8a81cd-70aa-4c83-8c4c-b7fd85ddcae9

and send selected transaction (HelloWorld is deployed already).

**Comment by turbolent** [comment]
Yes, this is valid and works as expected: A variable is evaluated, but the result not used. This is similar to evaluating any other expression as a statement and not using the result.
