### ISSUE TITLE
Number Types Convert Incorrectly

### ISSUE THREAD

**Issue by rheaplex** [onflow/cadence#1126]
This code:

```
  log(Int(UInt64(1)))
  log(Int(UInt64(18446744073709551615)))
```

logs:

```
18:20:43 Script 1
18:20:43 Script -1
```

https://play.onflow.org/f7457773-a35b-41f9-9296-cb0d73add49d?type=script&id=247df2fe-9acd-48bd-bba0-6f232801e478

That behaviour is unexpected. I have just encountered some code relying on it, and I have warned the developer that they should not do so.

@turbolent (thank you for looking at this!) says:

> I think this is a bug, caused by an internal conversion from uint64 to int, which silently overflows in Go

and that we should clean up code in the golang codebase marked:

> `// TODO: handle overflow`

I would like to attempt to fix this but I am slammed this week. If this can wait I can take it on, but if not someone else may need to.

**Comment by turbolent** [comment]
@rheaplex Any update here?
