### ISSUE TITLE
Checker with file import handler failing on relative paths. 

### ISSUE THREAD

**Issue by bluesign** [onflow/cadence#1132]
### Problem

File import handler of checker failing on relative paths. 

https://github.com/onflow/cadence/blob/90d26d53a1c6ad000361b9e2db5e6efa10f26ebc/runtime/cmd/cmd.go#L99

### Steps to Reproduce

When integrating checker to cli, we ran into this bug. 

You can also reproduce with cli cadence command:

```
flow cadence someFolder/someCadence.cdc
```

which `someCadence.cdc` containing an import:

```
import FungibleToken from "./contracts/dependencies/FungibleToken.cdc"
```

Here Checker is trying to resolve: `"./contracts/dependencies/FungibleToken.cdc"` from current path instead of `someFolder/contracts/dependencies/FungibleToken.cdc`

### Acceptance Criteria

Relative paths should work

**Comment by turbolent** [comment]
I think this was fixed in the language server by #616 and the same fix should be applied to the CLI tool.

**Comment by bluesign** [comment]
Thanks for the answer @turbolent, will it be ok if I carry this fix to Cadence directly? Otherwise we will have the same fix in 2 separate projects? Or maybe more in the future.

**Comment by turbolent** [comment]
@bluesign yes, ideally we would have this "local file resolution" mechanism in one place and use it everywhere if possible 👍
