### ISSUE TITLE
Allow Type to be used as a Dictionary key

### ISSUE THREAD

**Issue by rheaplex** [onflow/cadence#1133]
This is useful for associating runtime data with types. We can currently use `Type.identifier` and the resulting strings to achieve the same effect, but it would be more convenient to be able to use `Type` directly.

e.g.: `{Type: AnyStruct}`

An example of this is [the current metadata discussion](https://github.com/onflow/flow-nft/issues/9), where ensuring and accessing a particular `Type` of metadata is important for the robustness of the API.

**Comment by turbolent** [comment]
This should be fairly easy to implement, by adjusting `sema.IsValidDictionaryKeyType` and implementing `interpreter.HasKeyString` for `interpreter.TypeValue`. 

I think the only problem is handling type values that do not refer to a static type, i.e. the ones that are used for values that do not have static type information, e.g. function values, and are considered "opaque" and unequal to each other.
