### ISSUE TITLE
HashAlgorithm is Unsupported

### ISSUE THREAD

**Issue by rheaplex** [onflow/cadence#1140]
The Flow docs mention a `HashAlgorithm` enum:

https://docs.onflow.org/cadence/language/crypto/#hashing

Cadence doesn't seem to support it -

https://play.onflow.org/82d4070f-5a23-483f-90cd-a35dc8043be0?type=account&id=7555342d-2551-41ea-9bf9-d88218031fe8

We need it (or a workaround) for on-chain hash validation for a high priority project. 😬

**Comment by SupunS** [comment]
@rheaplex I think this is because the playground uses an old version of Cadence. Should work on-chain.

There is also an issue reported for the playground to keep up with the Cadence version: https://github.com/onflow/flow-playground/issues/138.

**Comment by turbolent** [comment]
This works as expected. For example:

```
$ flow scripts execute --host access.testnet.nodes.onflow.org:9000 <(echo 'pub fun main(): [UInt8] { return HashAlgorithm.SHA3_256.hash("01020304".decodeHex()) }')

Result: [150, 109, 189, 203, 208, 224, 52, 143, 170, 28, 203, 206, 90, 98, 184, 231, 59, 13, 8, 149, 93, 102, 109, 184, 34, 67, 179, 3, 217, 189, 149, 2]

```

The problem does not seem to be in Cadence, but the Playground. 

@rheaplex Have you tried using the Emulator? Does it work there?

**Comment by bluesign** [comment]
I checked this I think it was language server related but I cant recall right now

**Comment by justjoolz** [comment]
Yeah it's for sure the language server, same issue when using SignatureAlgorithm (and probably all Crypto).

**Comment by btspoony** [comment]
it's a language server bug. 
This causes the file using `HashAlgorithm` to never pass the type checker.

**Comment by bluesign** [comment]
To recycle this issue instead of creating new one:

 @SupunS , I think LS doesn't add `stdlib.BuiltinValues`  to` valueDeclarations`.

To anyone having this problem: I managed to solve this by changing valueDeclerations in server.go ( in LS ) to: 

Somehow my ugly but working code is like this: 
```
var valueDeclarations = append(append(
	stdlib.FlowBuiltInFunctions(stdlib.FlowBuiltinImpls{}),
	stdlib.BuiltinFunctions...,
).ToSemaValueDeclarations(), stdlib.BuiltinValues.ToSemaValueDeclarations()...)
```

**Comment by turbolent** [comment]
@bluesign Great find! I reproduced the initial problem of some of the standard library functionality not being available when using the language server, then  tested your proposed fix - the incomplete declarations are indeed the problem and adding them fixes the problem. Thank you! I opened #1698 to get this fix in
