### ISSUE TITLE
Let host environment to expose functionality

### ISSUE THREAD

**Issue by bluesign** [onflow/cadence#1160]
### Issue To Be Solved

Currently there is no way to expose some functionality from host environment to cadence. I think it will be very nice ability ( especially for emulator, but also if I want to use cadence in another environment, even not blockchain ) 

It will also make testing much powerful. 

Examples in my mind are:  ( for emulator )

- Saving / Loading Emulator State from cadence
- Setting Time Drift:  for testing logics requiring to have some time pass before second action
- Query Emulator Storage 
- A testing framework ( exposed to Cadence ) so I can write my tests in cadence 

### Suggested Solution

From hardest to easiest to implement in my opinion: 

- I think some pluggable architecture would be very nice, like `Crypto` contract.
- Or basically we can expose some built-in functions on a pre-set namespace. 
- Or just a `system` command taking a string argument ( like log command )

**Comment by turbolent** [comment]
Yes, this would be a "pre-requisite" for extending the functionality available in the emulator, and for the testing framework (#331), where tests are written in Cadence itself.

We actually have this already in the form of `runtime.Context.PredeclaredValues`, which allows the injection of values into particular locations when executing transactions and scripts. It leverages, the checker's predeclared values and interpreter's predeclared values features.

**Comment by bluesign** [comment]
As I have a  working solution, closing this issue
