### ISSUE TITLE
Determine expensive operations and adjust computation usage

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#1221]
### Definition of Done

Determine which Cadence and FVM operations are expensive and adjust metering accordingly

**Comment by turbolent** [comment]
Review @janezpodhostnik's Notion document, FLIP #660

**Comment by janezpodhostnik** [comment]
This PR should offer some insight into expensive operations, and should warn us if they change https://github.com/onflow/flow-go/pull/1219. I am also working on another FLIP that will connect into onflow/flow#660 and will address this part. I'm hoping to get it out next week.

**Comment by turbolent** [comment]
@janezpodhostnik Do we still want to improve computation metering for expensive operation until a more complex solution (e.g. FLIP) is implemented?

**Comment by janezpodhostnik** [comment]
Yes I think we can close this one. We have all the tools/metering needed in place now.

The flip that was created: https://github.com/onflow/flow/pull/753 (Though it still needs to be updated, which I am doing now.)
