### ISSUE TITLE
Documentation incorrectly suggests that Interface Implementation Requirements are supported

### ISSUE THREAD

**Issue by irisjae** [onflow/cadence#1237]
Under the ['Interface Implementation Requirements' section in the Documentation on 'Interfaces'](https://docs.onflow.org/cadence/language/interfaces/#interface-implementation-requirements), the following code suggests that Implementation Requirements is implemented and functional in Cadence. 
```
// Declare a structure interface named `Shape`.
//
pub struct interface Shape {}

// Declare a structure interface named `Polygon`.
// Require implementing types to also implement the structure interface `Shape`.
//
pub struct interface Polygon: Shape {}
```

However, this code triggers `error: unexpected conformances` when declared, both in the playground and in the Flow emulator. Browsing the cadence source code reveals the [following](https://github.com/onflow/cadence/blob/master/runtime/parser2/declaration.go#L855), suggesting that in fact Implementation Requirements are not yet implemented and cannot be used in Cadence code yet.
```
	if isInterface {
		// TODO: remove once interface conformances are supported
		if len(conformances) > 0 {
			// TODO: improve
			panic(fmt.Errorf("unexpected conformances"))
```

**Comment by turbolent** [comment]
Thank you for reporting this! This functionality is not implemented yet and the documentation is missing a status section
