### ISSUE TITLE
Inferred type for ternary operator with nil leads to unexpected `mismatched types` error 

### ISSUE THREAD

**Issue by irisjae** [onflow/cadence#1239]
### Problem

This program is semantically correct:
```
let cond = false
let message = ""
let messageOptional : String? =
  cond ? nil : message
```

However, it fails with Cadence's type inference on the fourth line on the `message` token, giving a `mismatched types` error, reporting that `expected 'Never?', got 'String'`.

Presumably this is because the type of the right-hand side of the initialization expression of variable declaration `messageOptional` is inferred on its own, with respect to `nil`, to `Never?`. Changing the order of the ternary operator does not affect the error, so presumably the type inference is performed solely on the strength of the `nil` token.

Perhaps the type of an expression on the right-hand side should be synthesized along with type information from the left-hand side, if available (bidirectional type checking).

As a workaround, forcing the type of the `nil` branch, like so, manages to convince Cadence's type checker.
```
let cond = false
let message = ""
let messageOptional/* : String?*/ =
  cond ? (nil as String?) : message
```

### Steps to Reproduce

See above.

**Comment by SupunS** [comment]
Thanks for reporting! Tested this against https://github.com/onflow/cadence/pull/1027, and seems to be fixed with that change.

**Comment by turbolent** [comment]
@SupunS Awesome!
