### ISSUE TITLE
Audit and document runtime interface user vs implementation error handling

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#1256]
- [ ] Audit how user and implementation errors are handled
- [ ] Document current handling (runtime interface function error return value VS panics)

**Comment by j1010001** [comment]
Most of the concerns addressed in https://github.com/onflow/cadence/issues/1708, there might be still some issues on the FVM side.

**Comment by j1010001** [comment]
Post Secure Cadence cleanup
