### ISSUE TITLE
Clean up PublicKey

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#1268]
### Issue To Be Solved

Currently it is possible to construct invalid public key. Representing invalid public keys is not useful and complicates the implementation of much of the functionality using public keys (e.g. signature verification).

### Suggested Solution

- In the `PublicKey` constructor: Keep validating the inputs, but instead of setting the `isValid` field, abort (panic) if the public key data is invalid
- Remove the `IsValid` and `Validated` fields from the `runtime.PublicKey` type
- Remove the `isValid` field from the Cadence `PublicKey` type, it is effectively constantly true

**Comment by tarakby** [comment]
Thanks for creating the issue!

One point I wanted to add: I believe the structure `PublicKey` in Cadence is currently immutable. With the update described above, we should either:
 - keep the structure immutable (raw bytes and signature algorithm)
 - make any update of the fields trigger a new validation of the key, which may lead to aborting the execution.
