### ISSUE TITLE
Move linter to a separate phase

### ISSUE THREAD

**Issue by SupunS** [onflow/cadence#1269]
### Issue To Be Solved

Currently, linter errors (i.e: hints such as redundant casts, etc.) are also checked and reported at the `checker`. Moving these non-erroneous checks /code-smells to a separate phase could make the checker cleaner. It also allows enabling/disabling such advanced but non-mandatory checks depending on the use-case (e.g: on-chain vs dev-tools)

**Comment by turbolent** [comment]
I really like the simplicity of [Go's `analysis` package](https://pkg.go.dev/golang.org/x/tools/go/analysis).
It should be possible to implement something similar for Cadence with little effort: We already have the AST walking implemented, and have to make the elaboration available. It does not provide complete type information for all elements, but should be sufficient for most tasks, and could be extended.

**Comment by turbolent** [comment]
The analysis framework is now in place, so we can easily refactor the existing linters to be based on the new framework. 
For example, they could be moved to the new contract analyzer tool and eventually to the CLI.

**Comment by turbolent** [comment]
Once #1732 is merged, we basically have a linter which can be extended with more linting rules / analyzers.

Two follow-up tasks:
- [ ] Maybe move this tool from `tools/contract-analyzer` into a repo `cadence-lint`
- [ ] Refactor the existing linting rules out of the checker and into separate analyzers (instances can be found by searching for `lintingEnabled` in `sema`)

**Comment by turbolent** [comment]
With Secure Cadence released, now would be a good time to clean up this tech debt and turn it into a more useful tool.

@dsainati1 would you be maybe interested in picking this up?

**Comment by dsainati1** [comment]
Sure! This seems cool
