### ISSUE TITLE
Array indexOf implementation

### ISSUE THREAD

**Issue by bm-nJoi** [onflow/cadence#1276]
### Issue To Be Solved
Arrays in Cadence have a limited API, but they do feature the function **contains**.
https://docs.onflow.org/cadence/language/values-and-types/#array-fields-and-functions

While this function is useful, it leaves something to be desired from the caller's perspective. Namely: **where is it?**
To answer this valuable question, the caller will then have to traverse the array themselves and find the thing they **know** is in there (_and just got found!_ <- this is repeated work, right?)

### Suggested Solution
The act of determining **does this array contain that thing**, is nothing more than a return-type change away from **where is this thing in that array**?

Arguably this function is a superset of both implementations:
```
indexOf(thing: T): UInt64? {
  if (!contains(thing)) {
    // find its index and return it
  }
  // return nil // "contains = false"
}
```

**Comment by turbolent** [comment]
Thank you for your feature request! There hasn't been much effort on the standard library yet. This should be easy to add, pull requests are very welcome! Like you pointed out, it would be very similar to the `contains` function.
