### ISSUE TITLE
PublicAccount.Keys is not iterable

### ISSUE THREAD

**Issue by MaxStalker** [onflow/cadence#1300]
### Problem
Within transaction or script context `PublicAccount.keys` accessed by getting `getAccount(val)` is not iterable - we don't know the amount of keys and can only access them via `get` method passing index inside. 

On top of that, if we return `PublicAccount` from script - `keys` field will be empty.

### Steps to Reproduce
- execute following script using any SDK:
```kotlin
    pub fun main(account: Address): PublicAccount{
        return getAccount(account)
    }
```
- returned value would contain empty object for field `keys`

**Comment by SupunS** [comment]
This is not actually a bug, but rather by design: https://docs.onflow.org/cadence/language/accounts/#account-keys

The reason behind this was that `PublicAccount.keys` are read-only, and must not be mutable. 

But yeah, there is room for improvement to let users iterate through the keys.

**Comment by turbolent** [comment]
There are multiple points in the issue, it would be good to split them into separate issues:
- Add a `length` field to `PublicAccount.Keys` and `AuthAccount.Keys` which returns the number of keys
- Improve the export of values of type `PublicAccount`

**Comment by turbolent** [comment]
Duplicated in #1388, moving discussion there
