### ISSUE TITLE
Pitch token rewrite to community

### ISSUE THREAD

**Issue by j1010001** [onflow/cadence#1308]
Draft: https://docs.google.com/document/d/17MEcG6dIBYcL3GW1Hwy9oJxkrNmIRTdKPjeiVgKTi7U/edit

**Comment by joshuahannan** [comment]
We've already pitched this to the community with the streamlined token standard blog post: https://forum.onflow.org/t/streamlined-token-standards-proposal/3075/43
And we have two PRs open for the changes already that have gotten a lot of participation from the community: 
https://github.com/onflow/flow-ft/pull/77
https://github.com/onflow/flow-nft/pull/126
I also have [another issue open for the FLIP](https://github.com/onflow/flow/issues/895), so I'm going to close this issue.
