### ISSUE TITLE
BUG: Values are not being stored in dictionaries correctly when transferred

### ISSUE THREAD

**Issue by joshuahannan** [onflow/cadence#131]
### Problem

Values that are transferred from a dictionary in one account to another account are not being stored correctly, so that a transaction that tries to access that value in the second dictionary causes the runtime to panic.

### Steps to Reproduce

1. Test cases are in the bugFix branch of the NFT repo: https://github.com/onflow/flow-nft/tree/josh/bugFix
2. Deploy a contract with a collection, create a collection in storage with an NFT inside of it
3. Create an empty collection in another account
4. Transfer the NFT from the first account to the second account
5. Try to withdraw or borrow a reference to the NFT in the second account
6. Panic

### Acceptance Criteria

Runtime must not panic and value must be accessed correctly

### Context

Blocking NFT contracts from working correctly

**Comment by turbolent** [comment]
Fixed by #132
