### ISSUE TITLE
Rebase onflow/cadence -> onflow/fuzzer

### ISSUE THREAD

**Issue by robert-e-davidson3** [onflow/cadence#1311]
Cadence has changed quite a bit since onflow/fuzzer was written. The parser-based fuzzing in onflow/fuzzer needs to be updated to use the latest Cadence code. We will keep this on a branch and evaluate the parser performance after the rebase to decide next steps.

There are a few complications:
1. The parser likely needs to be updated for specific Cadence changes, not just generic changes to code layout and flow.
2. Any seed values used by the fuzzer will be invalid because Cadence has changed in the onflow/cadence master branch. The contracts on mainnet are also outdated so creating new seeds may take a long time.

**Comment by j1010001** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Flow-Protocol-5a2ad022cee40e25b0885f82/issues/onflow/cadence/1311?planning-poker) with ZenHub @dsainati1 @robert-e-davidson3 @SupunS @turbolent
