### ISSUE TITLE
Add fuzzing tests

### ISSUE THREAD

**Issue by robert-e-davidson3** [onflow/cadence#1312]
Fuzzing coverage is expanded three ways:
1. Adding new tests. These add coverage of specific features or areas of aa feature.
2. Adding new seeds to existing tests. This expands coverage in an already-covered area.
3. Letting the fuzzer run. This increases coverage rapidly at first then much more slowly as the low-hanging fruit are picked.

This ticket is for #1 and maybe some of #2.

**Comment by j1010001** [comment]
Turn this into EPIC - depends on how this evaluation neds up - what coverage we get.
