### ISSUE TITLE
Fuzzing CI integration with FuzzBuzz

### ISSUE THREAD

**Issue by robert-e-davidson3** [onflow/cadence#1313]
The onflow/fuzzing repo is integrated with FuzzBuzz. This ticket is for migrating to the correct go fuzzer, as well as making sure the integration still works afterwards.

**Comment by j1010001** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Flow-Protocol-5a2ad022cee40e25b0885f82/issues/onflow/cadence/1313?planning-poker) with ZenHub @dsainati1 @robert-e-davidson3 @SupunS @turbolent
