### ISSUE TITLE
Documentation incorrectly suggests that `getAuthAccount` is supported

### ISSUE THREAD

**Issue by irisjae** [onflow/cadence#1321]
Under the ['AuthAccount' section in the Documentation on 'Accounts'](https://docs.onflow.org/cadence/language/accounts/#authaccount), it is stated that 'A script can get the `AuthAccount` for an account address using the built-in `getAuthAccount` function', and the following signature is presented.
```
fun getAuthAccount(_ address: Address): AuthAccount
```

However, using this in a script triggers the following error in the playground, in the Flow emulator, and on testnet.
```
  |
3 |     getAuthAccount (address) }
  |  ^^^^^^^^^^^^^^ not found in this scope
```
This suggests that in fact `getAuthAccount` is not yet implemented and cannot be used in Cadence code yet. This can be verified with a simple Cadence script, called with any address.

```
pub fun main (address: Address) : Void {
        getAuthAccount (address) }
```

**Comment by SupunS** [comment]
Thank you for reporting this!

This support was added very recently (https://github.com/onflow/cadence/pull/1240), and hasn't made it to the playground/emulator/networks yet. The documentation pulls the content from the latest snapshot of the repo, and hence why it is visible on the docs. This feature would be available from the next release.

There is also a separate issue to anotate 'future facing features' in the docs (https://github.com/onflow/cadence/issues/1282), to avoid such confusion.

**Comment by SupunS** [comment]
This is now available in the emulator, testnet, and the mainnet with the secure cadence release.
