### ISSUE TITLE
cadence.Path to go value will return nil

### ISSUE THREAD

**Issue by yihau** [onflow/cadence#1324]
### Issue To Be Solved

cadence.Path's ToGoValue will return nil (https://github.com/onflow/cadence/blob/master/values.go#L1216)

### Suggested Solution

maybe return a string of path

```diff
func (v Path) ToGoValue() interface{} {
-	return nil
+      return v.String()
}

func (v Path) String() string {
	return format.Path(
		v.Domain,
		v.Identifier,
	)
}
```

**Comment by turbolent** [comment]
The `ToGoValue` functions got removed in #3291 (see linked discussion)
