### ISSUE TITLE
Resource object may lost when using switch-case to destroy

### ISSUE THREAD

**Issue by swordc** [onflow/cadence#1325]
### Problem
Hi guys,
We are from the Increment Labs which focusing on the flow development and ecosystem. We know cadence takes resouce security testing seriously. However, we found that:
> If a switch-case without default is used to destroy the resource object, the compiler fails to make a judgement on whether the resource is passed correctly. When passing a param which is not captured by the switch-case, the resource disappears.

### Steps to Reproduce

Testcase on playground:
https://play.onflow.org/813992f4-5e98-4449-8421-9a753b607d5f?type=account&id=0
```js
    // deploy successfully
    pub fun test(n:Int, res:@R) {
        // switch with no default
        switch n {
            case 1:
                log("1")
                destroy res
            case 2:
                log("2")
                destroy res
        }
    }
```
```js
    let r <- HelloWorld.mintR()
    // if pass n = 3, switch failed in catching and resource disappears
    HelloWorld.test(n: 3, res: <-r)
```

**Comment by dryruner** [comment]
This looks like a severe bug, attention needs to be raised and gets it fixed soon 👀

**Comment by SupunS** [comment]
Thank you for reporting the issue! 🙏  It looks like a bug in the switch-case dataflow analysis.

We are looking into this and will be fixing it soon 🤞
