### ISSUE TITLE
Include static type information of containers in JSON encoding

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#1378]
## Context

On a high-level, containers (arrays, dictionaries, optionals), have two kinds of types associated with them:
- The run-time type / concrete types of the values in the container
- The static type of the container

For example, the program `let dict: {String: Number} = {"foo": 0 as UInt256}` creates a dictionary value with static type `{String: Number}`, and the first element has type `String`/`UInt256`.

The JSON Cadence spec was created when we did not have static types for containers.

Currently, the encoding of the example is as follows and lacks the static type:

```json
{ 
	"type": "Dictionary",
	"value": [{ 
		"key": { "type": "String", "value": "foo" },
		"value": { "type": "UInt256", "value": "0" }
	}]
}
```

When we added static types to containers, we didn’t update the encoding (Cadence value -> JSON) to include the static type, so when decoding (JSON -> Cadence value), Cadence values end up without a static type. 

For backwards compatibility and this lack of static type information, the JSON argument decoding in Cadence actually infers the static type from the element values that are sent. This works in most cases, but is implicit and it would be better if it were explicit and cover all values.

## Definition of Done

- Extend the JSON Cadence spec to have a notion for static types in containers (dictionaries, arrays, optionals)
- Update encoding to include static type in JSON
- Update decoding to use static type if provided in JSON

**Comment by turbolent** [comment]
@SupunS I think this is implemented now, right?

**Comment by SupunS** [comment]
We only added it to the exporting (https://github.com/onflow/cadence/pull/1762). I think we still need to add it for importing.

**Comment by j1010001** [comment]
CCF has static type info, prioritizing usage of CCF codec over JSON
