### ISSUE TITLE
Improvements to Fungible and Non-fungible Token Standards

### ISSUE THREAD

**Issue by franklywatson** [onflow/cadence#1379]
There are a number of shortcomings to both the named standards as they are currently implemented where improvements and added language features will  seek to remedy. This epic is to capture the set of tasks along that journey. 

- [x] Initial Pitch
- [x] Community input received
- [ ] FLIPs proposed
- [ ] Implementation

**Comment by turbolent** [comment]
With the v2 standards released, this is complete now
