### ISSUE TITLE
Address(number) is interpreted by using ConvertUInt64

### ISSUE THREAD

**Issue by liuxiaobleach** [onflow/cadence#1380]
### Problem

(https://github.com/onflow/cadence/pull/1080/files
This PR changes how Address(number) is interpreted by using ConvertUInt64, however, ConvertUInt64 treats a number as negative if highest bit is set.
It causes Address(0xf8d6e0586b0a20c7) to fail with underflow error)

Example code:
```
// work
transaction {
  prepare(acct: AuthAccount) {
      let a: UInt64 = 0x7811223344556677
      log(Address(a))
  }
}

// panic
transaction {
  prepare(acct: AuthAccount) {
      let a: UInt64 = 0xf811223344556677
      log(Address(a))
  }
}
```

Or you can try script:
```
// work
pub fun main() {
  let a: UInt64 = 0x7811223344556677
      log(Address(a))
}

// panic
pub fun main() {
  let a: UInt64 = 0xf811223344556677
      log(Address(a))
}

```

In playground, it will work.
But error will occur in local emulator with flow-cli(version: v0.30.2).
```
error: underflow
```

**Comment by turbolent** [comment]
Thank you for the bug report @liuxiaobleach!

This bug was already previously reported in #1208 and is fixed on master through #1208. 

As the release of master will take a little longer, we plan to release it earlier through #1385, which backports the fix to the latest Cadence release.

**Comment by KSlashh** [comment]
So it's a bug? I thought it was a feature and do something like: 
```
pub fun uint64ToAddress(_ n: UInt64): Address {
        if (n >= 0x8000000000000000) {
            return Address(Int128(n)+0x10000000000000000)
        } else {
            return Address(Int128(n))
        }
    }
```
lol

**Comment by liuxiaobleach** [comment]
@turbolent 
Double check, is this fix already deployed on flow testnet?

**Comment by turbolent** [comment]
@liuxiaobleach No, this fix has not been released or deployed yet
