### ISSUE TITLE
casting and unwrapping at the same time

### ISSUE THREAD

**Issue by bjartek** [onflow/cadence#1386]
In the curent metadata standard there is a method
``` fun resolveView(_ type:Type) : AnyStruct?```

When you call that method you very often want to cast the resulting object as the type you sent in. So something like this?
```
let metadata=collection.borrowViewResolver(id: id).resolveView(Type<Voucher.Metadata>()) as! Voucher.Metadata
```
This gives no compile error as you have use `as!` but it will never succeed. The reason is that since resolveView returns an option you first have to unrwap it and then cast it. So this code will work

```
let metadata=collection.borrowViewResolver(id: id).resolveView(Type<Voucher.Metadata>())! as! Voucher.Metadata
```

Another issue I am pondering is why we need `as!` here. If i remove it i get
`mismatched types. expected Vouchre.Metadata?, got AnyStruct?` but I have clearly ! the value before i cast it.

**Comment by turbolent** [comment]
I think with #3580 this should be supported now.
