### ISSUE TITLE
Interface conformance requirements for contract updates is too restrictive

### ISSUE THREAD

**Issue by SupunS** [onflow/cadence#1394]
### Problem

The documents suggest that adding/removing/changing interface conformance for a struct/resource is possible during updating a contract: https://docs.onflow.org/cadence/language/contract-updatability/#structs-resources-and-interfaces

However, it is restricted in the implementation: https://github.com/onflow/cadence/blob/0ce830012ae0f3d9358b18a16ecbdb17bf20a95a/runtime/contract_update_validation.go#L492

### Suggested solution

Conformance check is only required for enums, as changing enum's type can cause data inconsistencies. However, this restriction can be lifted for other types of composite declarations.

**Comment by bluesign** [comment]
@SupunS We had a recent discussion on Discord. Do we only consider storage as breaking for contract updates?

Or are we also considering breaking other contracts ? ( With composability using this contract )

**Comment by SupunS** [comment]
We only consider maintaining the data consistency during the contract update validations, and by doing so, trying to maintain the 'type safety' of cadence. There is a note on the docs that also specifies the goal: https://docs.onflow.org/cadence/language/contract-updatability/#validation-goals

On contrary, trying to protect the other smart contract's composability would bring too many restrictions. I believe maintaining composability is a bigger and separate problem to be solved, that may need a separate solution, like versioning smart contracts, etc.

**Comment by bluesign** [comment]
> We only consider maintaining the data consistency during the contract update validations

Do you mean by breaking every time changes ? or does it possibility break changes included ?

**Comment by SupunS** [comment]
Yeah, if there is any 'potential to break', then we do not allow such updates. TBH I haven't fully think through all the cases, and what changes to conformances are OK and what are not. But there's definitely a mismatch between the docs and the implementation so we should rectify that.

My initial thought was it's ok to lift some/most of these restrictions on conformances for structs/resources, but I could be wrong.

**Comment by turbolent** [comment]
Currently, the validation requires the conformances to stay the same, ignoring order, i.e., same count and elements; and most developers are currently trying to add a conformance. So maybe we can just focus on what allowing that would entail? I guess adding a conformance is fine?

As @SupunS noted, if adding a conformance also requires changing existing data (i.e: adding a new field that is enforced by the new conformance), then the separate check for adding new fields would reject such an update. Adding a conformance which only requires functions should be safe, or at least I can’t think of a counter-example

**Comment by turbolent** [comment]
This has been released in 0.21.1
