### ISSUE TITLE
Backport BLS and RLP from master to v0.23

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#1426]
## Context

It would be nice to release the new BLS and RLP APIs before the Secure Cadence release.

## Definition of Done

- Branch v0.22 to v0.23 
- Backport the BLS and RLP PRs to v0.23

**Comment by dsainati1** [comment]
BLS PRs: 
* https://github.com/onflow/cadence/pull/1236
* https://github.com/onflow/cadence/pull/1250
* https://github.com/onflow/cadence/pull/1417

RLP PR:
* https://github.com/onflow/cadence/pull/1397
* https://github.com/onflow/cadence/pull/1423 (not yet merged)

**Comment by turbolent** [comment]
Done
