### ISSUE TITLE
"dereference failed" error does not indicate the location of the error

### ISSUE THREAD

**Issue by chandanworkacct** [onflow/cadence#1429]
### Problem

On testnet, emulator or playground, execution runs into an error called ""dereference failed"" but the error message does not indicate the line # or where the error came from. 

This[ testnet transaction ](https://testnet.flowscan.org/transaction/a975b61d4665cdce5f81f9d9a44bc526b4357e6e5db688fbc6102d49cb6ad72c)shows the error.

### Steps to Reproduce
This [playground link](https://play.onflow.org/e9773de8-2e66-44a4-96d9-d603f4e14a7f?type=tx&id=4b30db03-0d28-4c7d-ad2d-81bba4025613&storage=none) can help reproduce the issue,

**Comment by dsainati1** [comment]
This has since been fixed by https://github.com/onflow/cadence/pull/2194
