### ISSUE TITLE
Remove deprecated constant from the crypto contract

### ISSUE THREAD

**Issue by tarakby** [onflow/cadence#1447]
## Context

FVM updated the requirement about user signature tags to accept all tags (https://github.com/onflow/flow-go/pull/2171). The user tag is deprecated (not a protocol constant anymore) and should not be used. 
It is still hardcoded in the crypto contract to verify signatures (https://github.com/onflow/cadence/blob/49c7bc8/runtime/stdlib/contracts/crypto.cdc#L155) 

The crypto contract API could also take a tag parameter, which would be a breaking change.

The contract is currently part of the Cadence code base. We can take this opportunity to move the contract out of Cadence and deploy it on both testnet and mainnet. This allows future contract updates to happen without a spork.

### Definition of done: 
- [x] add a new tag parameter for the `verify` [function](https://github.com/onflow/cadence/blob/49c7bc8/runtime/stdlib/contracts/crypto.cdc#L87-L90) and use it to verify each signature.
- [x] remove the flow user tag from the contract
- [x] update the contract tests
- [ ] (optional) move the contract and tests outside of Cadence
- [ ] deploy the new contract to testnet and mainnet

**Comment by j1010001** [comment]
Hi @tarakby , is this still relevant ?

**Comment by tarakby** [comment]
Hi @j1010001 , yep

**Comment by tarakby** [comment]
Hi @j1010001 , this is a very long technical debt. I'm putting it on your radar again

**Comment by turbolent** [comment]
@tarakby Could you please add some reasoning why this should be done?

Given it is a breaking change, we would need to include it in the Stable Cadence release. So we need to get approval (FLIP) for it.

**Comment by tarakby** [comment]
As the linked PR mentions, the Flow protocol used to define two signature tags (one for transactions, one for all user applications). This Cadence contract used the second tag which was correct at that time. 
In February 2022, we decided that the Flow protocol should only define the transaction tag, it should deprecate the user tag, and let applications choose their own tags. That's when I created this issue and there were updates to other tools.
The Cadence crypto contract didn't get updated and some applications couldn't use it (for example FCL needed this code but ended up deploying its own contract use a different tag). 

I believe a protocol FLIP was needed in Feb 2022 to deprecate the user tag, but updating Cadence is only a technical debt. I don't believe a FLIP is needed at this point because the decision was already taken and implemented by other tools.

I also remember you mentioned that this contract should not be part of Cadence, so maybe stable Cadence could decide to not include it at all?

**Comment by turbolent** [comment]
Moving the `Crypto` contract out of Cadence will require:
- Moving the contract to the Flow core contracts repository (https://github.com/onflow/flow-core-contracts) (tiny)
- Move tests (small)
- Deploy the contract on all chains (medium)
- Add state migration which migrates existing stored values to the respective new deployed contract (large)

**Comment by turbolent** [comment]
@tarakby Can you please open a separate issue for moving the `Crypto` contract out of Cadence?

**Comment by tarakby** [comment]
I created https://github.com/onflow/cadence/issues/3135 for the contract migration task. Not sure if it's a breaking change though.
