### ISSUE TITLE
Add Dark Mode Support for Flow Developer Docs

### ISSUE THREAD

**Issue by onlychans1** [onflow/cadence#1449]
### Issue To Be Solved
My eyes are too used to reading in dark mode, so reading in light mode hits different 

### Suggested Solution
![image](https://user-images.githubusercontent.com/60107091/155796441-0f7cb38c-e00e-423c-b215-70d19425a5a6.png)

**Comment by turbolent** [comment]
Moved this issue to the proper repo

**Comment by turbolent** [comment]
Issue moved to [onflow/flow #845](https://github.com/onflow/flow/issues/845) via [**ZenHub**](https://www.zenhub.com/)
