### ISSUE TITLE
Inline small closure functions (e.g: `locationRangeGetter`)

### ISSUE THREAD

**Issue by SupunS** [onflow/cadence#1451]
### Issue To Be Solved

While adding some runtime changes, I noticed that small closure functions can lead to performance degradations.
e.g: Use of `locationRangeGetter` function in a hot-path decreased the performance by ~20% (compared to inlining).
```
                           old time/op    new time/op     delta
InterpretRecursionFib-2	   2.30ms ± 1%	  2.77ms ± 5%	  20.21%
```

Related diff: https://github.com/onflow/cadence/pull/1464/commits/54cf6972d3614161700c05eec6808d25ee538847

### Suggested Solution

We should inline such commonly used small closure functions. Currently known ones are:
- [x] `locationRangeGetter`

**Comment by turbolent** [comment]
@SupunS I tried inlining `locationRangeGetter` using the Goland inlining functionality, but there does not seem to be any difference. Maybe I'm missing something. Maybe we can sync on this?

**Comment by SupunS** [comment]
Thanks for having a look into this!

If I remember correctly, This: https://github.com/onflow/cadence/pull/1464/commits/54cf6972d3614161700c05eec6808d25ee538847 was the change where I saw this perf degradation (and hence changed it). There, the location range getter was created every time an identifier expr is visited, which we currently do not do. So maybe the current use of location range getter is not extensive enough to see a difference 🤔
