### ISSUE TITLE
Cannot cast &FungibleToken.Vault to &FungibleToken.Vault{FungibleToken.Balance}

### ISSUE THREAD

**Issue by jacob-tucker** [onflow/cadence#1479]
### Problem

When trying to cast a `&FungibleToken.Vault` type to a `&FungibleToken.Vault{FungibleToken.Balance}` type, you get this weird error: "Error invalid transfer of value: expected &FungibleToken.Vault{FungibleToken.Balance}". 

The same is true for other restricted types, like `&FungibleToken.Vault{FungibleToken.Receiver}` and `&FungibleToken.Vault{FungibleToken.Provider}`. I believe this is also a bug for &NonFungibleToken.Collection as well.

I have reproduced this error in both the playground and on the current version of TestNet. 

![image](https://user-images.githubusercontent.com/15198786/156807729-1499725b-4c47-4c24-ac75-3f3acc69139f.png)

### Steps to Reproduce

https://play.onflow.org/0d50d978-20eb-4328-b75c-4aff5d42240f?type=account&id=f7be17c7-953e-4728-ac7b-e23337d5e215&storage=none

If you run the transaction in the playground above, you should see the error at hand.

**Comment by turbolent** [comment]
@SupunS Added a reproducer in #1480 which shows the program is accepted by the type checker, but the value transfer check at run-time fails. Have not looked into why yet

**Comment by turbolent** [comment]
Thank you for the bug report @jacob-tucker!
