### ISSUE TITLE
Transferring values allocates memory twice unnecessarily

### ISSUE THREAD

**Issue by dsainati1** [onflow/cadence#1491]
### Problem

`transferAndConvert`, the function that is called when values are moved or assigned by the interpreter, makes calls to `Transfer` and to `checkValueTransferTargetType` for each invocation of the function:

https://github.com/onflow/cadence/blob/a882c958e9b8ebff17166caaa63c7476b0330ca3/runtime/interpreter/interpreter.go#L2089-L2118

If the value being transferred is a container value like an array, dictionary or composite, this results in each of the values contained in the container being loaded into memory twice. The first time occurs during the call to `Transfer`. In the case of arrays, this loads each value in the array into memory in order to construct a new array:

https://github.com/onflow/cadence/blob/a882c958e9b8ebff17166caaa63c7476b0330ca3/runtime/interpreter/value.go#L1995-L1996

The second time occurs during the call to `checkValueTransferTargetType`, when `DynamicType` is called on the value in question to ensure that it is a runtime subtype of the target type:

https://github.com/onflow/cadence/blob/a882c958e9b8ebff17166caaa63c7476b0330ca3/runtime/interpreter/interpreter.go#L2059

In the case of arrays, `DynamicType`, this calls `Walk` to check the dynamic type of each element of the array: 

https://github.com/onflow/cadence/blob/a882c958e9b8ebff17166caaa63c7476b0330ca3/runtime/interpreter/value.go#L1240

Which then calls `Iterate`: 

https://github.com/onflow/cadence/blob/a882c958e9b8ebff17166caaa63c7476b0330ca3/runtime/interpreter/value.go#L1229

Which then loads each element of the array from memory so that the walk function can be called on each of them:

https://github.com/onflow/cadence/blob/a882c958e9b8ebff17166caaa63c7476b0330ca3/runtime/interpreter/value.go#L1219

All told, this results in the values in the array each being loaded into memory two separate times unnecessarily, when the values that were loaded for the `Transfer` could instead be re-used for the runtime typecheck. The dictionary and composite value cases are similar.

**Comment by dsainati1** [comment]
Has this been fixed by removing dynamic types in favor of using the sema type hierarchy?

**Comment by turbolent** [comment]
Could be. Could you maybe check again what you described above still holds true on `master`?

**Comment by turbolent** [comment]
Awesome! Thanks for reporting this, it accelerated us removing the dynamic types and optimizing the dynamic type checks 🙏
