### ISSUE TITLE
Resource within an interface can't access variables of the interface

### ISSUE THREAD

**Issue by rahul-kothari** [onflow/cadence#150]
### Problem
Consider the code:
```
pub contract interface FungibleTokenInterface {
    pub var paused: Bool
    ...
    ...
    pub resource interface Vault: Provider, Receiver, Balance { //same as in the spec
        pub var balance: UFix64

        pub fun withdraw(amount: UFix64): @Vault {
            pre {
                FungibleTokenInterface.paused == false: "Can't withdraw when function is paused"
               ...
            }
    }
}
```
Here I defined **a contract variable in the interface** called `paused`. But I can't call that in the pre-condition of the withdraw method on the Vault **interface**.

Deploying this contract gives the error- "can't access `FungibleTokenInterface.`"

### Context
I had to shift the pre condition code to my actual contract. I just think putting this in the interface makes things cleaner.

**Comment by turbolent** [comment]
`FungibleTokenInterface` is a contract interface and not a concrete contract implementation, so this works as expected.
