### ISSUE TITLE
Prevent re-entrancy attacks

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#1543]
### Issue To Be Solved

Re-entrancy attacks are a common bug in smart contracts. 

Provide language-level support for avoiding re-entrancy issues.

### Suggested Solution

TDB

**Comment by bluesign** [comment]
I have some ideas and comments on this @turbolent, when you have some free time I would like to discuss in private.

**Comment by j1010001** [comment]
We will keep discussing improvement to prevent Re-entrancy attacks, closing the issue for now.
