### ISSUE TITLE
[LS] Better cache invalidation for imported program checkers

### ISSUE THREAD

**Issue by sideninja** [onflow/cadence#1570]
### Issue To Be Solved
The language server creates a new checker every time when checking the imported programs as seen here, this might be quite expensive and was done as a quick patch to a problem in production.

### Suggested Solution
The caching should be reverted and stay in place but there should be a cache invalidation system that is smarter, potentially by analyzing an inversed dependency tree and just invalidating the dependencies that changed.

**Comment by sideninja** [comment]
Base test suite indicates changes are processed correctly. Trying to set up the playground version at the time the issue was reported. Coming across some difficulties setting up that version.

**Comment by sideninja** [comment]
I see everything 👁️  😄  yes I did and thank you for that. It will serve well with this for sure. I'm working today to reproduce the bug locally with local playground setup. I want to make sure this is indeed causing the bug since when I now wrote tests it seemed like the cached checkers work ok.

**Comment by sideninja** [comment]
This recording (sorry for potato resolution) is showing that the bug with added members is not possible to recreate. I’ve chosen the version before any updates and even though there are bunch of other issues with UI (a lot of them are now fixed) the one with member not being visible is not reproducable by me. I was monitoring the LS communication and the responses are correct. This makes me conclude it probably isn’t a bug related to LS. I will make sure to extend tests in LS potentially to find any problems, but the base test I made for this problem is working which is another indication it’s not a problem from the LS. 
cc @turbolent @srinjoyc 

https://user-images.githubusercontent.com/75445744/167633602-4ff07673-2dfb-4689-9d15-4d949617e3c6.mov

**Comment by sideninja** [comment]
Waiting to sync with Bastian.

**Comment by KhaledAylii** [comment]
@sideninja @turbolent any news on this issue? Making changes in a contract and redeploying does not reflect in the types imported by other accounts or transaction type checkers - pretty much a development dead end

**Comment by KhaledAylii** [comment]
update: refreshing page solves the problem for now

**Comment by sideninja** [comment]
@KhaledAylii I plan to work on this in the following days.
