### ISSUE TITLE
Dynamic assignment to AnyStruct type using ternary operator

### ISSUE THREAD

**Issue by avcdsld** [onflow/cadence#1608]
### Issue To Be Solved

I would like to use the ternary operator to dynamically determine the type to put into `AnyStruct` type, but the current Cadence gives me an error:
```
mismatched types. expected MetadataViews.IPFSFile, got MetadataViews.HTTPFile
```

This is a sample code to reproduce it:
https://play.onflow.org/fec66ae7-8807-4331-9479-c6ef56020c57?type=account&id=91bf23c8-5b28-4c3f-85a8-a5f0da61e21a&storage=none

In fact, this is not a big problem, but it would be better to make the code shorter if possible.

```cadence
pub contract MetadataViews {
    pub struct Display {
        pub let thumbnail: AnyStruct{File}

        init(thumbnail: AnyStruct{File}) {
            self.thumbnail = thumbnail
        }
    }

    pub struct interface File {
    }

    pub struct HTTPFile: File {
    }

    pub struct IPFSFile: File {
    }

    init() {
        // OK
        let htmlFile = Display(thumbnail: HTTPFile())

        // OK
        let ipfsFile = Display(thumbnail: IPFSFile())

        // NG
        // let flag = true
        // let ipfsOrHitmlFile = Display(thumbnail: flag ? IPFSFile() : HTTPFile())

        // OK
        let flag = true
        var thumbnail: AnyStruct{File}? = nil
        if flag {
            thumbnail = IPFSFile()
        } else {
            thumbnail = HTTPFile()
        }
        let ipfsOrHitmlFile = Display(thumbnail: thumbnail!)
    }
}

```

### Suggested Solution

I would like to be able to code the following.

```cadence
let flag = true
let ipfsOrHitmlFile = Display(thumbnail: flag ? IPFSFile() : HTTPFile())
```

**Comment by SupunS** [comment]
Thanks @avcdsld for reporting! This was improved in https://github.com/onflow/cadence/pull/1027 and would be available in the upcoming release.

**Comment by avcdsld** [comment]
Thanks for the improvements, I'm glad Cadence is better!

**Comment by SupunS** [comment]
This is now available with the secure cadence release
