### ISSUE TITLE
Allow use of run-time types for capability functions

### ISSUE THREAD

**Issue by aishairzay** [onflow/cadence#1617]
### Issue To Be Solved

Currently the following examples (and similar examples) do NOT work:
```cadence
let runTimeType: Type = Type<&{NonFungibleToken.CollectionPublic}>()
signer.link<runTimeType>(/public/testpath, target: /storage/testpath)
```
And
```cadence
let runTimeType: Type = Type<&{NonFungibleToken.CollectionPublic}>()
signer.borrow<runTimeType>(from: /storage/testpath)
```

This is because cadence requires that the type be static.

This imposes restrictions on contracts and transactions because there is no way to reference an already stored type to borrow or link a contract without explicitly importing the expected type and statically including it in code.

This is currently a blocker for creating a way to programmatically set up an account for a unique NFT collection without requiring some client-side templating for a transaction.

### Suggested Solution

Have cadence allow the following to work as expected, and also work for related functions that use T as a type:

```cadence
let runTimeType: Type = Type<&{NonFungibleToken.CollectionPublic}>()
signer.link<runTimeType>(/public/testpath, target: /storage/testpath)
```

i.e. link's <> may take in an `AnyStruct` and allow for both type T or type Type to be valid

or

Have a separate set of cadence APIs which allow cooperation with runTime types. I.e.
```cadence
let runTimeType: Type = Type<&{NonFungibleToken.CollectionPublic}>()
signer.borrow(from: /storage/testpath, type: runTimeType)
```

I'm also interested in hearing if there are any technical limitations to supporting this (like whether or not the underlying implementation of `link` requires a static type for reasons I would not know myself)

**Comment by bjartek** [comment]
Yes please!

**Comment by turbolent** [comment]
@aishairzay The current capability API was introduced before run-time types existed. 

There is no technical limitation for linking the capability using a run-time type. This could be added.
I highly suggest proposing this in this FLIP, which attempts to replace the current capability API with a better one:
https://github.com/onflow/flow/pull/798

However, it will not be possible to borrow the capability using a run-time type, as the type checker needs to  be able to statically know what the result of the function is going to be.

**Comment by turbolent** [comment]
For linking, we could either: 
- Add a new function. Maybe something like `linkWithTag`
- Extend the existing `link` function and add an optional parameter `type: Type`, then require it if the function's type argument is not given, e.g. `link<T>(source, target: target)` or `link(source, target: target, type: Type<T>())` would be equivalent

**Comment by bluesign** [comment]
I am not sure this will be good addition to the language. This will create a foot gun in my opinion. 

Consider :

```
var someRef : &FlowToken.Vault{FungibleToken.Receiver} = ....
link(source, target: target, type: someRef.getType())
```

This will link `&FlowToken.Vault` instead of restrictions.

**Comment by veganbeef** [comment]
I also agree with @aishairzay that this issue is a major blocker for most kinds of dynamic transactions. The fact that run-time types are effectively read-only means that any type one wishes to use must be a static type with a hard-coded import from a contract. This is especially difficult given Dapper Wallet's requirement for all approved transactions to be completely static, meaning there's no way to initialize a Dapper Wallet account to receive a dynamic set of NFT collections, for example.

I understand your concerns @bluesign, so this would probably require a way to include capabilities as part of types, making this potentially a much larger feature to implement, but I definitely think it's a much needed feature.

**Comment by turbolent** [comment]
@veganbeef can you elaborate on the "include capabilities as part of types" part?

**Comment by turbolent** [comment]
A question on Discord just asked about the ability to pass a run-time type to the `check` function. Just like for `link`, support for run-time types could be added for that function.

**Comment by bjartek** [comment]
@turbolent I _think_ he means interface restrictions in types.

**Comment by cybercent** [comment]
I'm also interested in this.

**Comment by austinkline** [comment]
Adding in that this would be very helpful as cadence 1.0 is coming. If we could link with runtime types, platforms like Flowty would be able to link collections according to the collection author's specifications without having to generate a different transaction for each one (which won't work with dapper wallet restrictions)

**Comment by turbolent** [comment]
Adding the ability to issue a capability with a run-time type should be easy to add.

What would be a good name for this function? `issueWithType`? (but `issue` also takes a type argument, it's just a static type and not a run-time type value ...)

**Comment by austinkline** [comment]
Would we be able to cast the untyped capability to its properly typed version?

Method name makes sense to me

**Comment by j1010001** [comment]
C1.0 Discord thread: https://discord.com/channels/613813861610684416/621847426201944074/1194705503754919967
