### ISSUE TITLE
Make composite type information of elaboration serializable

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#1636]
### Issue To Be Solved

We would like to store composite type information, which is computed by the type checker and saved in the elaboration, in the execution state. This would allow us to load type information as-is, without having to potentially re-parse and re-check contracts.

### Suggested Solution

- [ ] Determine which parts of the elaboration should be saved and if it is available
  - Composite members?
- [ ] (Add missing information to elaboration, if missing ^)
- [ ] Determine serialization format
  - CBOR, like Cadence value serialization?
  - Or format closer to external encoding format? Not determined yet
- [ ] Implement serialization
- [ ] Implement deserialization
- [ ] Tests

**Comment by robert-e-davidson3** [comment]
The landing of PR #1830 closes this issue. There's more work to be done to make a serialized Elaboration useful.
