### ISSUE TITLE
error: missing value for member `getEpoch`

### ISSUE THREAD

**Issue by pgebheim** [onflow/cadence#1638]
### Problem

blocto is trying to run this script:
```cadence
import BloctoTokenStaking from 0x6e0797ac987005f5

pub fun main(): UInt64 {
    return BloctoTokenStaking.getEpoch()
}
```
they get this error:

```
:x: Invalid argument: failed to execute script: failed to execute script at block (95b8a59e3d382ac68fd198966f09d36591eb587273467ce35543d1eae7f5e072): [Error Code: 1101] cadence runtime error Execution failed:
error: missing value for member `getEpoch`
 --> 2fa669ef7fce4635138cf632580cc040abbc5ac5f3a149b1e80ed0583c7e0a00:5:11
  |
5 |     return BloctoTokenStaking.getEpoch()
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^

:pray: Check your argument and flags value, you can use --help.
```

Checking the contract, that function seems to be there: https://flow-view-source.com/testnet/account/0x6e0797ac987005f5/contract/BloctoTokenStaking

## More information
- There is a flow-go remote script debug setup in the branch here: `janez/debug-blocto-09052022`

**Comment by pgebheim** [comment]
Blocto reported that they have updated a couple of times since the initial deploy.

**Comment by j1010001** [comment]
Not reported since, working after contract redeployment, closing
