### ISSUE TITLE
Compact Cadence Value External Encoding (CBF codec)

### ISSUE THREAD

**Issue by robert-e-davidson3** [onflow/cadence#1651]
Cadence external value encoding optimizations will include adding an alternative to the existing JSON-based encoding for external Cadence values is in development. External encodings are used for Cadence values sent as transaction arguments, for values returned from scripts, and events.

This new encoding will improve the speed of encoding/decoding, reduce size of payloads that transfer Cadence values, and unlike the JSON-based encoding, will have a canonical form. It will also enable storing type information on-chain, avoiding repeated parsing and type-checking of Cadence types during execution. 

This new encoding can be deployed while maintaining backwards compatibility with the existing JSON encoding, but to realize the performance benefits we will need to update the clients (internal to protocol, as well as external like SDKs) to use the new encoding.

**References:**
[Primary notion doc](https://www.notion.so/dapperlabs/Cadence-External-Value-Encoding-28d7849462724f9abeb80b306431abce)

Original notion doc: [Make composite type information of elaboration serializable](https://www.notion.so/dapperlabs/Compact-Cadence-Value-External-Encoding-fe380872bc84434b875489de1b0ad407)

**Comment by robert-e-davidson3** [comment]
Related? [Move storage encoding/decoding #224](https://github.com/onflow/cadence/issues/224)

**Comment by j1010001** [comment]
Closing in favor of redesigned solution captured in: https://github.com/onflow/cadence/issues/2157
