### ISSUE TITLE
Expose runtime storage internally

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#1677]
### Issue To Be Solved

Embedders of Cadence would like to get access to the runtime storage, e.g. to get access to the storage map of an account and inspect stored data, modify it, etc.

### Suggested Solution

- We can easily add a function `Storage(context Context) *runtime.Storage` to `runtime.Runtime`, which e.g. gives access to storage maps via `runtime.Storage.GetStorageMap`
- `StorageMap`'s API is fairly "low-level", e.g. `ReadValue` just accepts a `key string`, not a high-level path
- `interpreter.StorageMap.ReadValue` could be changed to just accept a memory gauge, at that point, an interpreter is not required
- However, most read operations on the returned `interpreter.Value`, e.g. reading a field from a composite value through `intererpreter.CompositeValue.GetField` require an interpreter instance. Such read cases could also be changed to just accept a memory gauge
- However, mutating operations, e.g. writing a field of a composite value through `interpreter.CompositeValue.SetMember` require an interpreter with configured storage
- Should we also return a "dummy" interpreter from `Runtime.Storage(Context)` which can be used for this purpose? It should not be used for anything else though, which would make such an API brittle

**Comment by turbolent** [comment]
I opened #1679 as a draft. It demonstrates how simples values can be read, we might want to extend this to allow arbitrary access to any complext object graph

**Comment by bluesign** [comment]
@turbolent I am coding something similar (though stuck on atree a bit), can you expand on: 

> reading a field from a composite value through intererpreter.CompositeValue.GetField require an interpreter instance

in what cases this is necessary ?

**Comment by turbolent** [comment]
@bluesign 

> I am coding something similar, a storage browser (though stuck on atree a bit)

Oh nice! I was discussing this with @sideninja before. The main use case of this work will be the Playground and Emulator, to allow storage inspection, and potentially also mutation, e.g. to quickly remove a value from an account that was stored using a transaction, without having to write a full TX that does that.

> > reading a field from a composite value through intererpreter.CompositeValue.GetField require an interpreter instance
> 
> in what cases this is necessary ?

Well, `CompositeValue.GetField` requires an `interpreter *Interpreter` as an argument right now, but only uses for an option (`invalidatedResourceValidationEnabled`) and passes it to `StoredValue` at the end – but `StoredValue` only actually requires a memory gauge.
