### ISSUE TITLE
Interaction limit skewed due to double-counting of contract imports

### ISSUE THREAD

**Issue by j1010001** [onflow/cadence#1684]
Seems like we are skewing interaction limit by counting contract imports multiple times if the same contract is imported via multiple branches in the dependency tree.

We need to fix this and only count one contract ones to ensure the interaction limit is correctly applied.

more context here: https://axiomzen.slack.com/archives/CG0B7CJAJ/p1654031627213579

**Comment by j1010001** [comment]
We should still fix this, Daniel has a proposal on how to sove it, requires sync with Ramtin.

**Comment by j1010001** [comment]
Majority of the effort to fix this is on the FVM side (programs-cache)

**Comment by turbolent** [comment]
We might want to reconsider this, given that it is causing problems when using e.g. storage iteration. See #2279

**Comment by j1010001** [comment]
Few more notes: this is a very hard problem to solve. We probably could do a sub-optimal solution, but when we have compiled code stored on chain and we get rid of the program cache, this would no longer be a problem.
