### ISSUE TITLE
Unable to update the field in structure.

### ISSUE THREAD

**Issue by danishtroon** [onflow/cadence#1687]
### Problem
I am unable to update the new field in structure on the test net.

I am unable to update the new field in structure on the test net. I have a contract on the testnet I want to update the structure and want to add the new field in the structure but I am unable to update it. Is there any way to update the structure and add a new field in the structure?

### Steps to Reproduce
- deploy the contract having a structure in it on the testnet.
- add a new field in the structure and try to update the contract.
- you would get errors `found new filed in the structure`.

**Comment by turbolent** [comment]
Adding fields is not supported, see https://docs.onflow.org/cadence/language/contract-updatability/
