### ISSUE TITLE
Proposal for Cadence Repo organization

### ISSUE THREAD

**Issue by joshuahannan** [onflow/cadence#170]
### Issue To Be Solved

We've been talking about how we like cadence projects to be organized in github repos and have come up with a proposal that could use some feedback. The ways that out projects are currently organized is not very good and makes it seem like more of a Go project than cadence project, so we decided to change the hierarchy to put the cadence files more in the front. 

### Suggest A Solution

Here is our proposal:

`contracts/ ` contains the cadence smart contract source code
`transactions/` contains the scripts and transactions that are used to interact with the smartcontracts
`lib/go`, `lib/js`, etc contains language specific tools and packages for interacting with the smart contracts. These can include packages to return formatted transactions, contracts, and tests.

Within the `lib/go/` directory, we have broken up it into 3 packages:

`contracts`: package for getting the text of the contracts in a repo, replacing some names and fields for customization
`templates`: packages for returning common transaction templates for the smart contracts. Uses the transaction templates in `transactions/` to construct them.
`test`: contains all the automated test related code for testing your smart contract

This is still a work in progress, so please give feedback about the structure of the repo, the package organization, and whatever else you feel is important.

**Comment by joshuahannan** [comment]
Example: https://github.com/onflow/flow-nft/tree/josh/reorg

**Comment by turbolent** [comment]
I think bringing the Cadence code to the root and adding the ability to provide wrapper libraries for other languages is a great idea and I like the proposal.

👍 from me

**Comment by benjaminkvm** [comment]
Really like this new structure and find it much more intuitive! 👏 

One other thought, breaking out scripts from the `transactions` directory as they technically aren't transactions within the context of Flow.

The root would then look like this:

`/contracts/`
`/scripts/`
`/transactions/`
`/lib/{js,go,...}/`

Thoughts?

**Comment by joshuahannan** [comment]
yeah, I think this makes sense. Good to split it up.

**Comment by joshuahannan** [comment]
This has been completed and can be closed
