### ISSUE TITLE
Overflow in json encode on Type

### ISSUE THREAD

**Issue by bjartek** [onflow/cadence#1704]
When returning a type from a resource Type I get an overflow in flow-cli 0.35.0
﻿
see gist for error message: https://gist.github.com/bjartek/0e855d238564a0013e239d55ce46c395

script is here: https://github.com/findonflow/find/blob/ben/find-203-find/scripts/test.cdc

Instructions:
 - clone branch
 - start emulator `flow emulator -v`
 - deploy contracts `flow project deploy -n emulator`
 - run script `flow scripts execute scripts/test.cdc`

**Comment by turbolent** [comment]
I managed to create a reproduction in #1705, working on a fix now
