### ISSUE TITLE
Documentation provides incorrect code sample

### ISSUE THREAD

**Issue by fcostasilva** [onflow/cadence#1713]
I just started reading the documentation from scratch and noticed this problem: the section [Cadence Design Patterns / Script-Accessible report](https://docs.onflow.org/cadence/design-patterns/#script-accessible-report) provides a sample code with incorrect return. Instead of 

```cadence
// Return the struct with a script
pub fun main(): A.BReport {
    let b: AContract.BResource // Borrow the resource
    let report = b.generateReport()
    return b
}
```
The comment suggests the actual code should be

```cadence
// Return the struct with a script
pub fun main(): A.BReportStruct {
    let b: AContract.BResource // Borrow the resource
    let report = b.generateReport()
    return report
}
```
I would also directly return the response of `b.generateReport` directly instead of assigning it to a variable. 
I can raise a pull request to fix this myself, just need a green light here.

**Comment by turbolent** [comment]
Thank you for flagging this mistake. A pull request with your suggestions would be very welcome!
