### ISSUE TITLE
Omit unnecessary types from messages

### ISSUE THREAD

**Issue by robert-e-davidson3** [onflow/cadence#1714]
[Notion doc](https://www.notion.so/dapperlabs/Cadence-External-Value-Encoding-28d7849462724f9abeb80b306431abce#c06c89588918402d88b46575583b3f77)

Depends on https://github.com/onflow/cadence/issues/1636.

When the client has access to types separate from the contracts, the client is able to encode arguments and parse return values and events without needing to include all types.

**Comment by robert-e-davidson3** [comment]
Tangentially related work done for storage: https://github.com/onflow/cadence/issues/834

**Comment by j1010001** [comment]
Closing in favor of redesigned solution captured in: https://github.com/onflow/cadence/issues/2157
