### ISSUE TITLE
Use custom encoding for external cadence values

### ISSUE THREAD

**Issue by robert-e-davidson3** [onflow/cadence#1715]
[Notion doc](https://www.notion.so/dapperlabs/Cadence-External-Value-Encoding-28d7849462724f9abeb80b306431abce#85cc642ae6944be4a1aa24dac2dc4462)

Depends on https://github.com/onflow/cadence/issues/1636.

I did a little research into the size efficiency of different encoding strategies. A custom encoder produces much smaller messages than JSON or CBOR. Using my fake data and omitting types, JSON and CBOR use 50% as many bytes while the custom encoder uses 20% as many bytes.

I didn't measure speed but it's very unlikely that a custom encoder will be slower than JSON encoding. CBOR encoding might be comparable except it requires intermediate data structures to omit type information whereas the custom encoder does not.

The custom encoder described in [this notion doc](https://www.notion.so/dapperlabs/Research-Encoding-Size-ac297bf21089467b9bab9154361fc900#5c47672f6cce4d68920270447c8fcb6e) is for my research. It definitely is not final and may need to be entirely redesigned.

------

Values to encode:
- [x] EncodedValueVoid
- [x] EncodedValueOptional
- [x] EncodedValueBool
- [x] EncodedValueString
- [x] EncodedValueBytes
- [x] EncodedValueCharacter
- [x] EncodedValueAddress
- [ ] EncodedValueInt
- [ ] EncodedValueInt8
- [ ] EncodedValueInt16
- [ ] EncodedValueInt32
- [ ] EncodedValueInt64
- [ ] EncodedValueInt128
- [ ] EncodedValueInt256
- [ ] EncodedValueUInt
- [ ] EncodedValueUInt8
- [ ] EncodedValueUInt16
- [ ] EncodedValueUInt32
- [ ] EncodedValueUInt64
- [ ] EncodedValueUInt128
- [ ] EncodedValueUInt256
- [ ] EncodedValueWord8
- [ ] EncodedValueWord16
- [ ] EncodedValueWord32
- [ ] EncodedValueWord64
- [ ] EncodedValueFix64
- [ ] EncodedValueUFix64
- [x] EncodedValueArray
- [ ] EncodedValueDictionary
- [ ] EncodedValueStruct
- [ ] EncodedValueResource
- [ ] EncodedValueEvebt
- [ ] EncodedValueContract
- [ ] EncodedValueLink
- [ ] EncodedValuePath
- [ ] EncodedValueCapability
- [ ] EncodedValueEnum

Types to encode:
- [x] EncodedTypeVoid
- [ ] EncodedTypeNever
- [x] EncodedTypeBool
- [x] EncodedTypeArray
- [x] EncodedTypeOptional
- [x] EncodedTypeString
- [x] EncodedTypeCharacter
- [x] EncodedTypeBytes
- [x] EncodedTypeAddress
- [ ] EncodedTypeNumber
- [ ] EncodedTypeSignedNumber
- [ ] EncodedTypeInteger
- [ ] EncodedTypeSignedInteger
- [ ] EncodedTypeFixedPoint
- [ ] EncodedTypeSignedFixedPoint
- [ ] EncodedTypeInt
- [ ] EncodedTypeInt8
- [ ] EncodedTypeInt16
- [ ] EncodedTypeInt32
- [ ] EncodedTypeInt64
- [ ] EncodedTypeInt128
- [ ] EncodedTypeInt256
- [ ] EncodedTypeUInt
- [ ] EncodedTypeUInt8
- [ ] EncodedTypeUInt16
- [ ] EncodedTypeUInt32
- [ ] EncodedTypeUInt64
- [ ] EncodedTypeUInt128
- [ ] EncodedTypeUInt256
- [ ] EncodedTypeWord8
- [ ] EncodedTypeWord16
- [ ] EncodedTypeWord32
- [ ] EncodedTypeWord64
- [ ] EncodedTypeFix64
- [ ] EncodedTypeUFix64
- [ ] EncodedTypeVariableSizedArray
- [ ] EncodedTypeConstantSizedArray
- [ ] EncodedTypeDictionary
- [ ] EncodedTypeStruct
- [ ] EncodedTypeResource
- [ ] EncodedTypeEvent
- [ ] EncodedTypeContract
- [ ] EncodedTypeStructInterface
- [ ] EncodedTypeResourceInterface
- [ ] EncodedTypeContractInterface
- [ ] EncodedTypeFunction
- [ ] EncodedTypeReference
- [ ] EncodedTypeRestricted
- [ ] EncodedTypeBlock
- [ ] EncodedTypeCapabilityPath
- [ ] EncodedTypeStoragePath
- [ ] EncodedTypePublicPath
- [ ] EncodedTypePrivatePath
- [ ] EncodedTypeCapability
- [ ] EncodedTypeEnum
- [ ] EncodedTypeAuthAccount
- [ ] EncodedTypePublicAccount
- [ ] EncodedTypeDeployedContract
- [ ] EncodedTypeAuthAccountContracts
- [ ] EncodedTypePublicAccountContracts
- [ ] EncodedTypeAuthAccountKeys
- [ ] EncodedTypePublicAccountKeys
- [ ] EncodedTypeAnyType
- [ ] EncodedTypeAnyStructType
- [ ] EncodedTypeAnyResourceType
- [ ] EncodedTypeArrau     // TODO is this necessary?
- [ ] EncodedTypeComposite // TODO is this necessary?
- [ ] EncodedTypeInterface // TODO is this necessary?
- [ ] EncodedTypeMetaType

**Comment by j1010001** [comment]
Closing in favor of redesigned solution captured in: https://github.com/onflow/cadence/issues/2157
