### ISSUE TITLE
The `check` function panics when checking a path set by an account that hasn't updated the contract to stable cadence

### ISSUE THREAD

**Issue by cybercent** [onflow/cadence#1729]
### Problem

The `check` function panics when checking a path set by an account that hasn't updated the contract to stable cadence.

### Steps to Reproduce

test.cdc
```cadence
import TopShot from 0x0b2a3299cc857e29

pub fun main(address: Address): Bool {
    let owner = getAccount(address)
    let cap = owner.getCapability<&{TopShot.MomentCollectionPublic}>(/public/MomentCollection)

    return cap.check()
}
```

```
flow scripts execute test.cdc -n mainnet 0xe0413d7b8f50d66d
```

ERROR:
```
❌ Invalid argument: failed to execute script: failed to execute script at block (ad4268b90d7913033bad1718773430e8736ae6f0906e1292f49b037059f1c8e9): [Error Code: 1101] cadence runtime error Execution failed:
error: Checking failed:
error: mismatched types
   --> 67af7ecf76556cd3.ABD:486:20

error: mismatched types
   --> 67af7ecf76556cd3.ABD:639:20

error: mismatched types
   --> 67af7ecf76556cd3.ABD:654:27
```

The ABD contract was not updated to stable Cadence and it uses the same path as NBA TS so it makes good example to reproduce the issue on Mainnet.

**Comment by cybercent** [comment]
The ABD contract was updated so you won't be able to use that contract to reproduce the issue.

**Comment by turbolent** [comment]
This works as expected: Importing code, explicitly through an import statement, or implicitly by using a stored value of a particular type, parses and type-checks the code. If it the imported code fails to parse or type-check, the importing program is aborted.

**Comment by cybercent** [comment]
@turbolent thanks. I’ll close the issue as it’s the expected behavior.
