### ISSUE TITLE
Re-Destroy optional resource

### ISSUE THREAD

**Issue by KSlashh** [onflow/cadence#1784]
### Bug Desciption
Resource is supposed to be destroy only once, so is the optional resource. But, if an interface destroy an optional resource in the pre condition, and an inherited function also destroy the optional resource, it will not cause any error. In fact, if you haven't destroy the optional resource in the inherited function, you will get `error: lose of resource` when deploy. Not sure it's a bug or a feature.

### Example
+ [https://testnet.flowscan.org/contract/A.203ea2804f661311.ResourceTest/overview](https://testnet.flowscan.org/contract/A.203ea2804f661311.ResourceTest/overview)
+  [https://testnet.flowscan.org/transaction/7c7a9347e16291a9c6f1e2c73e20b47909b4d7db72a3269ae64921784aa0f0e0/script](
https://testnet.flowscan.org/transaction/7c7a9347e16291a9c6f1e2c73e20b47909b4d7db72a3269ae64921784aa0f0e0/script)

**Comment by SupunS** [comment]
Thanks for reporting this. Yes, there is room for improvement here. At the moment resource invalidation happens at two stages:
1) Statically - when the code is deployed 
2) Dynamically - when the program runs

The scenario you mentioned is currently caught only when the program is running (i.e: dynamic check). As you correctly pointed out, it could be improved to also give a static error during the type checking of the program.

**Comment by turbolent** [comment]
@dsainati1 I think this will be resolved once conditions become view contexts?

**Comment by turbolent** [comment]
This will be resolved with the Stable Cadence release: [FLIP 1056](https://github.com/onflow/flow/blob/master/flips/20220715-cadence-purity-analysis.md) will require conditions to only call view functions, and moving a resource is considered impure.

Testing the linked program above will fail statically:
```
error: Impure operation performed in view context
  --> test.cdc:19:16
   |
19 |                 ResourceTest.checkTicket(<-ticket): "invalid ticket"
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
