### ISSUE TITLE
Iterator / cursor for larger resources

### ISSUE THREAD

**Issue by bshahid331** [onflow/cadence#1799]
### Issue To Be Solved

Currently for certain whale NFT wallets, if you try to load the collection resource or `getIDs` you get a memory error.

### Suggested Solution

It would be nice if we had a way to iterate over a specific resource that is taking up a lot of space. That or some sort of way of cursoring through an object.

I'd be interested in hearing about other solutions but currently the Alchemy API for example just fails for any whale wallets.

**Comment by turbolent** [comment]
Opened #1938 to propose a feature
