### ISSUE TITLE
Add convenience methods for working with account keys at runtime in Cadence

### ISSUE THREAD

**Issue by franklywatson** [onflow/cadence#1846]
### Issue To Be Solved

There aren't any convenience methods for working with account keys in Cadence, so therefore you have to iterate over them to determine the number of keys and most recent key index. Taking it further, when revoking a key, more code has to be written that will revoke old keys and set a new key as the only one that is valid. 

### Suggested Solution

Cadence could provide convenience methods to achieve the same: 

* acct.keys.length() 
* acct.keys.replaceKeys(publicKey: hashAlgorithm: weight:)

**Comment by robert-e-davidson3** [comment]
The work needed to add either method is similar to the work done here: https://github.com/onflow/cadence/pull/1845#pullrequestreview-1050039961.

This ticket requires more work: the FVM interface needs to be extended. Presently it has `GetAccountKey` but needs something like `GetAccountKeys` (plural) or `GetAccountKeyCount`, depending on the approach taken.

The FVM implementation for adding an account key uses `Accounts.GetPublicKeyCount` to decide the index of the soon-to-be-added account key. That method can be used, ultimately, for supporting Cadence having `AuthAccount.keys.length`.

An alternative to `length` or `replaceKeys` is to return an array of account keys. It would be helpful if the returned values included whether or not the key was revoked.

**Comment by turbolent** [comment]
- Iteration over keys has already been proposed in #1388 and is in progress
- `replaceKeys` seems like a short-hand for revoke + add. I'd argue that the language should only provide the building blocks and such higher-level helper functions can be built on top
