### ISSUE TITLE
Write and publish forum post detailing use of compact cadence codec in SDKs

### ISSUE THREAD

**Issue by robert-e-davidson3** [onflow/cadence#1867]
When the compact codec for external cadence values is finished, SDKs need to integrate it to use it. This may involve running a webworker for Go wasm code or a javascript version of the codec. In either case, a detailed explanation of how to use the codec is needed.

This ticket is complete when a forum post is published with these details.

**Comment by bluesign** [comment]
Is there a spec for the new codec somewhere?

**Comment by j1010001** [comment]
Closing in favor of redesigned solution captured in: https://github.com/onflow/cadence/issues/2157
