### ISSUE TITLE
Support for structural typing

### ISSUE THREAD

**Issue by satyamakgec** [onflow/cadence#1875]
### Issue To Be Solved

Developers are deploying an interface and ensuring the implementing contract inherits it while implementing the definition.

Can't we do it similarly to solidity, where developers can create an interface that tells whether the contract has the support of provided interface APIs without deploying it explicitly? I think that will makes it handier.

Example - There are numerous `FungibleToken` contracts (Let's say they set `A`) in the Flow blockchain, which implements the `FungibleToken` interface 

Now I create a new interface called `FungibleTokenMintable` with the `MinterResource` in addition to the FungibleToken interface declarations. Now my new contract wants to accept those fungible tokens with the `FungibleTokenMintable.Minter Resource`.  so does set my new contract can receive set `A` contracts? as those contracts were deployed before and are not explicitly implementing the `FungibleTokenMintable.Minter` resource even though they are supporting the `MinterResource` that has a similar API definition as `FungibleTokenMintable.MinterResource`

### Suggested Solution

I don't know how the interfaces are implemented in cadence language, so I don't know the solution. Still, if we somehow allow typecasting of the interfaces to one another by making sure that it supports the similar function signature, then it would be easy to do so instead of interface objects. 

Reference - https://discord.com/channels/613813861610684416/621847426201944074/1006097648320782336

**Comment by turbolent** [comment]
I think what you are referring to is [structural typing](https://en.wikipedia.org/wiki/Structural_type_system). Cadence currently only, and intentionally, supports [nominal typing](https://en.wikipedia.org/wiki/Nominal_type_system). 

I vaguely remember that we had a discussion about this very early on, but I'm a bit fuzzy on the details. As far as I can remember, @dete brought up some security concerns.

From an implementation point of view, one concern might be the cost of determining if a certain type conforms to an interface at each use-site.

BTW, the term "pure" usually relates to functions, i.e. [pure functions](https://en.wikipedia.org/wiki/Pure_function).

**Comment by turbolent** [comment]
Feel free to add this to the agenda for the [Language Design Meetings](https://docs.google.com/document/d/1KMGdiZ7qX9aoyH2WEVGHjsvBTNPTN6my8LcNmSVivLQ/edit), so we can discuss this.

**Comment by turbolent** [comment]
https://wiki.c2.com/?NominativeAndStructuralTyping has a good example where structural typing is a potential foot-gun

**Comment by turbolent** [comment]
No progress in a long time, closing for now. Please open a new issue if you still feel like this should exist.
