### ISSUE TITLE
Cadence Interpreter Optimizations

### ISSUE THREAD

**Issue by j1010001** [onflow/cadence#1883]
This epic tracks investigations and performance improvements of the tree-walking interpreter, for example by compiling to functions. Interpreters can potentially also be reused and certain operations can be performed concurrently.

**Comment by turbolent** [comment]
- #1899
- #1888
- #1831
- #1825
- #1813

**Comment by turbolent** [comment]
@j1010001 I think that's all improvements we have so far. OK to close? (We can create another issue/epic when we do more)
