### ISSUE TITLE
`toBigEndianBytes` for `UInt256`, `UInt128`, and `Int128` may not result in what we want

### ISSUE THREAD

**Issue by xiyu1984** [onflow/cadence#1913]
### Issue To Be Solved
The following script shows what happened when we call `toBigEndianBytes` for `UInt256`, `UInt128`, and `Int128`. 
```cadence

pub fun main(): [UInt8] {
    let a: UInt256 = 1;
    var b = a.toBigEndianBytes();

    // output `[1]` when a is type `UInt256`, `UInt128`, and `Int128` 
    // but I think most developers want get `[0, 0, 0, 0, ... , 0, 1]`, the length of which is 32 for `UInt256` and 16 for `UInt128` and `Int128`
    return b;
}

```

When we call `toBigEndianBytes` for other types, for example, for `UInt64` we will get `[0, 0, 0, 0, 0, 0, 0, 1]`.

### Suggested Solution

Temporarily, I solved this problem manually as follows:
```cadence

// UInt128, Int128, and UInt256 need to be specially processed!
    //128
    pub fun to_be_bytes_u128(number: UInt128): [UInt8] {
        var output = number.toBigEndianBytes();
        while output.length < 16 {
            output = [UInt8(0)].concat(output);
        }

        return output;
    }

    pub fun to_be_bytes_i128(number: Int128): [UInt8] {
        var output = number.toBigEndianBytes();
        while output.length < 16 {
            output = [UInt8(0)].concat(output);
        }

        return output;
    }

    // 256
    pub fun to_be_bytes_u256(number: UInt256): [UInt8] {
        var output = number.toBigEndianBytes();
        while output.length < 32 {
            output = [UInt8(0)].concat(output);
        }

        return output;
    }

```

Are there any better or more efficient solutions?
Why the underlying implementation of `cadence` does not support this?

**Comment by turbolent** [comment]
@xiyu1984 Good catch, thank you for reporting this! We'll look into this and fix the incorrect behaviour

**Comment by turbolent** [comment]
@dreamsmasher This could be a good next issue if you are interested

**Comment by turbolent** [comment]
Given that this will change semantics, it is going to be a breaking change, so should be labeled as `Breaking Change` and target the `feature/stable-cadence` branch
