### ISSUE TITLE
Parsing String into UFix64 or any other numberable type

### ISSUE THREAD

**Issue by zhvarikk** [onflow/cadence#1918]

**Comment by turbolent** [comment]
What is the use-case for this? When would this be useful on-chain?

**Comment by dreamsmasher** [comment]
I guess for marshalling data from external sources? We could definitely add static methods on numeric types like

`UFix64.fromString(_ input: String): UFix64?`

Although treating smart contracts like untyped REST API's has a bit of a code smell.

**Comment by bluesign** [comment]
I think those can be cheaply implemented in Cadence code. ( on chain )

**Comment by bluesign** [comment]
@npahucki https://flowscan.org/contract/A.097bafa4e0b48eef.CharityNFT/overview LIne 112

**Comment by turbolent** [comment]
Number parsing functions could be easily added to Cadence. We have parsing functions in various places, that "just" need to be exposed to Cadence. For example, for fixed-point numbers we have parsing functions in `fixedpoint`, `ParseUFix64` and `ParseFix64`.
