### ISSUE TITLE
Keywords can be used as identifiers in certain situations

### ISSUE THREAD

**Issue by dsainati1** [onflow/cadence#1929]
### Problem

Keywords like `destroy`, `for`, `while` or `transaction` can be used as identifiers for composite, function and variable declarations. This is unnecessarily confusing, and should not be allowed. 

### Steps to Reproduce

Try the following code in the Playground or the emulator:

```cadence
resource destroy {
   fun transaction() {}
}
let f <- create destroy()
f.transaction()
destroy f
```

Note that this parses and typechecks, but it probably should fail parsing. 

### Suggested Solution

We should add a list of keywords that are not allowed to be identifiers, and when parsing an identifier to be used as the name of a composite, variable or function, we should reject these keywords in the parser.

**Comment by dreamsmasher** [comment]
Given that it's a breaking change, should we target `stable-cadence` then?
