### ISSUE TITLE
Add key iteration function to dictionaries

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#1938]
### Issue To Be Solved

Dictionaries currently have a `let keys: [K]` field (where `K` is the type of the keys), which returns all keys of the dictionary.

Dictionaries may stores a lot of elements, so the resulting keys array might be very expensive to produce.

### Suggested Solution

Similar to the new [storage iteration functions](https://github.com/onflow/cadence/pull/1851), add a new function to `Dictionary` which allows iterating over keys of the dictionary:

```cadence 
fun forEachKey(_ f: ((K): Bool))
```

The `Bool` return value of the iteration function `f` determines whether iteration continues; `true` will proceed to the next key, while `false` will terminate iteration. The specific order in which the objects are iterated over is undefined, as is the behavior when a key is added or removed from the dictionary.

**Comment by turbolent** [comment]
@dreamsmasher ah, right, the parameter should be a function! Fixed the signature in the description

**Comment by dreamsmasher** [comment]
Maybe we should open a FLIP to change the syntax for function types to something more clear, like `T -> U`

**Comment by bluesign** [comment]
for N keys: 

`let keys: [K]`  vs calling N times `fun forEachKey(_ f: ((K): Bool))` what is the difference here? Obviously there is something but I am missing.

**Comment by turbolent** [comment]
> for N keys:
> 
> `let keys: [K]` vs calling N times `fun forEachKey(_ f: ((K): Bool))` what is the difference here? Obviously there is something but I am missing.

No, a user would not call `forEachKey` N times, they would call it once, and `forEachKey` in turn calls the given function `f` up to N times, for eahc key of the dictionary.

The documentation should maybe describe this and provide an example to avoid misunderstandings.

**Comment by bluesign** [comment]
> No, a user would not call forEachKey N times, they would call it once, and forEachKey in turn calls the given function f up to N times, for eahc key of the dictionary.

@turbolent: yeah I meant `((K): Bool)` calling N times here, what will be the difference here ? in computation cost? or memory cost etc? If it was dictionary, I would understand the as N get bigger cost is increasing but why with the array ?

**Comment by dreamsmasher** [comment]
> > No, a user would not call forEachKey N times, they would call it once, and forEachKey in turn calls the given function f up to N times, for eahc key of the dictionary.
> 
> 
> 
> @turbolent: yeah I meant `((K): Bool)` calling N times here, what will be the difference here ? in computation cost? or memory cost etc? If it was dictionary, I would understand the as N get bigger cost is increasing but why with the array ?
> 
> 

The difference is direct iteration vs creating an intermediate array then iterating over that. This reduces the amount of requests to the storage layer if you exit early.

**Comment by bluesign** [comment]
> This reduces the amount of requests to the storage layer if you exit early.

Yeah this: "if you are lucky", is not a so good idea in my opinion. Isn't it better to fail always vs fail rarely ?

**Comment by turbolent** [comment]
You could imagine a caller chunking the keys into smaller parts and returning them individually, vs returning all keys at once, which might be prohibitively expensive.

**Comment by turbolent** [comment]
@bluesign 
> "if you are lucky", is not a so good idea in my opinion. Isn't it better to fail always vs fail rarely ?

What do you mean by this? I don't quite follow.

**Comment by bluesign** [comment]
if we have "keys" that will cause computation limit to exceed, then also if sum of all key iteration will be same computation cost, if I am searching for a key, it will fail in some cases and succeed in others ( depending on random key ordering )

**Comment by bluesign** [comment]
> For example, to skip the first few keys, then collect some, and finally ignore the rest:

This is super bad example though, considering ordering of the keys is random
