### ISSUE TITLE
Inconsistent behaviour of assert satement

### ISSUE THREAD

**Issue by psiemens** [onflow/cadence#194]
### Problem

The `assert` statement is behaving in a strange way in `v0.5.0-beta1`.

This script will panic due to the failed assertion:

```
pub fun main(): Int {
  assert(1 == 2)
  return 42
}
```

However, this script will return successfully with a value of 42:

```
pub fun main(): Int {
  assert 1 == 2
  return 42
}
```

Could this be a parser bug?

**Comment by turbolent** [comment]
Thanks for the report!

Yes, it looks like the second program is valid because the first line is probably parsed as multiple expression statements:

```
pub fun main(): Int {
  assert
  1 == 2
  return 42
}
```
