### ISSUE TITLE
memory metering for codec

### ISSUE THREAD

**Issue by robert-e-davidson3** [onflow/cadence#1940]
I included metering for newly allocated Cadence values and types on decoding but there may be gaps. My biggest concern is that there may be unbounded values that are metered _after_ allocation.

We may also want to meter the encoded bytes. Reasons not to include:
1. It's smaller than the already-metered cadence Values and Types it represents.
2. There's a fair amount of overhead in metering.
That being said, there's an advantage: the default io.Writer the Encoder uses is a wrapper that keeps track of the number of encoded bytes, making it fairly easy to add metering every e.g. 1000 bytes.

**Comment by j1010001** [comment]
Closing in favor of redesigned solution captured in: https://github.com/onflow/cadence/issues/2157
