### ISSUE TITLE
dynamic support for multiple codecs

### ISSUE THREAD

**Issue by robert-e-davidson3** [onflow/cadence#1941]
A wrapper codec is needed that chooses which codec to use for decoding by examining the first byte.

If the first byte is '{' then assume it's JSON. This isn't entirely correct because JSON doesn't always start with '{' but _our_ JSON does so this works.

Otherwise, use the first byte for version and capability info for the codec.
Version info is like "v1, v2, ..." while the capability info, if we use it, is like "[uses out-of-band type encoding](https://github.com/onflow/cadence/issues/1714)".

**Comment by j1010001** [comment]
Closing in favor of redesigned solution captured in: https://github.com/onflow/cadence/issues/2157
