### ISSUE TITLE
Encode events

### ISSUE THREAD

**Issue by robert-e-davidson3** [onflow/cadence#1952]
Right now in Cadence we encode events as JSON. We want to encode them with the new codec, CBF (Cadence Binary Format).

The FVM treats events as a black box so swapping out the codec should not require any changes to the flow-go repo.

It's outside of the scope of this ticket but we also want to convert the CBF-encoded events into JSON before returning them to the clients. This can be done in the Access Node, which _will_ impact the flow-go repo.

**Comment by j1010001** [comment]
Closing in favor of redesigned solution captured in: https://github.com/onflow/cadence/issues/2157
