### ISSUE TITLE
Interface Implementation Requirements

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#1956]
### Description

An earlier version of the language reference specified an unimplemented feature: Interface implementation requirements:

> Interfaces can require implementing types to also implement other interfaces of the same kind.
> Interface implementation requirements can be declared by following the interface name with a colon (`:`)
> and one or more names of interfaces of the same kind, separated by commas.
> 
> ```cadence
> // Declare a structure interface named `Shape`.
> //
> pub struct interface Shape {}
> 
> // Declare a structure interface named `Polygon`.
> // Require implementing types to also implement the structure interface `Shape`.
> //
> pub struct interface Polygon: Shape {}
> 
> // Declare a structure named `Hexagon` that implements the `Polygon` interface.
> // This also is required to implement the `Shape` interface,
> // because the `Polygon` interface requires it.
> //
> pub struct Hexagon: Polygon, Shape {}
> ```
> 

This feature is needed for the new FT / NFT standards.

**Comment by turbolent** [comment]
cc @joshuahannan @dsainati1

**Comment by joshuahannan** [comment]
Thank you! I'm excited to have this feature! :)

**Comment by SupunS** [comment]
Added with https://github.com/onflow/cadence/pull/2112

**Comment by turbolent** [comment]
FLIP: https://github.com/onflow/flips/pull/40
