### ISSUE TITLE
Add value encoding to the standard library

### ISSUE THREAD

**Issue by psiemens** [onflow/cadence#197]
### Issue To Be Solved

With the introduction of the `Crypto` built-in package, there is now a use case for converting arbitrary Cadence values into a serialized byte array, which can then be hashed and verified against a signature.

This encoding format should be secure and well-defined, allowing users to encode values in an external environment (i.e. Go, JavaScript) and expect Cadence to produce the same results.

This encoding format may only need to support Cadence value types (i.e. no resources).

### Possible Solution A

Expose an `Encoding.RLP` package as part of the Cadence standard library.

* Simple API (i.e. `RLP.Encode(value: AnyStruct)`)

### Possible Solution B

Add a `toBytes` method to value types that produces a consistent byte-wise encoding.

- E.g. `let myIntBytes = myInt.toBigEndianBytes()`

**Comment by turbolent** [comment]
I think both options are OK. I think option A is more complete, but will take a while to design and implement, whereas option B is quicker to get implemented but only covers a subset of the bigger problem.

### Option A

We'd need to define and implement encoding for all value types. We probably also want to statically check if the given value is encodable.

If we choose something low-level like RLP, we would need to somehow define lowering from high-level types to low-level RLP types. 

I'd not want to expose the internal CBOR based encoding used for storage, as I think it's still a bit of a implementation detail and changes there would mean breaking contracts / interactions with contracts.

I think if we choose this option we might as well consider implementing this as a format for `cadence.Value`s, for which we currently only have the verbose JSON encoding. 
Maybe CBOR could be nice here, and we could reuse much of what we already have from the internal CBOR encoding.

I think implementing a full encoding solution (no decoding yet) will likely take a sprint.

### Option B

I think this might be just enough for covering the requirements of on-chain signature verification and would require less effort.

**Comment by psiemens** [comment]
> I think this might be just enough for covering the requirements of on-chain signature verification and would require less effort.

I agree that this unblocks the current use case. Perhaps we could implement `toBytes()` methods for the value types we currently need and then take more time to design a complete version?

**Comment by turbolent** [comment]
For now I'll start by adding `fun Address.toBytes(): [UInt8]` and `fun Number.toBigEndianBytes(): [UInt8]`. We can extend this in the future and we'll need this functionality even for a more full-featured encoding system (e.g. RLP)
