### ISSUE TITLE
CBF: Length encoding should include nil and be variable-size

### ISSUE THREAD

**Issue by robert-e-davidson3** [onflow/cadence#2006]
In CBF, length (of strings, arrays, etc) is encoded as four bytes. Separately, anything that can be nil encodes an extra byte a a boolean for whether or not it's nil.

Instead, encode length like this:
1. If the data structure is nil then encode its length as `0xFF`.
2. If it is shorter than `0xFE` then encode its length normally in a single byte.
3. If it is longer than `0xFD` then encode its first byte as `0xFE`.
4. Repeat #3 for as many subsequent bytes as necessary but instead use `0xFF` for "also read next byte as length" instead of `0xFE` because nil need only be indicated in the first byte.

**Comment by j1010001** [comment]
Closing in favor of redesigned solution captured in: https://github.com/onflow/cadence/issues/2157
