### ISSUE TITLE
Broken image link in tutorial doc.

### ISSUE THREAD

**Issue by 10thfloor** [onflow/cadence#2032]
## Issue 
There is a broken image link on the Marketplace Compose screen that needs to be resolved. 

## Steps to reproduce 
- visit this link - https://developers.flow.com/cadence/tutorial/08-marketplace-compose
- scroll part way down the page
- notice under Marketplace Setup, there is a broken image link

**Comment by dreamsmasher** [comment]
uh oh, might be an issue with our google cloud storage account. here's the link in question: https://storage.googleapis.com/flow-resources/documentation-assets/cadence-tuts/account-nft-storage.png

**Comment by dreamsmasher** [comment]
seems like the other hosted image links are working, was the file accidentally moved or deleted? I don't think I have access to our cloud storage.
