### ISSUE TITLE
Extend exportable types

### ISSUE THREAD

**Issue by bluesign** [onflow/cadence#2049]
### Issue To Be Solved

Not sure if I called it correct, but functions/references etc cannot be exported causing some problems. 

For example NFTView, FTView on metadata, has function field, which causes script errors. 

Also I am developing some Jupyter/debugger integration for mainnet/testnet [0], it would be nice if everything can be exported, preferably can be important also in script environment. 

[0] https://www.loom.com/share/afed3b09cbd449dbb150d075de8d2087

**Comment by turbolent** [comment]
Do you maybe have a concrete example of something you would like to be able to do and what is preventing you from achieving it?

**Comment by bluesign** [comment]
@turbolent, for example NFTView has CollectionData which has a function typed field. 

https://github.com/onflow/flow-nft/blob/9877dccbd884e06bbd754a4f693b7169dd6dd62b/contracts/MetadataViews.cdc#L514

Also references and some more types are not exportable, would be nice to make them exportable ( even some of them would be not much sense )
