### ISSUE TITLE
Cleanup: docs - tutorial 06

### ISSUE THREAD

**Issue by AmarildoGrembi** [onflow/cadence#2070]
### Issue To Be Solved

For a beginner it's important that docs are up to date in order to not complicate the learning process or cause confusion. I found some parts on the [06 tutorial](https://github.com/onflow/cadence/blob/master/docs/tutorial/06-fungible-tokens.mdx) to be outdated or not relevant anymore while going through it.

### Suggested Solution

Cleanup or re-write outdated parts.

**Comment by turbolent** [comment]
@AmarildoGrembi Can you please elaborate on what parts specifically are outdated or irrelevant?
