### ISSUE TITLE
Allow composites to inherit events from interfaces

### ISSUE THREAD

**Issue by dsainati1** [onflow/cadence#2081]
This is an alternative to the proposed change in https://github.com/onflow/cadence/issues/2069, that solves the same issue outline in https://github.com/onflow/cadence/issues/1283.

This would allow composites to inherit events directly from interfaces, rather than requiring them to redeclare these events identically to the interface's definition in the body of the composite. E.g. this:

```cadence
pub struct interface I {
     pub event Foo(x: string)
}
pub struct S: I {}

emit S.Foo(x: "data")
```

would be valid, as `S` has inherited the definition of `Foo` from `I`. Note also that here the events are declared/inherited by a struct rather than a contract, as in order to support a proposed change in the new NFT standard (where events are defined in the `Vault` resource rather than the contract), we would also permit arbitrary composites to define events.

**Comment by bluesign** [comment]
I think this is very nice:

```cadence
pub struct interface I {
    pub event Foo(x: string)
    pub fun deniz(){
      post{
        emit I.Foo("data") 
     } 
   }
}

pub struct S: I {}
``` 
If this can emit an event as S, it can be good. 


My only concern is this `inherit` proposal converts events from `types` to `functions.` ( with interface default functions etc.)  If we assume event as function, everything makes sense. 

- event becomes kind of a function 
` pub event Foo(x: string)` ->  `pub fun Foo(x: string): #Foo` ( # being event decorator, like @ for resources ) 
so `emit Foo(x:"data")` becomes `emit #Foo(d:data)`

**Comment by j1010001** [comment]
this is an alternative to https://github.com/onflow/cadence/issues/2069

**Comment by turbolent** [comment]
This might get proposed as part of https://github.com/onflow/flips/pull/111 or separately, it was started to get proposed before in https://github.com/onflow/flips/pull/82

**Comment by dsainati1** [comment]
With https://github.com/onflow/cadence/pull/2589 this is now no longer necessary.
