### ISSUE TITLE
Update Downstream deps for stable-cadence branch

### ISSUE THREAD

**Issue by j1010001** [onflow/cadence#2084]
### Issue To Be Solved

We would like to have a CLI build with the Stable Cadence changes.

### Suggested Solution

Create `feature/stable-cadence branches` in downstream dependencies:
- [x] `flow-go`
- [x] `flow-go-sdk`
- [x] `flow-emulator`
- [x] `flow-nft`
- [x] `nft-storefront`

**Comment by turbolent** [comment]
Currently the update of flow-go is blocked by an update of the Flow core contracts to Stable Cadence, tracked in #1820

**Comment by turbolent** [comment]
Core contracts are updated: https://github.com/onflow/flow-core-contracts/pull/319

Updated flow-go to the updated core contracts and updated the tests in: https://github.com/onflow/flow-go/pull/3498

**Comment by turbolent** [comment]
Next blocker is the NFT standard contract. It uses `view` as an identifier, but `view` was made a keyword.
@dreamsmasher will work on making `view` a soft-keyword to avoid making this a breaking change for existing contracts. Challenge is still allowing `view` function expressions (`view fun() {...}`)

**Comment by turbolent** [comment]
@sideninja The dependencies up to and including the Emulator are now updated:

- https://github.com/onflow/cadence/tree/v0.29.0-stable-cadence-3
- https://github.com/onflow/flow-go-sdk/tree/feature/stable-cadence
- https://github.com/onflow/flow-go/tree/feature/stable-cadence
- https://github.com/onflow/flow-emulator/tree/feature/stable-cadence

**Comment by sideninja** [comment]
> @sideninja The dependencies up to and including the Emulator are now updated:
> 
> * https://github.com/onflow/cadence/tree/v0.29.0-stable-cadence-3
> * https://github.com/onflow/flow-go-sdk/tree/feature/stable-cadence
> * https://github.com/onflow/flow-go/tree/feature/stable-cadence
> * https://github.com/onflow/flow-emulator/tree/feature/stable-cadence

Nice. Should we tag them and do a release with the secure cadence tag?

**Comment by turbolent** [comment]
Yes, good point. I'll tag them

**Comment by turbolent** [comment]
Tagged, updated the comment above

**Comment by sideninja** [comment]
Thank you. Should I release a CLI with these versions? By when should a release be ready?

**Comment by turbolent** [comment]
Yes, that would be great, thanks! We also need to update the Cadence tools (e.g. test framework, language server). I can take care of this too if you want. 

As for timing, there's no rush, we just like to get a preview release out as soon as it's ready, so that developers can start updating their contracts early and give feedback on the changes.

**Comment by turbolent** [comment]
@sideninja Everything is now updated to preview 4 in https://github.com/onflow/flow-cli/compare/master...release/stable-cadence

**Comment by turbolent** [comment]
Greg successfully built a CLI binary with preview 4.

I tested it and found issues relating to `view` functions. #2141 fixes the issues and is merged now.

I'll tag preview 5 and do another round of updates, which will luckily from now on just be version bumps.




 https://github.com/onflow/cadence/pull/

**Comment by turbolent** [comment]
Tagged and updated everything to preview 5: https://github.com/onflow/flow-cli/compare/master...release/stable-cadence. Ping Gregor to build and publish another CLI release of that branch

**Comment by turbolent** [comment]
CLI preview release tagged: https://github.com/onflow/flow-cli/releases/tag/v0.41.3-stable-cadence-5

Going to wait for feedback. If deemed OK, will announce as first preview release for Stable Cadence and close issue.
