### ISSUE TITLE
Change syntax for function types

### ISSUE THREAD

**Issue by dreamsmasher** [onflow/cadence#2094]
### Issue To Be Solved

Currently, function types are printed with confusing syntax. For instance, the type of the function

```cadence
fun foo(n: Int, s: String): Bool
```

is rendered as

```cadence
foo: ((Int, String): Bool)
```

This inconsistency is more apparent when writing higher-order functions:

```cadence
fun forEach(xs: [Int], f: ((Int): Bool)): Void
```

which harms readability.

### Suggested Solution

Function types should use the `fun` keyword so their types are closer to the way they're defined. For the examples above, their types should be rendered as

```cadence
foo: fun(Int, String): Bool
forEach: fun([Int], fun(Int): Bool): Void
```

To avoid breaking existing contracts, this could be implemented as a non-breaking change by allowing the old syntax but updating the parser to also accept the `fun` keyword as a prefix. The stringification of function types should be changed to include the `fun` keyword. 

[See FLIP](https://github.com/onflow/flips/pull/43)

**Comment by turbolent** [comment]
- FLIP likely to get accepted
- Can start on implementation
