### ISSUE TITLE
Add `fromString` conversion function to `Address` type

### ISSUE THREAD

**Issue by veganbeef** [onflow/cadence#2154]
### Issue To Be Solved

Cadence now supports conversion of strings to all number types with [the latest mainnet spork](https://forum.onflow.org/t/cadence-updates-for-the-nov-2022-mainnet-spork/3748) using the built-in `fromString` method. 

It would be nice to have the same capability for creating addresses from strings.

This would allow for more flexibility in passing and manipulating variables, such as using `{String: String}` dictionaries to pass numbers and addresses as transaction inputs without having to use [conditional downcasting operators](https://developers.flow.com/cadence/language/operators#conditional-downcasting-operator-as) and related boilerplate code.

This would also allow users to query `PublicAccount` objects from strings, allowing for one to, for example, query a value stored on an account based on the address embedded in a run-time type identifier string.

### Suggested Solution

 An example of usage might look like:
```cadence
let input: String = "0xf8d6e0586b0a20c7"
let convertedAddress: Address? = Address.fromString(input) // returns a valid address

let badInput: String = "42"
let badConvertedAddress: Address? = Address.fromString(badInput) // returns nil
```

Given that this operation is quite similar to the `UInt64.fromString()` method (after all, addresses are [just unsigned 64-bit integers](https://developers.flow.com/cadence/language/values-and-types#addresses)), the implementation should be fairly straight-forward.

**Comment by dreamsmasher** [comment]
hmm, would you mind sharing a motivating use-case? we currently allow addresses to be directly passed into scripts and transactions/stored in data structures.

**Comment by darkdrag00nv2** [comment]
@turbolent Will take this one up as well. Should be similar to `Address.fromBytes`

**Comment by bluesign** [comment]
@darkdrag00nv2 I think anything that provides `fromBytes` can also provide `fromString`, @turbolent knows better but maybe a generic solution here can be pretty nice.

**Comment by turbolent** [comment]
@bluesign agreed, it would be nice to have `fromString` function for all `Number` types, and further conversion functions for other representations.
