### ISSUE TITLE
Add static type for Cadence external `PathLink` value

### ISSUE THREAD

**Issue by fxamacker** [onflow/cadence#2167]
### Issue To Be Solved

`cadence.PathLink` doesn't have a static type.  It is needed because:
- [CCF specs (draft)](https://github.com/fxamacker/ccf_draft) needs to include `cadence.PathLink` static type.
- CCF codec (WIP) needs all Cadence external values to have a static type.

Updates #2157 

### Suggested Solution

Maybe add `PathLinkType` and return `PathLinkType` from `PathLink.Type()`.

EDIT: Renamed `Link` to its new name `PathLink`.

**Comment by turbolent** [comment]
I might have commented on this somewhere before, but I don't think that this is actually needed:
After some digging, support for exporting links was implemented very early on and is/was likely only needed for the Playground. I can't think of a way when a link would be exported, as links are stored internally, but are not first-class values that could be imported or exported by a user.

**Comment by SupunS** [comment]
I initially had the same thought, but would this be needed in the future? e.g: would the CCF be used for encoding cadence internal data (e.g: elaboration serialization, etc.)?

**Comment by SupunS** [comment]
Reopening the issue, since the removal of `PathLink` value was reverted: https://github.com/onflow/cadence/pull/2381.

This would still be a problem for CCF.

**Comment by turbolent** [comment]
I followed up with the DX team: The Emulator provides the functionality to export values from account storage, and the Playground API in turn encodes the values further to JSON-CDC.

That means that we'll want to keep the export functionality (`interpreter.Value` to `cadence.Value`), and the JSON-CDC encoding, but can remove import related code.

In addition, we should add support for account link values.

For CCF, we can just ignore links.

I'll open a PR for that
