### ISSUE TITLE
PrimitiveStaticTypeCapability is redundant with CapabilityStaticType

### ISSUE THREAD

**Issue by fxamacker** [onflow/cadence#2175]
### Issue To Be Solved

`PrimitiveStaticTypeCapability` is redundant with `CapabilityStaticType`.

`sema.CapabilityType` is converted to `interpreter.CapabilityStaticType` in `ConvertSemaToStaticType`.

### Suggested Solution

Remove `PrimitiveStaticTypeCapability` in the file runtime/interpreter/primitivestatictype.go.

**Comment by j1010001** [comment]
large effort required and would require migration for some tech debt reduction

**Comment by j1010001** [comment]
Copying from the linked PR: "There might be existing stored data that might use this, so before we remove it, we need to make sure it isn't a breaking change."
