### ISSUE TITLE
Iterating over attachments

### ISSUE THREAD

**Issue by dsainati1** [onflow/cadence#2193]
In the FLIP for attachments (https://github.com/onflow/flips/blob/main/cadence/2022-09-21-attachments.md), it was originally proposed that Cadence have a way to iterate over attachments, in order to support the use case wherein the developer of a resource wants to include metadata that may or may not exist on attachments on their resource, when outputting that resource's metadata. 

This was originally included in the above FLIP and implementation, but we discovered some security concerns with the proposal, and as such the iteration API (and associated reflection features) were removed from the core proposal, which has since been approved and merged. 

We should figure out a safe and secure way to support attachment iteration, potentially starting with the proposed solution in the Related Issues section of the linked FLIP.

**Comment by sisyphusSmiling** [comment]
Checking in to see if this is being prioritized as a feature for mainnet release of native Attachments. Any word?

**Comment by dsainati1** [comment]
This is likely not going to be in the initial release of attachments on Mainnet; as mentioned above there were some big security concerns about the iteration API. We are working on a new and improved design for this feature, but there are some proposed language changes that might influence the final design, so we need to work out the design for those before we can pick this back up.

**Comment by j1010001** [comment]
blocked by https://github.com/onflow/flips/pull/54

**Comment by dsainati1** [comment]
This is implemented now in Stable Cadence
