### ISSUE TITLE
Skip broken values during storage iteration

### ISSUE THREAD

**Issue by SupunS** [onflow/cadence#2200]
### Issue To Be Solved

As described in https://github.com/onflow/cadence/issues/2170, some storage values could be broken/fail to load, due to outdated contracts. This becomes problematic in cases like storage iteration etc.

### Suggested Solution

Improve the storage iteration API to skip broken values

**Comment by turbolent** [comment]
@SupunS Do we have a reproducer? 

Let's look into what the error chain looks like and then
- See if is correct and maybe needs adjustments (maybe on Cadence side, maybe on FVM side)
- If the chain is correct / as we want it, maybe consider if we need `error.Is/As`
