### ISSUE TITLE
Code marked as unreachable when it is not

### ISSUE THREAD

**Issue by bjartek** [onflow/cadence#2210]
Trying to deploy finds `dandy` contract to a new emulator (the one in flowkit 0.43.0, via overflow testing) gives me an unreachable error here https://github.com/findonflow/find/blob/main/contracts/Dandy.cdc#L186

In the commit https://github.com/findonflow/find/commit/06d4620d0450ceb1be2cfc1b838f59436ad8dc84 i move around returning NFTCollectionData from resolve view to the bottom of the block. Then it works. As you can see this error also affects flovatar. 

My hunch here is that there is something wrong the infering that returning an anonymous function will trigger proceeeding lines to be unreachable?

**Comment by turbolent** [comment]
Thank you very much for reporting this @bjartek! This was indeed a regression introduced in v0.30
