### ISSUE TITLE
Attachments documentation

### ISSUE THREAD

**Issue by alilloig** [onflow/cadence#2212]
### Issue To Be Solved

We need to include the new attachments FLIP on the dev portal docs

### Suggested Solution

Create a new section in the language docs, explaining and giving examples on how to use it https://github.com/onflow/flips/blob/main/cadence/2022-09-21-attachments.md

**Comment by alilloig** [comment]
@turbolent maybe y'all are already tracking this, we are about to write the first feature using attachments so we though it could be a good timing to include it to the docs

**Comment by dsainati1** [comment]
https://github.com/onflow/cadence/pull/2137 already adds documentation for attachments to the attachments feature branch; when this feature branch is merged to `master` this documentation should be added to the website.

**Comment by dsainati1** [comment]
Other than this, I believe we had been discussing updating the Cadence tutorials to include a new tutorial on attachments in this issue: https://github.com/onflow/flow-playground-tutorials/issues/16

**Comment by turbolent** [comment]
@alilloig Like Daniel pointed out, there are docs, they are not merged yet, because the feature hasn't been merged yet. If you need the docs, they're here:
https://github.com/onflow/cadence/blob/feature/attachments/docs/language/attachments.md

**Comment by alilloig** [comment]
Thank you so much guys! Yeah having the docs will be great, we were looking at the flip.
