### ISSUE TITLE
Cannot update invalid contract

### ISSUE THREAD

**Issue by SupunS** [onflow/cadence#2217]
### Problem
The Cadence version prior to `v0.30.0` had a bug where invalid identifiers were not reported by the parser.
e.g: 
```cadence
pub contract Foo {
    pub event foo() someInvalidIdentifier    // <-- invalid identifier: Wasn't an error previously 
    pub event bar()
```

This was fixed in `v0.30.0` (https://github.com/onflow/cadence/pull/2134). But with this fix, it makes it not possible to update the invalid contract to fix it, because the contract update validation tries to parse the old code and fails.

### Potential solutions:

Two options:
- Revert the fix entirely: Won't be a breaking change. However, newly deployed contracts would be prone to the bug.
- Revert the fix only for the contract updates: Any invalid code can be updated, but cannot be used without updating. Any new code would not be prone to the bug.

**Comment by turbolent** [comment]
Going to revert this breaking change on `master` and move it to the Stable Cadence feature branch instead.
