### ISSUE TITLE
Automated regression testing for contracts on Testnet and Mainnet

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#2228]
### Issue To Be Solved

We should have automated regression testing for code on Testnet and Mainnet.

### Suggested Solution

Use the [batch tool / contract downloader](https://github.com/onflow/cadence/tree/master/tools/batch-script/cmd/get_contracts) and the [Cadence linter](https://github.com/onflow/cadence-tools/tree/master/lint) to automatically / periodically perform a regression test for a new Cadence version.

The Cadence linter already has a mode to only parse and check, and not run any linting rules.

We could implement this as a Go tool that runs using GitHub actions, thus could be triggered manually before a spork, and automated to run periodically (e.g. every day).

- Fetch all contracts using the batch script tool which has a command to fetch all contracts
- Run linter with current Cadence version of network
- Update version in linter
- Run linter with new Cadence version
- Compare

We also have the existing / old [Source Compatibility Suite](https://github.com/onflow/cadence/tree/master/compat) which we could extend / repurpose.

**Comment by SupunS** [comment]
Added with #2237
