### ISSUE TITLE
Add computed field/method on `Contract`s to view all declarations 

### ISSUE THREAD

**Issue by dreamsmasher** [onflow/cadence#2232]
### Issue To Be Solved

Part of #2201.

As part of the NFT V2 spec, we need a way to view all declarations within a given contract.
### Suggested Solution

This could consist of a single computed field or getter on the `Contract` type that returns an array of `Type`s: 

```cadence
pub fun Contract.publicDeclarations(): [Type]
```

for further granularity, we could introduce separate getters for each kind of declaration: function, struct, resource, interface, etc.

**Comment by bluesign** [comment]
Why this is on DeployedContract? Wouldn’t it better to have it on MetaType?

**Comment by turbolent** [comment]
`DeployedContract` is pretty much the meta type of a contract. It will be useful there, and I agree it would also be nice to not only have this for contracts and generalize this to any kind by adding the functionality to `Type` (`sema.MetaType`)
