### ISSUE TITLE
Some broken values are not skipped during storage iteration

### ISSUE THREAD

**Issue by LanfordCai** [onflow/cadence#2251]
### Current Behavior

According to https://github.com/onflow/cadence/pull/2202, the broken values should now be skipped during storage iteration, but it seems there are still some are not skipped.

### Expected Behavior

All broken values are skipped during storage iteration

### Steps To Reproduce

Script:
```cadence
  pub fun main(address: Address): Type? {
    let account = getAuthAccount(address)
    var t: Type? = nil
    account.forEachStored(fun (path: StoragePath, type: Type): Bool {
        if path == /storage/MusicBlockCollection {
            t = type
            return false
        }

        return true
    })
    return t
  }
```

Command: 
`flow scripts execute ./scripts/get_paths.cdc 0x196c1869b10635b1 --network=mainnet`

Error:
```
error: mismatched types
   --> 5634aefcb76e7d8c.MusicBlock:133:23
    |
133 |             let ref = &self.ownedNFTs[id] as auth &NonFungibleToken.NFT
    |                        ^^^^^^^^^^^^^^^^^^ expected `NonFungibleToken.NFT`, got `NonFungibleToken.NFT?`

error: mismatched types
   --> 5634aefcb76e7d8c.MusicBlock:147:20
    |
147 |             return &self.ownedNFTs[id] as &NonFungibleToken.NFT
    |                     ^^^^^^^^^^^^^^^^^^ expected `NonFungibleToken.NFT`, got `NonFungibleToken.NFT?`
 
```

### Environment

```markdown
- Cadence version: v0.31.0
- Network: Mainnet
```

**Comment by bluesign** [comment]
isn't this coming on next spork ? is mainnet on v0.31.0 already?

**Comment by LanfordCai** [comment]
> isn't this coming on next spork ? is mainnet on v0.31.0 already?

I'm don't know whether 'skip broken value' is a unreleased feature or not. I just upgraded to the latest flow-cli and the Cadence version is v0.31.0. 

If 'skip broken value' is not released yet, then why I'm not sure the paths number get from storage iteration API and account.storagePaths are different(see #2250 )
