### ISSUE TITLE
Contracts with the same name in an account?

### ISSUE THREAD

**Issue by LanfordCai** [onflow/cadence#2252]
### Current Behavior

`account.contracts.names` may returns duplicate contract names

### Expected Behavior

`account.contracts.names` returns unique contract names

### Steps To Reproduce

script:
```cadence
  pub fun main(address: Address): [String] {
    let account = getAccount(address)
    return account.contracts.names
  }
```

command:
`flow scripts execute ./scripts/get_contracts.cdc 0xf233dcee88fe0abe --network=mainnet`

result:
`["FungibleToken", "FungibleToken", "FungibleTokenMetadataViews", "FungibleTokenSwitchboard"]`

There are two "FungibleToken"

### Environment

```markdown
- Cadence version: v0.31.0
- Network: Mainnet
```

**Comment by turbolent** [comment]
@LanfordCai Thanks for reporting this inconsistency!

**Comment by turbolent** [comment]
Notes:

Cadence gets the contract names of an account by calling into FVM through the `runtime.Interface.GetAccountContractNames` function. It seems like FVM returns duplicates. 

Pinged the Execution team for feedback (https://dapperlabs.slack.com/archives/C03C40ZV82C/p1673891470638519)
