### ISSUE TITLE
Links behaviour

### ISSUE THREAD

**Issue by bluesign** [onflow/cadence#2264]
### Issue to be solved

I think linking from capability path to path is a bit too much freedom. 

for example: 

```
acc.link(/public/a, /public/b) 
acc.link(/public/b, /public/a) 
```

causing too much trouble. It causes borrow and check to panic. 

### Suggested Solution

I suggest to disallow, if not at least cyclic link error to be panic free. In check it can return false, in borrow can be nil maybe.

**Comment by turbolent** [comment]
Currently there is restriction on link targets, so cycles can be created, but are rejected when dereferenced. 
We could reject cyclic links at link creation time, but that would be a breaking change.

The [capability controller FLIP](https://github.com/onflow/flow/pull/798) aims to replace links, so we should maybe wait for that.

**Comment by bluesign** [comment]
I think changing check and borrow behavior is the non-breaking solution here. 

A lot of discussion going on in contracts ( NFTstorefront etc) and what I see is people usually think ‘check’ is non-panic function. ( we can probably make it safely like that )

**Comment by j1010001** [comment]
small inconsistency - wait for outcome of Capability Controllers FLIP discussion to decide what to do here.

**Comment by bluesign** [comment]
Closing in favour of Capability Controllers.
