### ISSUE TITLE
Include Examples of Multi-interface Restricted Types

### ISSUE THREAD

**Issue by dete** [onflow/cadence#2267]
### Issue to be solved

The Cadence reference pages for [restricted types](https://developers.flow.com/cadence/language/restricted-types) and [capabilities](https://developers.flow.com/cadence/language/capability-based-access-control) use examples with a single interface as part of the restriction to make things clear. I think it would be useful to include a note that explicitly says that multiple interfaces are allowed, and shows a simple, extended example with multiple interfaces as part of a restricted type.

**Comment by turbolent** [comment]
Can close once https://github.com/onflow/flips/pull/85 is approved and implemented

**Comment by j1010001** [comment]
Add example for interface sets with multiple interfaces.

**Comment by dsainati1** [comment]
I believe the new documentation actually already has this: https://developers.flow.com/next/cadence/language/intersection-types
