### ISSUE TITLE
Improve external mutability

### ISSUE THREAD

**Issue by SupunS** [onflow/cadence#2273]
### Issue to be solved

A previous version of cadence (secure cadence release) restricted the potential foot-gun of mutating container-typed
`let` fields/variables via the
[Cadence mutability restrictions FLIP](https://github.com/onflow/flips/blob/main/flips/20211129-cadence-mutability-restrictions.md).

However, there are still ways to mutate such fields by:
- Directly mutating a nested composite typed field.
- Mutating a field by calling a mutating function on the field.
- Mutating the field via a reference.

### Suggested Solution

Explore potential improvements that can be done at the language level to eliminate/minimize the above-mentioned foot guns.

**Comment by j1010001** [comment]
our recommendation updated https://github.com/onflow/flips/pull/59 - bring up in LDM, decide if we need breakout of if it is ok to close.

**Comment by SupunS** [comment]
We have three FLIps (https://github.com/onflow/flips/pull/89, https://github.com/onflow/flips/pull/86, https://github.com/onflow/flips/pull/94) proposed for this, and three separate issues (#2534, #2535, #2536) tracking the implementation.

Therefore closing this issue.
