### ISSUE TITLE
Implement per-tx contracts cache in Cadence 

### ISSUE THREAD

**Issue by j1010001** [onflow/cadence#2301]
### Issue to be solved

Related to https://github.com/onflow/cadence/issues/1684 

The problem described in the above issue is amplified by implementation of Storage Iteration feature (https://github.com/onflow/cadence/issues/208), making the feature unusable on some accounts.

### Suggested Solution

Implement per transaction/script cache, so that Cadence one fetches a contract from FVM one time (the first time the contract is imported in the transaction)

**Comment by turbolent** [comment]
Just to clarify and avoid potential bugs, "cache" is a bit of a misnomer: The programs should be stored in memory during the execution of a transaction/script, and never be evicted during that time; programs must always be returned if they were returned before.

We can probably do this in the runtime, before we currently call into FVM via `GetAndSetProgram`.

**Comment by bjartek** [comment]
Nice clarrification on Cache use here. Is memoize a better word to use here?

**Comment by j1010001** [comment]
now that #1684 is done, do we still need this @janezpodhostnik ?

**Comment by janezpodhostnik** [comment]
no, 
we can lose this. This was an alternate solution.
