### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#237]
## Context

New features have been added to Cadence in the last few releases.
Update the documentation and describe the new features

## Definition of Done

- [x] Querying block information
  - Get the current block:
    `fun getCurrentBlock(): Block`

  - Get a block at a given height:
    `fun getBlock(at height: UInt64): Block?`

  - The block info is:

    ```
    struct Block {
        let id: [UInt8; 32]
        let height: UInt64
        let timestamp: UFix64
    }
    ```
  - [ ] Also update https://docs.onflow.org/docs/faq#how-do-i-access-block-information-like-timestamp-and-block-number-in-cadence
- [x] Crypto contract
- [x] Typed capabilities
- [x] Run-time Types
- [x] Addresses size (8 instead of 20 bytes)
- [x] Parameters for transactions and scripts
- [x] `fun toString(): String` was added for all number types and addresses
- [x] `fun toBytes(): [UInt8]` was added to `Address`
- [x] `fun toBigEndianBytes(): [UInt8]` was added to all number types.
- [x] Fields which have a non-storable type are now rejected:
  Non-storable types are:
    - Functions (e.g. `((Int): Bool)`)
    - Accounts (`AuthAccount` / `PublicAccount`)
    - Transactions
    - `Void`
- [x] `String.decodeHex(): [Int]` → `String.decodeHex(): [UInt8]`
- [x] `AuthAccount.addPublicKey(publicKey: [Int])` → `AuthAccount.addPublicKey(publicKey: [UInt8])`
- [x] `AuthAccount.setCode(code: [Int])` → `AuthAccount.setCode(code: [UInt8])`
- [x] Conformance check now allows subtype for return type
- [x] Type hierarchy
- [x] `unsafeRandom`
- [x] Account creation

**Comment by timmymmit** [comment]
Add section for Roadmap and Features that are upcoming
