### ISSUE TITLE
Fuzz test CCF Codec

### ISSUE THREAD

**Issue by fxamacker** [onflow/cadence#2377]
### Issue to be solved

The CCF codec (PR #2364) should be fuzz tested before deployment.

### Suggested Solution

Fuzz testing the CCF codec should ideally be done by Cadence team with expertise in Cadence types and values.

It would be unusual for a brand new codec for a brand new data format to not have issues detected by fuzzing.

**Comment by turbolent** [comment]
@SupunS We could do something similar as we do for the existing fuzzer, or even extend it. Let's sync on it

**Comment by bluesign** [comment]
is existing fuzzer public?

**Comment by turbolent** [comment]
@bluesign No, the fuzzer is not public.
