### ISSUE TITLE
Update CCF codec to support recently added types/values (e.g. AttachmentType)

### ISSUE THREAD

**Issue by fxamacker** [onflow/cadence#2379]
### Issue to be solved

New Cadence types and/or values were recently added, such as `AttachmentType`, `AnyStructAttachmentType`, `AnyResourceAttachementType`.

They need to be supported in CCF Specs and CCF Codec.

### Suggested Solution

NOTE: The PR for this depends on PR #2364 (CCF Codec) being approved and merged first.

First, update [CCF Specs](https://github.com/fxamacker/ccf_draft) to support new types (e.g.`AttachmentType`, `AnyStructAttachmentType`, `AnyResourceAttachementType`) and bump specs (e.g. from RC1->RC2).

Then update [CCF Codec](https://github.com/onflow/cadence/pull/2364) to match updated CCF Specs.

We're leaving room for possibility of [CCF fuzz testing](https://github.com/onflow/cadence/issues/2377) (and maybe integration tests) to uncover issues that require changes to CCF Specs and/or CCF Codec.

**Comment by j1010001** [comment]
blocker for event encoving

**Comment by dsainati1** [comment]
Heads up that the https://github.com/onflow/flips/pull/54 entitlements change is going to add some new data to references. In particular the `Authorized` field, which was previously a `Bool`, is now going to be one of `Unauthorized`, a set of entitlements, or a single name for an entitlement map.
