### ISSUE TITLE
Return overflowing value when multiplying for UInt256 and Int256 

### ISSUE THREAD

**Issue by quocle108** [onflow/cadence#2389]
### Issue to be solved

There are some cases in which we need to get the overflowing value instead of the maximum value when the overflow happens. For example this case [mulDiv(uint256 x, uint256 y, uint256 denominator)](https://github.com/PaulRBerg/prb-math/blob/main/src/Common.sol#L379).

In order to multiply a and b and get the result in 512 bits, we need to get the overflowing value when it happens.

**Comment by darkdrag00nv2** [comment]
@turbolent If I understand correctly, we want to implement `Word128` and `Word256`? 

The title of this issue is a little confusing. We wouldn't want to change the behavior of `UInt256` and `Int256` I presume. They should still raise runtime errors on overflow. Please correct me if I am wrong.

**Comment by darkdrag00nv2** [comment]
Thanks @turbolent 

I think we can implement `Word128` and `Word256` for starters. We can add more functions further if it is insufficient for @quocle108.

**Comment by turbolent** [comment]
@darkdrag00nv2 Sounds good!
