### ISSUE TITLE
Homebrew support

### ISSUE THREAD

**Issue by chenrui333** [onflow/cadence#240]
Just to let you know, there is a homebrew support PR going on.
https://github.com/Homebrew/homebrew-core/pull/57981

**Comment by turbolent** [comment]
Nice, looks like it has been merged! 🎉 

Note that this only Cadence's interpreter and REPL. In case you are looking for the Flow CLI, which also includes this and the Flow emulator, consider installing that instead https://docs.onflow.org/docs/cli.

We're planning to open-source it very soon, and hope to have Homebrew Formula for it as well 🙂

**Comment by chenrui333** [comment]
Thanks @turbolent!
