### ISSUE TITLE
Linking to capability

### ISSUE THREAD

**Issue by bluesign** [onflow/cadence#2431]
### Issue to be solved

This idea came out today when discussing hybrid custody (child account) , I wanted to run it with you if it is viable. 

Considering I have a capability to &FlowToken.Vault from another account. ( let's say 0x2 ) I am thinking it would be great if I have some kind of option to link to that capability, without writing a proxy contract. 

```cadence 
var cap : Capability<&FlowToken.Vault> = ...   [ Capability(account:0x2, borrowType: &FlowToken.Vault, path:/private/flowtokenvault ) ]
acc.save(cap, /storage/cap0x2 )
acc.link<&{FungibleToken.Receiver}>( /public/receiver, /storage/cap0x2)
```

was this considered before? I can see few edge cases ( bit those are also same for proxy objects )

**Comment by turbolent** [comment]
That's an interesting idea. 

Given the case that the plan is to replace the existing linking API with [Capability Controllers](https://github.com/onflow/flow/pull/798), we can maybe discuss this as a follow-up feature once the FLIP got approved (or not).
