### ISSUE TITLE
Support function-purity annotations in CCF

### ISSUE THREAD

**Issue by SupunS** [onflow/cadence#2457]
### Issue to be solved

Function type has a new field called "Purity" in Stable-cadence: https://github.com/onflow/cadence/blob/be303b7586d0353b60dbe8ae9d7b4117f282e0c6/types.go#L1708

Serializing/deserializing this new field was added to JSON encoding/decoding when function-purity was added. But now that we also have CCF, this also needs to be supported in the CCF encoder/decoder.

**Comment by j1010001** [comment]
blocking merging stable Cadence ot master

**Comment by fxamacker** [comment]
Updates epic #2157
