### ISSUE TITLE
Update checker/interpreter NFT tests to use actual NFT contracts

### ISSUE THREAD

**Issue by dsainati1** [onflow/cadence#2503]
### Issue to be solved

Changes to the checker and interpreter during the development of Stable Cadence have caused the unit tests using the NFT (and other core) contracts to fail, and as such the test contracts were updated locally. These updates are going to be out of sync with the actual core contracts, and once the core contracts are updated for Stable Cadence these tests should be updated to reflect the actual core contracts.

**Comment by turbolent** [comment]
Related: #2503

**Comment by j1010001** [comment]
Alternative to #3608

**Comment by SupunS** [comment]
Probably the source coded are updated in https://github.com/onflow/cadence/pull/3471. Might just need to double check and "enable" the disabled tests.

**Comment by turbolent** [comment]
Let's remove the tests once the Source Compatibility Suite is testing the contracts again, i.e. when #3608 is complete
