### ISSUE TITLE
static type and runtime type doesn't match for `codeHash` in flow events

### ISSUE THREAD

**Issue by fxamacker** [onflow/cadence#2527]
### Current Behavior

Currently, static type and runtime type doesn't match.

For example, `flow.AccountContractAdded`:

-  event type has `codeHash` field type `[UInt8; 32]` (static type).

- event value has `codeHash` field as `[UInt8]`  (runtime type).

### Expected Behavior

runtime type should match static type

### Steps To Reproduce

See source code.

### Environment

```markdown
- Cadence version: master
- Network:
```

**Comment by turbolent** [comment]
Good catch! The types should definitely match. We should probably use the static type and fix the value type
