### ISSUE TITLE
Cannot take a reference to a nested-optional

### ISSUE THREAD

**Issue by SupunS** [onflow/cadence#2541]
### Issue to be solved

Taking a reference to a nested-optional value (double-optional) results in type-checking errors.

```cadence
pub fun main() {
  var dict: {String: Foo?} = {}

  // Type of `dict["foo"]` is `Foo??`

  var ref = &dict["foo"] as &Foo??    // Static Error: cannot create reference. expected reference type, got `&Foo?`
}

pub struct Foo {}
```

This is solved to a certain extent in Stable-Cadence, with the parenthesized types added in https://github.com/onflow/cadence/pull/2140

i.e:
```cadence
  var ref = &dict["foo"] as &(Foo??)    // OK
```

However, the created reference is a reference to an optional (i.e: `&(Foo??)`), but not an optional reference (i.e: `(&Foo)??`) as proposed in [FLIP 722](https://github.com/onflow/flips/blob/main/cadence/20211208-cadence-remove-optional-reference.md)

### Suggested Solution

The issue is, currently the optional unwrapping happens only for one level. 
It would need to recursively unwrap optionals during reference creation.

**Comment by j1010001** [comment]
@SupunS to check if this would require breaking change. There is a workaround.

**Comment by SupunS** [comment]
> i.e:
>
> ```cadence
> var ref = &dict["foo"] as &(Foo??)    // OK
> ```
> However, the created reference is a reference to an optional (i.e: &(Foo??)), but not an optional reference (i.e: (&Foo)??) as > proposed in [FLIP 722](https://github.com/onflow/flips/blob/main/cadence/20211208-cadence-remove-optional-reference.md)

This is a breaking change, since the resulting type of the expression would be different after the change
