### ISSUE TITLE
Link values are not exportable from the runtime

### ISSUE THREAD

**Issue by psiemens** [onflow/cadence#259]
### Problem

When attempting to emit a storage write of type `interpreter.LinkValue`, the runtime panics because it fails to convert the value to a public `cadence.Value` type.

```
cannot convert value of type interpreter.LinkValue
```

This originates from this function, which does not have a switch case for `interpreter.LinkValue`: https://github.com/onflow/cadence/blob/83952e3867c91ab9fdad2c4c71303b8353970aa9/runtime/convertValues.go#L49-L111

### Steps to Reproduce

1. Execution a transaction with a `runtime.Interface` that implements `runtime.HighLevelStorage`
1. In this transaction, attempt to create link

```
self.account.link<&{NFTReceiver}>(/public/NFTReceiver, target: /storage/NFTCollection)
```
### Acceptance Criteria

The above link should ideally be emitted as type `cadence.Link`. Further more, a `cadence.Link` value should be encodable as JSON-CDC.

Alternatively, we could treat links as un-exportable and ignore them in the storage write handler.

### Context

This is preventing an upgrade of the Playground API, which currently breaks if a user saves a link.

**Comment by turbolent** [comment]
I went through the list of all structs conforming to `interpreter.Value`, the status is:


- [x] VoidValue
- [x] NilValue
- [x] SomeValue
- [x] BoolValue
- [x] StringValue
- [x] ArrayValue
- [x] IntValue
- [x] Int8Value
- [x] Int16Value
- [x] Int32Value
- [x] Int64Value
- [x] Int128Value
- [x] Int256Value
- [x] UIntValue
- [x] UInt8Value
- [x] UInt16Value
- [x] UInt32Value
- [x] UInt64Value
- [x] UInt128Value
- [x] UInt256Value
- [x] Word8Value
- [x] Word16Value
- [x] Word32Value
- [x] Word64Value
- [x] Fix64Value
- [x] UFix64Value
- [x] CompositeValue
- [x] DictionaryValue
- [x] AddressValue
- [ ] StorageReferenceValue
- [ ] EphemeralReferenceValue
- [ ] BlockValue
- [ ] CapabilityValue
- [ ] HostFunctionValue
- [ ] InterpretedFunctionValue
- [ ] BoundFunctionValue
- [ ] LinkValue
- [ ] PathValue
- [ ] PublicAccountValue
- [ ] AuthAccountValue
- [ ] TypeValue
  - StaticType
    - [ ] CapabilityStaticType
    - [ ] CompositeStaticType
    - [ ] ConstantSizedStaticType
    - [ ] DictionaryStaticType
    - [ ] InterfaceStaticType
    - [ ] OptionalStaticType
    - [ ] PrimitiveStaticType
    - [ ] ReferenceStaticType
    - [ ] RestrictedStaticType
    - [ ] VariableSizedStaticType
