### ISSUE TITLE
Add support for max arguments in a function

### ISSUE THREAD

**Issue by darkdrag00nv2** [onflow/cadence#2610]
### Issue to be solved

Right now, we don't have any support to limit the maximum number of arguments in variadic functions.

For example in `assert(_: Bool, message: String)`, I can pass `assert(10 == 10, message: "abc", "EXTRA ARGUMENT")` and the checker doesn't catch it. 

### Suggested Solution

It would nice to be able to limit the number of arguments as well.

**Comment by SupunS** [comment]
Added with https://github.com/onflow/cadence/pull/2656
