### ISSUE TITLE
Dictionaries key'd by type are order-dependent

### ISSUE THREAD

**Issue by austinkline** [onflow/cadence#2681]
### Current Behavior

If I have a dictionary key'd by `Type`, the order of their interface conformance matters:

```cadence
import FungibleToken from 0x1

pub fun main(): String {
  let t1 = Type<&{FungibleToken.Provider, FungibleToken.Balance}>()
  let t2 = Type<&{FungibleToken.Balance, FungibleToken.Provider}>()

  let dict: {Type: Bool} = {}
  dict[t1] = true

  assert(dict[t2] != nil, message: "key not found!")
  return "Done"
}
```

However, if I compare the two types, they are equal:

```cadence
import FungibleToken from 0x1

pub fun main(): String {
  let t1 = Type<&{FungibleToken.Provider, FungibleToken.Balance}>()
  let t2 = Type<&{FungibleToken.Balance, FungibleToken.Provider}>()

  assert(t1 == t2, message: "types are not equal")

  return "Done"
}
```

### Expected Behavior

I expect that two types which are equal should match to the same key in a dictionary

If I have a type `&{A, B}` and it is equivalent to `&{B, A}`, then my expectation is that a dictionary key'd on types should match regardless of their order

### Steps To Reproduce

Run this script on the flow emulator:

```cadence
import FungibleToken from 0xee82856bf20e2aa6

pub fun main(): String {
  let t1 = Type<&{FungibleToken.Provider, FungibleToken.Balance}>()
  let t2 = Type<&{FungibleToken.Balance, FungibleToken.Provider}>()

  // this will pass
  assert(t1 == t2, message: "types are not equal")

  let dict: {Type: Bool} = {}
  dict[t1] = true

  // this will fail
  assert(dict[t2] != nil, message: "key not found!")

  return "done"
}
```

### Environment

```markdown
- Cadence version: v1.3.2 (flow cli version)
- Network: Emulator
```

**Comment by dsainati1** [comment]
In general it would be nice to enforce that for any two types `T` and `U` such that `T = U`, `Type<T>() = Type<U>()` at runtime.

**Comment by turbolent** [comment]
To fix this, we need to:
- Fix the type ID function for type sets (e.g. currently, restricted types; in Stable Cadence, interface sets) to produce a canonical representation, i.e. fixed order. Like in CCF, we can probably use bytewise lexicographic order
- Migrate existing data, which involves re-hashing of dictionary keys

**Comment by austinkline** [comment]
> To fix this, we need to:
> 
> * Fix the encoding and hashing of type sets (e.g. currently, restricted types; in Stable Cadence, interface sets) of interpreter static types to produce a canonical representation, i.e. fixed order. Like in CCF, we can probably use bytewise lexicographic order.
> * Migrate existing data, which involves re-hashing of dictionary keys

Thanks for looking into this! Makes sense that a fix would be split into two parts. Is this something that makes more sense to bundle with stable cadence since migrations are already needed? Or it is able to be done at the next spork after encoding is "fixed" (whenever that may be)?

**Comment by dsainati1** [comment]
This would (I believe) be a breaking change, since any existing code that relies on these two type keys being different would have different behavior after we change them to be the same.

**Comment by austinkline** [comment]
> This would (I believe) be a breaking change, since any existing code that relies on these two type keys being different would have different behavior after we change them to be the same.

Definitely, yeah. Does how this gets handled change with Entitlements anyway? How is that migration being planned? Maybe this has some overlap

**Comment by dsainati1** [comment]
https://github.com/onflow/flips/pull/95 has the discussion of the entitlements migration

**Comment by j1010001** [comment]
Fix requires migration as part of Stable Cadence

**Comment by turbolent** [comment]
@dsainati1 It just occurred to me that authorizations of reference types should also be ordered. Could you please open an issue for this?
