### ISSUE TITLE
Computation limit exceeding errors are treated as internal errors

### ISSUE THREAD

**Issue by SupunS** [onflow/cadence#2682]
### Current Behavior

If the user exceeds the computation limit, it should be a user error. But currently it is treated as an internal error (and prints the go-stacktrace). e.g: https://github.com/onflow/cadence/issues/2679

### Expected Behavior

Such errors should be treated as user errors

### Steps To Reproduce

Run a transaction/code that exceeds the computation limit.

### Environment

```markdown
- Cadence version: latest/master
- Network: TN/MN
```

**Comment by bluesign** [comment]
There are many places this is happening, I think best to solve would be generate a list of errors from transaction results and fix them all in a single PR.
