### ISSUE TITLE
BUG: `unsafeRandom()` is not working in stable cadence on the emulator

### ISSUE THREAD

**Issue by joshuahannan** [onflow/cadence#2691]
### Current Behavior

When testing the emulator with stable cadence, using `unsafeRandom()` anywhere causes errors. 

If it is called in a script, 
```
error: internal error: [Error Code: 1057] operation (Random) is not supported in this environment
```

If it is called in a transaction:

```
 * transaction execute failed: [Error Code: 1101] cadence runtime error: Execution failed:
 error: internal error: runtime error: invalid memory address or nil pointer dereference
```

### Expected Behavior

Expected no error

### Steps To Reproduce

1. Pull down this branch in core contracts: https://github.com/onflow/flow-core-contracts/tree/stable-cadence
Follow these steps:
```
cd lib/go/test
go test -v --tags=relic -run TestEpochClusters
```
(may need to run `make crypto_setup_gopath` in the root of the repo to set up relic)

you'll see the error:
```
error: internal error: [Error Code: 1057] operation (Random) is not supported in this environment
```

Is it running this test: https://github.com/onflow/flow-core-contracts/blob/stable-cadence/lib/go/test/flow_epoch_test.go#L81-L149

where we first try to execute `unsafeRandom` with a script that goes through a function call in a contract and calls `unsafeRandom()` in the function.

If you comment lines 98-106 out and run again, you'll see the error in the next basic transaction that just calls `unsafeRandom()`

And see this error:
```
            * transaction execute failed: [Error Code: 1101] cadence runtime error: Execution failed:
        error: internal error: runtime error: invalid memory address or nil pointer dereference
```

### Environment

```markdown
- Cadence version:

github.com/onflow/cadence v0.39.13-stable-cadence.0.20230719215202-3311f5f8189b
github.com/onflow/flow-emulator v0.53.1-0.20230801165926-9fd4af1cce5b
github.com/onflow/flow-go v0.31.1-0.20230801162100-85890d2bf9bb
github.com/onflow/flow-go-sdk v0.41.10-0.20230719221154-2a4946e41c23
```
- Network: Emulator
```

**Comment by tarakby** [comment]
I implemented a fix. I need to discuss it with @janezpodhostnik before pushing it to the flow-emulator repo.

**Comment by tarakby** [comment]
addressed in https://github.com/onflow/flow-emulator/pull/459
