### ISSUE TITLE
Migration - Entitlements

### ISSUE THREAD

**Issue by j1010001** [onflow/cadence#2709]

**Comment by j1010001** [comment]
Remaining decision to make:
How do we deal with contracts that are not updated in time for migration during network upgrade ?
The way this migration is implemented depends on the decision - we could do some kind of lazy-migration at runtime.

**Comment by dsainati1** [comment]
https://github.com/onflow/cadence/pull/2705 and https://github.com/onflow/cadence/pull/2705 implement most of this, the remaining work here is just to hook up this functionality to the new migration framework, and pull in contracts as necessary to typecheck the new values.

**Comment by turbolent** [comment]
@dsainati1 Do you think we can close this know as done, or is there anything left to be done here?

**Comment by dsainati1** [comment]
Yeah! I’ll close it.
