### ISSUE TITLE
Re-enable disabled contract tests

### ISSUE THREAD

**Issue by dsainati1** [onflow/cadence#2719]
### Issue to be solved

https://github.com/onflow/cadence/pull/2670 disables some tests relying on the FT/NFT standards that use type requirements, testing that those contracts are functional. The tests should be re-enabled once the v2 versions of these standards are finished.

**Comment by turbolent** [comment]
Let's remove the tests once the Source Compatibility Suite is testing the contracts again, i.e. when #3608 is complete
