### ISSUE TITLE
Stable Cadence: Cannot create and borrow a generic capability

### ISSUE THREAD

**Issue by joshuahannan** [onflow/cadence#2721]
### Current Behavior

Using the latest stable cadence build, I am trying to create a capability that can be borrowed using the interface type, not the concrete type.
I linked the capability like this (from [setup_account](https://github.com/onflow/flow-ft/blob/v2-standard/transactions/setup_account.cdc)):
```
        // Create a public capability to the Vault that exposes the Balance interface
        signer.link<&{FungibleToken.Balance}>(
            ExampleToken.VaultPublicPath,
            target: ExampleToken.VaultStoragePath
        )
```
And tried to borrow it in a script like this (from [get_balance](https://github.com/onflow/flow-ft/blob/v2-standard/transactions/scripts/get_balance.cdc)):
```
access(all) fun main(address: Address, path: PublicPath): UFix64 {
    let account = getAccount(address)
    let vaultRef = account.getCapability<&{FungibleToken.Balance}>(path)
        .borrow()
        ?? panic("Could not borrow Balance reference to the Vault")

    return vaultRef.getBalance()
}
```
but when I try to run that script, it isn't letting me borrow it as a `FungibleToken.Balance` reference:
```
error: failed to force-cast value: expected type `{FungibleToken.Balance}`, got `ExampleToken.Vault`
```

### Expected Behavior

Expected the `getCapability()` and `borrow()` to return a `Balance` reference as usual.

### Steps To Reproduce

1. Check out the `v2-standard` branch of `onflow/flow-ft`
2. `cd lib/go/test`
3.  `go test -v -run TestCreateToken` (This runs [TestCreateToken](https://github.com/onflow/flow-ft/blob/v2-standard/lib/go/test/token_test.go#L32))
4. You should see the error. The transaction and script that is running is linked in the current behavior section above, and the contracts that are being used are `FungibleToken-v2` and `ExampleToken-v2`
5. If you want to make changes to the transaction or script, after you modify them you need to run `make generate` in the `lib/go` directory to generate the assets.

### Environment

```markdown
- Cadence version:

	github.com/onflow/cadence v0.39.13-stable-cadence.0.20230811182010-c66466eb6b1a
	github.com/onflow/flow-emulator v0.54.1-0.20230810231813-53e63bcc9c8f
	github.com/onflow/flow-go-sdk v0.41.10-0.20230719221154-2a4946e41c23
```
- Network: emulator
```

**Comment by dsainati1** [comment]
This should be fixed by https://github.com/onflow/cadence/pull/2674

**Comment by joshuahannan** [comment]
I haven't been able to verify if this is working yet in my tests, so I'm going to leave it open for now
