### ISSUE TITLE
Unified error messages for "not supported yet" or "upcoming features"

### ISSUE THREAD

**Issue by PratikDhanave** [onflow/cadence#2739]
### Issue to be solved

Cadence should provide unified error messages for "not supported yet" or "not  implemented yet " or  "upcoming features". 

That would invite contributors to contribute the missing functionality.

**Comment by PratikDhanave** [comment]
@turbolent please assign this to me

**Comment by SupunS** [comment]
Can you provide a bit more details: maybe an example of where this currently happens?
