### ISSUE TITLE
Revert changes in #2764 after Stable Cadence

### ISSUE THREAD

**Issue by dsainati1** [onflow/cadence#2766]
### Issue to be solved

https://github.com/onflow/cadence/pull/2764 improves the Stable Cadence migration path, but introduces an unfortunate parser ambiguity in the process. We should revert this change after Stable Cadence has been release for a sufficient time period.

**Comment by turbolent** [comment]
Please also add this to #2642

**Comment by turbolent** [comment]
Decision: Don't remove, leave for developers trying pre-1.0 code. 

TODO: Remove TODO and explain why code exists
