### ISSUE TITLE
Support using references in loops

### ISSUE THREAD

**Issue by SupunS** [onflow/cadence#2784]
### Issue to be solved

Currently, for-each loop only supports arrays, and doesn't support array references.
i.e:
```cadence
var arrayRef: &[String] = ...

for element in arrayRef {    // Error

}
```

However, with the mutability changes, given fields can now return references, it would be useful to be able to use array references in loops as well.

### Suggested Solution

Allow using array references in for loops.
```cadence
for v in arrayRef {}
```
For an array of type `[T]`, the type of the loop-variable `v` would be:
  - The concrete type `T`, if the array element type `T` is a primitive.
  - A reference type `&T`, if the array element is a container type.

This is to be consistent with the member access semantics: https://github.com/onflow/flips/blob/120b8aa473e5040db2b99034d2118fb78d053cdf/cadence/20230517-member-access-semnatics.md

**Comment by turbolent** [comment]
We might want to get this implemented as part of Cadence 1.0 to ease with the transition and not require developers to migrate their contracts to worse versions (like in https://github.com/onflow/flow-core-contracts/pull/382#discussion_r1326119444)

**Comment by bluesign** [comment]
```
For an array of type [T], the type of the loop-variable v would be:

The concrete type T, if the array element type T is a primitive.
A reference type &T, if the array element is a container type.
```

second part confused me a little, why &T ?

**Comment by SupunS** [comment]
This is beacsue with the [member-access semantics change](https://github.com/onflow/flips/blob/120b8aa473e5040db2b99034d2118fb78d053cdf/cadence/20230517-member-access-semnatics.md), if `arrayRef[i]` would return `&[String]`. So we would need to keep the same semantics in the loop as well.

More details are available here: https://developers.flow.com/next/cadence/language/references#field-and-index-access
