### ISSUE TITLE
Add `replace` and `replaceAll` functions to String

### ISSUE THREAD

**Issue by darkdrag00nv2** [onflow/cadence#2813]
### Issue to be solved

Add `replace` and `replaceAll` instance functions to Cadence. 

1. `replace(_ of: String, _ with: String): String`: Returns a new String after replacing first occurrence of `of` with `with`.
2. `replaceAll(_ of: String, _ with: String): String`: Returns a new String after replacing all occurrences of `of` with `with`. 

Epic: https://github.com/onflow/cadence/issues/1972

**Comment by turbolent** [comment]
`replaceAll` was added in #2814. We can add e.g. a `replaceFirst` when there is demand.
