### ISSUE TITLE
Suprising behaviour for dictionary insertion 

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#2818]
### Issue to be solved

Constructing a dictionary using a literal inserts elements into the dictionary as-is.
Assigning to a dictionary indexing expression unwraps the value.

```cadence
let inner: {String: Int} = {"test": 10}
let outer: {String: AnyStruct} = {"a": inner["test"]}
outer["b"] = inner["test"]
```

This result in the two keys having different values:

```
{"b": 10, "a": 10 /* optional */}
```

This behaves the same in Swift:

```swift
let inner: [String: Int] = ["test": 10]
var outer: [String: Any] = ["a": inner["test"]]
outer["b"] = inner["test"]
print(outer)
```

```
["b": 10, "a": Optional(10)]
```

This behaviour is surprising, but correct: Assignments take optionals, just like a lookup returns an optional.

### Suggested Solution

There are multiple options on how this could be improved:

- Unwrap in literal construction, just like assignment does
- Change assignment to not assign optional, but non-optional (plain dictionary’s value type)
  - Removes ability to assign with `nil` to remove, but equivalent is simply calling `remove`, which is also more explicit
  - Breaks:
     - Swapping, which assumes lookup and assignment types are the same, but could be handled specially
     - Variable declarations with second value, e.g. `let r <- rs["foo"] <- nil`

- Improving casting: The problem might be less in the behaviour of how the data is stored, but how with how the data can be worked with.

  For example, in Swift, casting to optional types boxes and unboxes if needed:

  ```swift
  let x: Int?? = 1
  let y: Int? = 1

  x as! Int?   // is `Optional(1)`
  y as! Int??  // is `Optional(Optional(1))`
  ```

  This makes it possible to perform lookup in dictionaries and cast to the desired/expected type easily.
    
  Cadence currently does not provide this behaviour, so a lookup and cast might succeed or fail depending on the key:

  ```cadence
  outer["a"] as? Int?  // is `nil`, as the value actually has type `Int??`
  outer["b"] as? Int?  // is `Optional(Optional(10))`, as the dictionary value itself is `Int?`, 
                       // and the result of the failable cast results in `Int??`
    ```

Notes:

Implicit boxing is convenient and usually not a source of problems. Requiring explicit boxing would be tedious.
However, implicit unboxing is often confusing.

**Comment by turbolent** [comment]
We discussed this in the team, and favoured change assignment to not assign optional.

However, after the discussion I tried making the proposed change and ran into several issues, see the "Breaks" point in the description above.

This issue needs some more discussion on how we want to proceed.

**Comment by dsainati1** [comment]
> This issue needs some more discussion on how we want to proceed.

Does the community feel this merits a FLIP or can this be handled in this issue?

**Comment by bluesign** [comment]
Personally I don't think this needs FLIP, if we introduce with stable cadence

**Comment by turbolent** [comment]
> Does the community feel this merits a FLIP or can this be handled in this issue?

@dsainati1 We'll want to first discuss a design that works and we're aligned on, then propose it in a FLIP

**Comment by turbolent** [comment]
From @SupunS:
Swapping and variable declaration with second value could be both rewritten with `remove`

**Comment by SupunS** [comment]
[Adding some more context/explanation]

So yeah, assuming if the change is done, the two affected cases:

- Second value assignment
  ```cadence
  let r <- rs["foo"] <- nil
  ```
  Could be replaced by:
  ```cadence
  let r <- rs.remove("foo")
  ```

- Swap
  - Like you mentioned in the description, it could be special-cased to handle this.
  - The argument here is that, special-casing swap (and keeping the current behavior) is hopefully more compared to having two different behaviors for the normal assignment vs dictionary literal.
  - i.e: following will continue to work.
    ```cadence
    rs["foo"] <-> rs["bar"]
    ```

**Comment by turbolent** [comment]
This issue hasn't seen any more discussions about and feedback on the proposed improvement and its problems.

If we want to include an improvement in Cadence 1.0, we'll need a concrete improvement proposal.

cc @jacob-tucker
