### ISSUE TITLE
[stable-cadence] Improve type inference for authorized references

### ISSUE THREAD

**Issue by SupunS** [onflow/cadence#2826]
### Issue to be solved

When there are auth references with a common entitlement, the type-inferring infers the supertype type as `AnyStruct`.

```cadence
access(all) 
fun main(
    a: auth(Insert, Mutate) &[String],
    b: auth(Remove, Mutate) &[String]
) {

    // OK: both `a` and `b` have `Mutate` entitlement. 
    let c: [auth(Mutate) &[String]] = [a, b]

    // However, when inferring, type of `d` is inferred as `[AnyStruct]`
    let d = [a, b]

    // Static Error
    let e: [auth(Mutate) &[String]] = d
}
```

### Suggested Solution

It could be improved to consider the common entitlement, and to infer the supertype as `auth(Mutate) &[String]`

**Comment by j1010001** [comment]
nice to have for Stable Cadence
