### ISSUE TITLE
BUG: Error when deploying contract to latest vscode extension emulator

### ISSUE THREAD

**Issue by joshuahannan** [onflow/cadence#283]
### Problem

When I deploy a contract to the vscode extension, I get an error that prevents the deployment. It does not panic though.

### Steps to Reproduce

1. Copy any contract to a cadence file. I used this one:
```
pub contract Test {
    pub let field: Int

    init() {
        self.field = 10
    }
}
```
2. Start the emulator and try to deploy to the first account.
3. See the error in the output:
```
[Info  - 11:27:24 AM] checking file:///Users/joshuahannan/flow/onflow/flow-core-contracts/contracts/epochs/test.cdc took 459.343µs
called execute command: cadence.server.flow.updateAccountCode
update acct code args: [file:///Users/joshuahannan/flow/onflow/flow-core-contracts/contracts/epochs/test.cdc]
[Error - 11:27:30 AM] Request workspace/executeCommand failed.
  Message: cannot sign transaction: unknown account 0000000000000000
  Code: -32603 
```

**Comment by turbolent** [comment]
This might be a bug in the Visual Studio Code extension or an integration with it (settings, SDK/client library, emulator, etc)

**Comment by joshuahannan** [comment]
@psiemens @10thfloor any thoughts?

**Comment by turbolent** [comment]
We'll look into it tomorrow @joshuahannan

**Comment by 10thfloor** [comment]
Yeah no more acct 000000

**Comment by joshuahannan** [comment]
The button that I click to deploy the contract says deploy to account 0x01cf0e2f2f715450, but the dialogue box that pops up says, `Deploying FlowStaking.cdc to account 0x0000000000000000`

**Comment by joshuahannan** [comment]
I disabled the https://marketplace.visualstudio.com/items?itemName=karigari.chat extension and the cadence vscode extension started working properly. The presence of this extension was causing the language server to fail repeatedly

**Comment by psiemens** [comment]
@joshuahannan That's interesting. The presence of that extension was causing this specific bug?

**Comment by turbolent** [comment]
We debugged on @joshuahannan's machine and when VS Code started up, the "extension host" errored (no stack trace), but the path was for that extension. Disabling it resolved the error and made the Cadence extension work. Enabling the chat extension again made brought back the error.

However, I have the Chat extension installed and enabled on my machine and everything works just fine. 

Don't really have a good answer here, it's hard to fix because I can't reproduce it locally
