### ISSUE TITLE
Add more integration tests for atree inlining

### ISSUE THREAD

**Issue by fxamacker** [onflow/cadence#2837]
### Issue to be solved

More integration tests for atree inlining can be added to Cadence after https://github.com/onflow/atree/issues/342 and https://github.com/onflow/atree/issues/345 are merged.

Updates https://github.com/onflow/atree/issues/346

### Suggested Solution

Add more integration tests for atree inlining.

For example, inserting a child into a parent, mutating it, removing the child from that parent, mutating it, and then inserting the child into another container, and mutating it.

**Comment by j1010001** [comment]
what we have now is sufficient after we have smoke tests running successfully.
