### ISSUE TITLE
Fix incorrect type inference for InclusiveRange

### ISSUE THREAD

**Issue by darkdrag00nv2** [onflow/cadence#2886]
### Issue to be solved

https://github.com/onflow/cadence/pull/2523/files#r1361281514

> While testing, I also ran into the following cases that currently report errors, but shouldn't:
>
> The inclusive range constructor always takes Int as the type parameter's type.
> ```cadence
> let r = InclusiveRange<Int>(0, 10)    // Works
> ```
>
> ```cadence
> let r = InclusiveRange<Int8>(0, 10)    // Checker error (should also work)
> ```
>
> Also probably related to above, Type inferring also doesn't infer the type parameter from LHS.
> ```cadence
> let r: InclusiveRange<Int8> = InclusiveRange(0, 10)   // Type-mismatch error
> ```

**Comment by darkdrag00nv2** [comment]
@SupunS 

Did a bit of investigation on this. I can see that we don't support type inference of function arguments as suggested by this comment: https://github.com/onflow/cadence/blob/323b887c1202eaa99119d44308f8f70758b20426/runtime/sema/check_invocation_expression.go#L577

So seems like both the cases mentioned are not bugs but more of an existing limitation.

I am happy to take a shot at adding this support but would it be possible to untie this with the InclusiveRange work? I would like to wrap up the grant work sooner if possible and then take this up unless we consider this to be a blocker for the InclusiveRange feature. Thoughts?

cc: @turbolent

**Comment by turbolent** [comment]
I didn't realize we still had some gaps there. Aren't we already using this elsewhere, e.g. for the storage `save` function? Has this maybe improved on the `feature/stable-cadence` branch?

The work on the standard library identified this gap in the checker, but the work / grant for the standard library is is not dependent on resolving these gaps, no worries. 

We might still need to address these gaps before we can ship the feature, but that is separate from your grant.

**Comment by SupunS** [comment]
Makes sense. If this is already an existing limitation, and fixing it requires changing the way type-parameters are type-checked in general, then yeah, we can/should do it separately 👍 

Thanks for looking into this!

**Comment by darkdrag00nv2** [comment]
> I didn't realize we still had some gaps there. Aren't we already using this elsewhere, e.g. for the storage save function? Has this maybe improved on the feature/stable-cadence branch?

@turbolent No, this hasn't improved. Please check this test: https://github.com/onflow/cadence/blob/7e955a3110542bf487e2f3d4c2cea01854afaf90/runtime/tests/checker/type_inference_test.go#L338-L409

**Comment by turbolent** [comment]
Looking into this
