### ISSUE TITLE
Split runtime/interpreter/interpreter.go into multiple files

### ISSUE THREAD

**Issue by PratikDhanave** [onflow/cadence#2908]
### Issue to be solved

Issue to be solved

The runtime/interpreter/interpreter.go file is huge. Even the GitHub syntax highlighting gets disabled on PR reviews because of the huge size.

### Suggested Solution

We should consider splitting the file into different files

**Comment by j1010001** [comment]
This should not be done until we merge Stable Cadence feature branch to master.
