### ISSUE TITLE
Links don't open to correct Cadence version in docs, resulting in 404

### ISSUE THREAD

**Issue by 10thfloor** [onflow/cadence#2988]
### Current Behavior

When reading this article: https://forum.flow.com/t/update-on-cadence-1-0/5197 
I discovered it contains a dead link in the section: https://forum.flow.com/t/update-on-cadence-1-0/5197 (Entitlements and Safe Down-casting)

<img width="759" alt="Screenshot 2023-12-24 at 12 48 10 PM" src="https://github.com/onflow/cadence/assets/901466/5c8436ba-37be-405e-82fd-f6f8e187a0bc">

The dead link points to here: https://developers.flow.com/next/cadence/language/access-control#entitlements
Resulting in a 404

*It happens because the Cadence version switcher in the docs site does not point to the v1 docs, when opening the link from the forum post.*

### Expected Behavior

Links to topic in v1 docs open to the correct version-page on cadence-lang.org

### Steps To Reproduce

Click the link, feel the pain.

### Environment

```markdown
- Cadence version: NA
- Network: NA
```

**Comment by j1010001** [comment]
Thanks for the report! fixed the link in the forum post to point to https://cadence-lang.org/docs/1.0/language/access-control#entitlements
