### ISSUE TITLE
Migrations for core contract changes

### ISSUE THREAD

**Issue by j1010001** [onflow/cadence#3007]
The core contracts (e.g. FT/NFT standards) need to be updated to Cadence 1.0. Some of the required code changes also require state to get migrated.

Evaluate and implement the necessary state migrations

**Comment by turbolent** [comment]
https://www.notion.so/dapperlabs/Cadence-Implementation-Sync-Notes-Agenda-640389e72df942668d89deadd8d291de?pvs=4#129e6aa0d7834b35849bd61cef21608b

**Comment by turbolent** [comment]
It seems like we need a migration of existing types such as `@FungibleToken.Vault` to `@{FungibleToken.Vault}`, in values like `Type` and `Capability`.

We already have an existing general Cadence 1.0 migration for migrating the account types. Would it make sense to refactor it and generalize it to any such type rewrite, and we could then add arbitrary type replacement rules?

**Comment by SupunS** [comment]
+1 for extending the account type migration.
I think we can extend it to accept  something like a 'composite/interface type conversion function' and use it here:  https://github.com/onflow/cadence/blob/23a0f5905d5e9e7f23395496dea149672b299390/migrations/account_type/migration.go#L160-L162

**Comment by dsainati1** [comment]
This makes sense to me!

**Comment by SupunS** [comment]
We can also probably merge it with `type_value/migration` as well. Both pretty mush has the same logic.

**Comment by turbolent** [comment]
@SupunS Do you mean that we should merge the `type_value` and the `account_type` migration, and generalize it so that it also can support other type rewrite rules, like the one needed for the FT/NFT standards?

**Comment by SupunS** [comment]
yeah, I can open a quick PR for the merging, if you already haven't started.
While looking, I also realize the type_value migration may missing some cases too, so definitely we should combine

**Comment by turbolent** [comment]
That would be great, thanks! I haven't started yet

**Comment by joshuahannan** [comment]
I finished looking through the core contracts and the only issues that I found with the migration are related to updating `FlowToken.Vault` capabilities to `auth(FungibleToken.Withdraw)`. Here is a list for reference:

    * LockedTokens: [Line 94](https://github.com/onflow/flow-core-contracts/blob/stable-cadence/contracts/LockedTokens.cdc#L94): Update the stored vault capability in the locked token manager to auth(FungibleToken.Withdraw). 
    * Locked Tokens: [Line 282](https://github.com/onflow/flow-core-contracts/blob/stable-cadence/contracts/LockedTokens.cdc#L282): Update LockedTokenManager capability in TokenHolder to be auth(FungibleToken.Withdraw)
    * FlowStakingCollection [Line 58](https://github.com/onflow/flow-core-contracts/blob/stable-cadence/contracts/FlowStakingCollection.cdc#L58), [131](https://github.com/onflow/flow-core-contracts/blob/stable-cadence/contracts/FlowStakingCollection.cdc#L131): Update the FlowToken.Vault capability in stored `MachineAccountInfo` structs to be auth(FungibleToken.Withdraw)
    * FlowStakingCollection: [Line 108, 112](https://github.com/onflow/flow-core-contracts/blob/stable-cadence/contracts/FlowStakingCollection.cdc#L108-L112): Update the locked and unlocked vaults in all staking collections to be auth FungibleToken.Withdraw

**Comment by turbolent** [comment]
@dsainati1 I think the entitlements migration will already take care of these, and there is no dedicated migration required here?

**Comment by joshuahannan** [comment]
> Yes, if the entitlements are added to the appropriate resources/interfaces then the migration should take care of capabilities referencing them.

Does that mean that every user has to run a transaction to update the capabilities in their account to re-link them with the correct entitlement, or is the migration just going to find every unrestricted capability for a Fungible Token vault and turn it into a `Withdraw`-entitled capability?

**Comment by dsainati1** [comment]
> is the migration just going to find every unrestricted capability for a Fungible Token vault and turn it into a Withdraw-entitled capability?

This one. In essence the migration transforms every reference value (i.e. the borrow type of the capability) into an entitled reference that is entitled to the exact same set of functions old reference was able to access. This is why it's so critical that developers don't bundle business logic changes with their 1.0 upgrades, because it breaks our ability to determine what entitlements to grant to give access to the "old" behavior. 

For capability fields, the capability in the field is migrated the same way any other capability in storage is, the capability is just "owned" by a composite value.

**Comment by j1010001** [comment]
can be closed after v2 token standards are finalized.
