### ISSUE TITLE
Qualifying a contract-level struct errors

### ISSUE THREAD

**Issue by dangdennis** [onflow/cadence#312]
### Instructions

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.

### Problem

Qualifying a contract-level struct with its contract name gives an error. 

Example:

```
contract A {
   pub struct B {}
}
```

I'd expect to be able to do `A.B()`. I have a playground to share.

### Steps to Reproduce

https://play.onflow.org/1e0a4413-21f8-4302-b7d4-6705bd78dc5d

Starting at line 245, if you quality `HealthStats` as `HealthCrossingCore.HealthStat`, Cadence returns an error.

### Acceptance Criteria

You should be able to qualify the contract struct.

### Context

This is a non-blocking issue because I don't necessarily have to qualify the struct with the contract name.

**Comment by turbolent** [comment]
Thanks for reporting this @dangdennis!

This should be supported, but there seems to be an issue with the initialization order: `HealthCrossingCore`'s initializer creates a `ProgressEngine` instance, and the `ProcessEngine` initializer in turn refers to `HealthCrossingCore.HealthStat` – which seems to be not available yet.

We might have to restrict the use of the contract object inside the contract itself, as an initializer of a contract may call code which refers to the contract before the contract is fully initialized, which is illegal. I'll have to think about it a bit more
