### ISSUE TITLE
Restrict the entitlements allowed by the contract update validator

### ISSUE THREAD

**Issue by SupunS** [onflow/cadence#3128]
> Currently this allows any set of entitlements with equal or less access permitted than the "actual" access granted by the migration. E.g. if some reference `&T` will be given `auth(E, F)` by the migration, users can update that type in a field to any of `&T`, `auth(E) &T`, `auth(F) &T`, `auth(E | F) &T` or `auth(E, F) &T`. 
>
> s this okay, or should we be more restrictive and require that users only migrate their field types to exactly what the migration will grant?

_Originally posted by @dsainati1 in https://github.com/onflow/cadence/pull/3069#discussion_r1476509028_

**Comment by SupunS** [comment]
IMO we should restrict the update checker to allow field types to be exactly what the entitlement migration will grant

**Comment by turbolent** [comment]
Is it a problem if they choose a less permissive variant?
