### ISSUE TITLE
Support Composite Types (struct) as event parameters

### ISSUE THREAD

**Issue by joshuahannan** [onflow/cadence#313]
### Issue To Be Solved

It would be useful to be able to use a composite type as an event parameter so contracts can communicate complex information with the outside world without having to awkwardly split up the data.

### Suggest A Solution

* Support for any struct as a event parameter
* Support for understanding and parsing the struct in other languages like Go.
* Do not support resources

### Context

This is blocking our ability to efficiently emit important events in the Flow Epoch Smart Contracts. We have a workaround, but would prefer to emit structs in our events.

### Definition of Done

- [ ] Sema: Allow structs as event parameters
- [ ] Tests: Sema, Interpreter
- [ ] Documentation

**Comment by turbolent** [comment]
This should be easy to support for structs, as they are copied.

The change itself would entail [adding a case in `sema.IsValidEventParameterType`](https://github.com/onflow/cadence/blob/4b67098d457e56a467a3e837c215ae34ca90e613/runtime/sema/check_event_declaration.go#L73-L72)

**Comment by turbolent** [comment]
@joshuahannan This is a good first issue, would anyone from the Reliability Pod working on the contracts be willing to pick this up? It should be fairly small and I'd be happy to assist

**Comment by joshuahannan** [comment]
I could do it if you can help me out!

**Comment by turbolent** [comment]
Definitely! Let me know when you'd have time and we could pair up if you want
