### ISSUE TITLE
Loading values from a migrated emulator state fails

### ISSUE THREAD

**Issue by SupunS** [onflow/cadence#3143]
### Issue to be solved

Loading already stored values from a migrated emulator state fails for certain values. e.g: Dictionary values.

This could be either:
- A problem in the way the updated payloads are written back to the emulator state, or
- A problem with the migration

Needs to investigate further.

**Comment by turbolent** [comment]
Is there any kind of error that is reported?

**Comment by SupunS** [comment]
The two errors that I ran into so far was:
- Loading a dictionary (say `{String:Int}`) loads some random dictionary value.
  ```
  error: failed to force-cast value: expected type `{String: Int}`, got `{UInt64: Never?}`
    --> d15604fc4f6a3ebafa9de405add09237341bcb45505cd167798de1d65f3fbaa4:16:16
     |
  16 |     var dict1 = acct.storage.load<{String: Int}>(from: /storage/dictionary_with_string_keys)
     |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ```
  The value is indeed something else (e.g: `{2: nil}`)

- Imports cannot be found after migrating the contract

**Comment by SupunS** [comment]
It seems the registers are somehow messed up

**Comment by turbolent** [comment]
It's weird that this happens, given that the we have a test case in flow-go that works

**Comment by turbolent** [comment]
Maybe this is caused by https://github.com/onflow/cadence/pull/3141?

**Comment by SupunS** [comment]
> Maybe this is caused by the gap that https://github.com/onflow/cadence/pull/3141 fills?

It shouldn't be: the said dictionary value doesn't change it's static type (its a `{String: Int}` value), so #3141  wouldn't really impact this one.

**Comment by SupunS** [comment]
Values in the storage seems to be correct: https://github.com/onflow/flow-emulator/pull/584

**Comment by SupunS** [comment]
Maybe the way the register keys are created/encoded got changed in the emulator latest version, or something like that? 🤔

**Comment by SupunS** [comment]
So it turns out to be the snapshot was taken before shutting down the emulator, which may have left the store with some unwritten data.

**Comment by turbolent** [comment]
What are the steps for creating a valid snapshot? We'll have to document this and provide it to developers
