### ISSUE TITLE
Recommend appropriate authorization for type mismatch

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#3145]
### Issue to be solved

Currently, type mismatch errors show the expected type as-is. 

This makes sense for most types, but for reference types, showing the expected authorization when it is a disjunction, might confuse the user, as they often understand the expected type as the proposed fix, so they might literally copy it into their code.

For example, consider the following transaction:

```cadence
transaction {
    prepare(signer: &Account) {
        Account(payer: signer)
    }
}
```

This reports the following, correct, error:

```
  |
4 |         Account(payer: signer)
  |                        ^^^^^^ expected `auth(BorrowValue | Storage) &Account`, got `&Account`
```

A user is likely to try and fix this error by taking the expected type and changing the `prepare` block's parameter list to `prepare(signer: auth(BorrowValue | Storage) &Account)`, which is an incorrect fix.

### Suggested Solution

When a type mismatch error involved a missing authorization that is a disjunction, propose a list of types as suggested fixes.

For example, given the expected type `auth(BorrowValue | Storage) &Account`, propose `auth(BorrowValue) &Account` and `auth(Storage) &Account` as suggested fixes.

**Comment by turbolent** [comment]
cc @dsainati1

**Comment by turbolent** [comment]
It seems like a prevalent problems, as questions for similar problems have been asked on Discord multiple times before

**Comment by dsainati1** [comment]
> A user is likely to try and fix this error by taking the expected type and changing the prepare block's parameter list to prepare(signer: auth(BorrowValue | Storage) &Account), which is an incorrect fix.

Why is this an incorrect fix?

**Comment by turbolent** [comment]
Maybe I'm misunderstanding how disjunction authorizations for references work, but I assumed that they behave similar to union types, and e.g. `auth(T | U) &V` does not satisfy access to `auth(T | U) &V`, given that it has "neither" `T` or `U`

**Comment by dsainati1** [comment]
An `auth(T | U) &V` is like a union, in that it is guaranteed to have one of `T` or `U`. This is sufficient to satisfy access to `access(T | U)` because that requires access to one of `T` or `U`. We don't know which entitlement the reference actually has, but that doesn't matter because we know it does have one of the ones it needs to.

**Comment by turbolent** [comment]
Ah, I see, thanks for explaining this! In that case we can probably close this issue. 

Before we do though: Do we have this documented? If so, we can close, otherwise it might be good to have a short explanation, even literally just your last comment, in the docs.

**Comment by dsainati1** [comment]
I think we did originally plan to include this in the entitlements docs, but decided not to because it would be confusing, if I recall correctly. I can easily add it back though.

**Comment by turbolent** [comment]
Given questions and confusion came up before, it might be good to have a note about the interaction between disjunctions in the docs 👍

**Comment by bluesign** [comment]
`prepare(signer: auth(BorrowValue | Storage) &Account)` how this will work? signer will be one of them or both ?

**Comment by dsainati1** [comment]
This is saying that the `singer` must have at least one of these entitlements. Both is also okay, but all we know about it is that it has one of them.

**Comment by bluesign** [comment]
> This is saying that the `signer` must have at least one of these entitlements. Both is also okay, but all we know about it is that it has one of them.

maybe need to document how FVM (or Cadence not sure where it is created) will create the value, now it is a bit undefined behavior.

**Comment by turbolent** [comment]
The account value is always the same, the type annotation is purely static (and part of the reference). There isn't really anything undefined here and documenting implementation details doesn't help developers.

**Comment by bluesign** [comment]
> The account value is always the same, the type annotation is purely static (and part of the reference). There isn't really anything undefined here and documenting implementation details doesn't help developers.

Ah true, I always mix this with C1.0. Thanks a lot.
