### ISSUE TITLE
emit account key information in AccountKeyAdded event

### ISSUE THREAD

**Issue by rrrkren** [onflow/cadence#3146]
### Issue to be solved

the old `AccountKeyAddedFromByteArrayEventType` event contained a publickey field which is a byte encoded value of `runtimeAccountPublicKeyWrapper` [injected dependency defined here](https://github.com/onflow/flow-go/blob/master/model/flow/account_encoder.go#L36) With this event payload one is able to identify all information of the public key that was added to this account except for index. 
the new `AccountKeyAddedFromPublicKeyEventType` event only contains the raw public key itself with no additional account key information. 

### Suggested Solution

emit the following information in `AccountKeyAddedFromPublicKeyEventType`:
- account address
- public key raw value
- sig algo
- sign algo
- weight
- keyIndex

**Comment by rrrkren** [comment]
to implement this my understanding is we'd modify the event type here:
https://github.com/onflow/cadence/blob/master/runtime/stdlib/flow.go#L217

then emit the corresponding information here:
https://github.com/onflow/cadence/blob/master/runtime/stdlib/account.go#L627

and update/add tests.

if this seems right I'll attempt a PR at this 🙏

**Comment by turbolent** [comment]
@rrrkren Thanks for opening this issue and offering to implement the changes 🙏 The links to the implementation are correct, these are the places that need to be adjusted.
