### ISSUE TITLE
Enable iteration over array references using for-in loop

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#315]
### Issue To Be Solved

Currently the for-in loop is only supported for arrays. When working with storage, it is likely that a developer acquires a reference to an array.

Enable for-in loops to iterate over array references:

```swift
let array = [1, 2, 3]
let arrayRef = &array as &[Int]
for element in arrayRef {
    log(element)
}
```

### Definition of Done

- [ ] Checker: Extend check of for-in loops from array types to also include array reference types
- [ ] Interpreter: Potentially make iteration over references work. The code should already work, but might not
- [ ] Tests
- [ ] Documentation

**Comment by turbolent** [comment]
@SupunS Was this already done for Cadence 1.0?

**Comment by SupunS** [comment]
Added in https://github.com/onflow/cadence/pull/2876
