### ISSUE TITLE
Improve program checking in Cadence 1.0 migration

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#3233]
Parts of the full Cadence 1.0 migration load programs, for example the entitlements and links migration.

Currently we only cache programs per account: each `MigrateAccount` call creates a new migrator runtime, which in turn creates a new `environment.Programs`. We might be able to re-use program checking results across accounts ("problem": concurrency), and even across migrations: we need programs for the values migration (entitlements), but then also again for the link migration.

After we've updated contracts (first two migrations, updating system and user contracts), and before starting the values migrations which need programs, we can probably just run a new migration/pass, which checks all programs, once, for all subsequent migrations that may need them. We might check more than needed, and have to keep them all in memory (vs just if a value refers to the type, and only during a migration of an account), but still might be simple and effective.

**Comment by dsainati1** [comment]
The re-use of the cache discussed in https://github.com/onflow/cadence/pull/3232 also seems like it could be done as part of this.
