### ISSUE TITLE
Add C1.0 migration metric for evaluating migrated state

### ISSUE THREAD

**Issue by j1010001** [onflow/cadence#3243]
### Issue to be solved

We need to know what is the percentage of on-chain state which has been migrated as a result of Cadence 1.0 migration. This will help us make better go/no-go decision for the testnet and mainnet upgrade to C1.0.

The ideal outcome IMO is to say "from total X of Values stored on chain, Y has been successfully migrated and Z was not because the related contract was not staged."

In addition, for each on-chain contract we want to know how many on-chain values/objects relate to it and maybe how much storage is used by those. This will help us evaluate if there are any significant contract that are not staged that hold significant number of on-chain state.

**Comment by bluesign** [comment]
this is only good for mainnet, but also nothing is staged for mainnet. I think good approach would be to match staged contracts to mainnet.

**Comment by j1010001** [comment]
> this is only good for mainnet, but also nothing is staged for mainnet. I think good approach would be to match staged contracts to mainnet.

Yes, We need to push for devs to stage for TN and MN at the same time, as we are getting closer to TN upgrade.
