### ISSUE TITLE
JSON-Cadence Interchange Format docs need to be updated for Cadence 1.0

### ISSUE THREAD

**Issue by ben-graffle** [onflow/cadence#3244]
### Issue to be solved

JSON-Cadence Interchange Format docs need updated for Cadence 1.0

https://cadence-lang.org/docs/json-cadence-spec

I am the maintainer for a dotnet sdk for flow which is responsible for parsing event json - updated docs for what to expect with Cadence 1.0 would make this process significantly easier

**Comment by turbolent** [comment]
@Aliserag Could 4D maybe help with this?

**Comment by gregsantos** [comment]
@turbolent @ianthpun should be able to update this week
