### ISSUE TITLE
Add pre-1.0 backward-compatibility to JSON and CCF decoding (SDK)

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#3250]
https://discord.com/channels/613813861610684416/1229932575959552003

Network clients may need to support both current (pre-Cadence 1.0) and Cadence 1.0 networks.

Add support for decoding old values to the JSON and CCF decoders. 
Forbid importing such values into the interpreter.

**Comment by j1010001** [comment]
Specifically, this is blocking @rrrkren and @austinkline to do further testing with flow-go SDK.

**Comment by rrrkren** [comment]
a did a temporary hack by by replacing https://github.com/onflow/cadence/blob/v0.42.10/encoding/json/decode.go#L1196-L1201 with `return cadence.TheAnyType` 
if we can make it so that the sdk versions pre 1.0 can work with both pre/post 1.0 network that'd be great
