### ISSUE TITLE
Resource interface conformance issue

### ISSUE THREAD

**Issue by joshuahannan** [onflow/cadence#326]
### Problem

When specifying a restricted reference to a resource as a return value, the checker reports that `restricted type does not conform to restricting type`. Is this intentional, or is it a bug?

### Steps to Reproduce

1. Copy this code:
```
pub contract Nester {
    pub resource interface Nesting {
        pub fun get(): &Thing{Nesting}
    }
    pub resource Thing: Nesting {
        pub fun get(): &Thing{Nesting}
    }
}
```
2. See the error on the return types: restricted type does not conform to restricting type: Nester.Nesting

**Comment by turbolent** [comment]
@joshuahannan Thanks for reporting it, it could be s a shortcoming in the order of how the declarations are checked. I'll have a look early next week
