### ISSUE TITLE
Add and removing a resource from a dictionary deletes the entire resource

### ISSUE THREAD

**Issue by dangdennis** [onflow/cadence#327]
### Problem

Accounts are losing its resource after attempting to remove a resource from a dictionary via the shift statement:
`let oldResource <- self.collection[key] <- newResource`

### Steps to Reproduce

https://play.onflow.org/14fca9a8-1068-4897-9c51-0e70f775b0d7

1. Deploy the first contract HelloWorld
2. Init any account with the first transaction `init collection`
3. Add a new resource to the same account with transaction `add new thing`

### Acceptance Criteria

I should expect to see the collection resource present in my account. 

### Context

Blocker because I cannot properly update resources inside my accounts.

**Comment by joshuahannan** [comment]
I'm not sure what the issue is @dangdennis. It looks like the collection is stored in your account. The transactions that use it are working correctly.

**Comment by dangdennis** [comment]
Hi Josh, after running the second transaction, you may be able to see that the collection resource is null. Are you seeing that?

**Comment by dangdennis** [comment]
After transaction 1:

<img width="1183" alt="Screen Shot 2020-08-19 at 10 03 22 AM" src="https://user-images.githubusercontent.com/22418429/90644887-4a723780-e203-11ea-81c5-718dd8126800.png">

After transaction 2: 
<img width="1016" alt="Screen Shot 2020-08-19 at 10 03 32 AM" src="https://user-images.githubusercontent.com/22418429/90644924-552ccc80-e203-11ea-913f-fcec162bd172.png">

**Comment by joshuahannan** [comment]
Yeah I see that, but the fact that you can keep running transaction 2 over and over again shows that the resource is still there. This actually looks like an issue with the playground. Can you report this in the playground repo?

**Comment by dangdennis** [comment]
Will do, I'll close and move this over.

**Comment by dangdennis** [comment]
Thanks for the help.
