### ISSUE TITLE
Update Cadence 1.0 Contract Upgrade Validator to reject unrepresentable entitlement sets

### ISSUE THREAD

**Issue by dsainati1** [onflow/cadence#3296]
### Issue to be solved

Currently if a staged upgraded contract defines a resource `R` like so:

```
resource R {
   access(A | B) fun foo() { ... } 
   access(C | D) fun bar() { ... }
}
```

The entitlements migration will grant any `&R` references the conjunction `(A, B, C, D)`, rather than `((A | B), (C | D))`, as the latter is not expressible in Cadence. 

### Suggested Solution

Instead of allowing the migration to infer a more permissive authorization than is actually required, the validator should reject any contract updates like the example above that would cause the migration to behave in this unsafe way. 

Additionally, we will need to update the migration guide to reflect this change to the validator.

**Comment by j1010001** [comment]
related: https://github.com/onflow/cadence-lang.org/pull/95

**Comment by turbolent** [comment]
@dsainati1 I guess this is done now, with #3304 merged? Or was there something else that needed to still get done? (docs?)

**Comment by dsainati1** [comment]
Yeah we just need to update the migration guide, which I am working on now.
