### ISSUE TITLE
Division and Modulo for UFix64 and Fix64 is not implemented yet

### ISSUE THREAD

**Issue by slash7** [onflow/cadence#33]
## Instructions

Please fill out the template below to the best of your ability.

### Issue To Be Solved
Division for UFix64 and Fix64 is not implemented yet. 
The error message was not clear to what's wrong within the contract.

Code example: 
```swift
let result = Fix64(10) / Fix64(2)
```

Playground Error:
```swift
Error: GraphQL error: failed to deploy account code: Execution failed: TODO
```

### (Optional): Suggest A Solution

Maybe including more info about the function that breaks would help with debugging.

```swift
Execution failed: TODO [U]Fix64 division.
```

### (Optional): Context

(Replace this text:
What are you currently working on that this is blocking?)

**Comment by turbolent** [comment]
Hi @slash7, thank you for your issue!

We've worked hard on making this repository welcoming for contributors and have created several templates for creating issues: 
https://github.com/onflow/cadence/issues/new/choose.
The templates help us a lot, so we would greatly appreciated them being used! Thank you for understanding

Regarding the reported issue: 
Division and modulo operations for `[U]Fix64` have not been implemented yet, but plan to work on this week. I'll update this issue once it is complete.

For internal reference:
- dapperlabs/flow-go#3070
- dapperlabs/flow-go#3071

**Comment by slash7** [comment]
Hi @turbolent, thank you.
I've updated the issue using a template.

**Comment by turbolent** [comment]
@slash7 I've opened two PRs to implement division and modulo for `[U]Fix64`, they should be merged soon
