### ISSUE TITLE
Use Profile-Guided Optimization (PGO) to speedup programs (e.g. migrations) by up to ~14%

### ISSUE THREAD

**Issue by fxamacker** [onflow/cadence#3303]
The Go compiler supports [profile-guided optimization (PGO)](https://go.dev/doc/pgo).

- Go 1.20 - PGO is a new preview feature
- Go 1.21 - PGO is ready for general use and improved
- Go 1.22 - PGO is ready for general use and further improved

Go release notes mentioned 2-14% speedup by using PGO but it might be better than that in some cases as it improves.

Updates these (and maybe others):
- #3297
- https://github.com/onflow/flow-go/issues/1744

I opened this here in onflow/cadence because Epic #3297 mentions hardware, multiple machines, etc. to speedup migrations.

**Comment by turbolent** [comment]
Now that we're on Go 1.22 we should be able to try this out more easily

**Comment by fxamacker** [comment]
> Now that we're on Go 1.22 we should be able to try this out more easily

@turbolent BTW, thank you for pushing for and bumping Go to 1.22.  :+1:

**Comment by turbolent** [comment]
Applying PGO to the state extraction resulted in a ~2% improvement. See https://www.notion.so/flowfoundation/State-Migration-Result-Tests-01e501fceb8444cca8a598d6111f2e3c?pvs=4#f1464668c5324c0a8568a47e8b02edf6 for details. 

Though the result is not that impressive, given that this is basically a free win, we should still consider building the binaries with PGO enabled when we run the migrations. cc @zhangchiqing @j1010001
