### ISSUE TITLE
Use larger instances with more CPUs

### ISSUE THREAD

**Issue by j1010001** [onflow/cadence#3309]
- [x] Request m3-ultramem-128 and m2-megamem-416 instances
- [x] Test which instance performs better
- [x] Keep the instance that performs best, remove the other one

**Comment by j1010001** [comment]
Slack thread: https://dapperlabs.slack.com/archives/C015G65HR2P/p1714419791630609

**Comment by j1010001** [comment]
m3-megamem-128 is the fastest instance so far. Will also use C3D next.

**Comment by fxamacker** [comment]
>- [x] Request m3-ultramem-128 and m2-megamem-416 instances

>  m3-megamem-128 is the fastest instance so far. Will also use C3D next.

@j1010001 Did you mean `m3-megamem-128 (1.9TB RAM)` or `m3-ultramem-128 (3.9TB RAM)`?

atree inlining migration requires >2TB RAM (mostly because it uses large non-inlined state as input).

**Comment by j1010001** [comment]
> > * [x]  Request m3-ultramem-128 and m2-megamem-416 instances
> 
> > m3-megamem-128 is the fastest instance so far. Will also use C3D next.
> 
> @j1010001 Did you mean `m3-megamem-128 (1.9TB RAM)` or `m3-ultramem-128 (3.9TB RAM)`?
> 
> atree inlining migration requires >2TB RAM (mostly because it uses large non-inlined state as input).

You are right @fxamacker , I meant m3-ultramem-128.

**Comment by j1010001** [comment]
c3d-highmem-360 is marginally better, but not significant.
