### ISSUE TITLE
JavaScript/TypeScript Testing Framework

### ISSUE THREAD

**Issue by timmymmit** [onflow/cadence#332]
### Issue To Be Solved

It would be nice to write tests for Cadence in JavaScript/TypeScript.

### Suggest A Solution

Once the [Go testing library](https://github.com/onflow/cadence-testing-go) is ready, a similar library could be created in JavaScript/TypeScript, based on the [Flow JS SDK](https://github.com/onflow/flow-js-sdk/)

**Comment by turbolent** [comment]
This exists now: https://github.com/onflow/flow-js-testing
