### ISSUE TITLE
Documentation Generator

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#339]
### Issue To Be Solved

It would be nice to have a tool that generates human-readable documentation for Cadence programs.

### Suggest A Solution

Most pieces to build such a tool are in place: 
- The AST is well-defined and can be serialized to a well-defined JSON format if needed (i.e. the tool could be potentially written in a language other than Go)
- The parser parses documentation comments ("docstrings"; line comments starting with `///` and block comments starting with `/**`) for all declarations

The tool's main task would be to traverse the AST and generate e.g. Markdown, HTML, etc.

To generate the output, the documentation comments need to be written in a specific format/syntax. AFAIK there is no standard for this across programming languages. I think it would be best to adopt something that exists, I don't think it's necessary to reinvent the wheel here.

Inspiration:

- [Swift](https://nshipster.com/swift-documentation/): Markdown-based, with certain keywords like "Parameters"
- [Solidity's NatSpec](https://solidity.readthedocs.io/en/develop/natspec-format.html): Purely specific keywords/"tags" (`@` prefix)
- [Kotlin's KDoc syntax](https://kotlinlang.org/docs/reference/kotlin-doc.html): Mix of Markdown and specific keywords/"tags" (`@` prefix)
- Rust: also uses Markdown, but e.g. does not have a standardized way to refer to parameters
- [Elixir](https://hexdocs.pm/elixir/writing-documentation.html): Markdown-based

Choosing a Markdown-based format has the benefit that it e.g. allows adding sections, example code blocks, etc.

## Definition of Done

- [x] Implement tool
- [x] Tests
- [x] Documentation

**Comment by SupunS** [comment]
This is now available through the following PRs:
- #927
- #938
- #1003
- #1005
- #1008

I'll close this issue since the all tasks mentioned here are covered.

We can open new git-issues for any feature/improvement requests.
