### ISSUE TITLE
Emit events for capability controller operations

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#3459]
### Issue to be solved

Capability controller operations, such as issuing, should emit an event

### Suggested Solution

- `StorageCapabilityControllers.issue`: 
  `flow.StorageCapabilityControllerIssued(id: UInt64, address: Address, type: Type, path: StoragePath)`
- `AccountCapabilityControllers.issue`: 
  `flow.AccountCapabilityControllerIssued(id: UInt64, address: Address, type: Type)`

**Comment by turbolent** [comment]
Do these proposed events above look good?

What other events should be emitted?

@austinkline @bjartek @joshuahannan @sisyphusSmiling Would love to hear your thoughts!

**Comment by joshuahannan** [comment]
Those look good I think! Could we have some for deleting also? That might be useful

**Comment by turbolent** [comment]
@joshuahannan good point!

How about:

- `StorageCapabilityControllerDeleted(id: UInt64, address: Address)`
- `AccountCapabilityControllerDeleted(id: UInt64, address: Address)`

**Comment by turbolent** [comment]
Do we need an event for StorageCapabilityController.retarget`?

**Comment by sisyphusSmiling** [comment]
I think the events and associated actions proposed are great. Only suggestion would be to consider emitting `type: String` instead of `type: Type` based on how the value is defined in v2 FT/NFT standard events.

> How about:
>
> StorageCapabilityControllerDeleted(id: UInt64, address: Address)
> AccountCapabilityControllerDeleted(id: UInt64, address: Address)

I also wonder if `tag` would be useful here. If so, we might also consider truncating at a certain length if there's concern around emitting garbage that would otherwise be too computationally expensive at scale.

**Comment by turbolent** [comment]
> Is it possible to include the type in the `StorageCapabilityControllerDeleted` event?

We could, but it might be unecessary? We currently have the type in `InboxValuePublished`, but also omit it in `InboxValueUnpublished`. If we add it, we should also add it to `AccountCapabilityControllerDeleted`.

> Only suggestion would be to consider emitting type: String instead of type: Type based on how the value is defined in v2 FT/NFT standard events.

I'd prefer keeping strong types and avoid "stringly" typed code. It is also more consistent with existing event types, like `InboxValuePublished`.

**Comment by turbolent** [comment]
As of #3464 the following events are emitted:

For the following functions, emit the new event:


- `StorageCapabilityControllers.issue`:
   `flow.StorageCapabilityControllerIssued(id: UInt64, address: Address, type: Type, path: StoragePath)`

- `AccountCapabilityControllers.issue`:
   `flow.AccountCapabilityControllerIssued(id: UInt64, address: Address, type: Type)`

- `StorageCapabilityController.delete`:
    `flow.StorageCapabilityControllerDeleted(id: UInt64, address: Address)`

- `AccountCapabilityController.delete`:
    `flow.AccountCapabilityControllerDeleted(id: UInt64, address: Address)`

- `Account.Capabilities.publish`:
    `flow.CpabililityPublished(address: Address, path: PublicPath, capability: Capability)`

- `Account.Capabilities.unpublish`:
    `flow.CpabililityUnpublished(address: Address, path: PublicPath)`

For the following field change, emit a new event:

- `StorageCapabilityController.target`:
    `flow.StorageCapabilityControllerTargetChanged(id: UInt64, address: Address, path: StoragePath)`

Note that also capability publishing and unpublishing now emits events.

This is a first iteration. We still have a but of time to change these, and can always amend these with additional info.
