### ISSUE TITLE
Handle broken contracts

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#3480]
### Issue to be solved

After the update to Cadence 1.0 some contracts will be broken.

It should be possible to keep using them at least in a read-only form.

### Suggested Solution

https://www.notion.so/flowfoundation/Keep-values-with-types-of-broken-contracts-working-7a57ddf83a50456da6851ed1f65e26a9?pvs=4#c69daabfde7a4134be73f70b1ffea58f

**Comment by turbolent** [comment]
FLIP: https://github.com/onflow/flips/pull/283

**Comment by j1010001** [comment]
Remaining - handling of non-fungible token collections
