### ISSUE TITLE
Problems loading values and @AnyResource

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/cadence#3491]
### Current Behavior

Attempting to load a resource from account storage as `@AnyResource` fails

### Expected Behavior

Loading resources from storage as `AnyResource` should succeed

### Steps To Reproduce

Attempt to load a resource from storage using a transaction such as:

```cadence
import "FlowToken"

transaction {
    prepare(signer: auth(Storage) &Account) {
        let v <- FlowToken.createEmptyVault(vaultType: Type<@FlowToken.Vault>())

        signer.storage.save(<-v, to: /storage/temp)

        let loaded <- signer.storage.load<@AnyResource>(from: /storage/temp)
            ?? panic("no resource found in vault storage path")
        
        destroy loaded
    }
}
```

Which outputs the error:

```sh
Execution failed:\nerror: invalid transfer of value: expected `<<invalid>>`, got `FlowToken.Vault`\n --> 7e6d3a1240487452be2f9e265dfdcaa2e66bbb34f165518e700eb1be621fdbc1:6:17\n  |\n6 |         let m <- acct.storage.load<@AnyResource>(from: /storage/temp)\n7 |             ?? panic(\"no resource found in vault storage path\")\n  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n\n
```

### Environment

```markdown
- Flow CLI: v1.21.0-cadence-v1.0.0-preview.28 and above
- Cadence version: v1.0.0-preview.35
- Network: Emulator (waiting on PN HCU to validate there)
```

**Comment by sisyphusSmiling** [comment]
Was able to reproduce this on migrationnet in transaction 55ac88fd65ed289e67d5aa960a1f6f3d4e8ab9b702f2687e3cab65b916d3e3e0

**Comment by turbolent** [comment]
Flow CLI v1.21.0-cadence-v1.0.0-preview.28 uses Cadence v1.0.0-preview.35
Flow CLI v1.21.0-cadence-v1.0.0-preview.27 uses Cadence v1.0.0-preview.34

**Comment by turbolent** [comment]
Maybe this is related to the nil-coalescing changes? https://github.com/onflow/cadence/pull/3423

**Comment by turbolent** [comment]
Tried this and that succeeds as expected:

```cadence
resource R {}

fun f(): @R? {
    return <-create R()
}

let y <- f() ?? panic("no R")
```

**Comment by turbolent** [comment]
@SupunS Any idea why this could happen? Maybe the new use of `LeastCommonSuperType` for checking of the nil-coalescing operator does not handle the combination of `AnyResource` and `Never`?

**Comment by turbolent** [comment]
Pushed up a reproducer as a test case in https://github.com/onflow/cadence/pull/new/bastian/3491-fix-load-anyresource

**Comment by SupunS** [comment]
hmm, strange. I'll have a look

**Comment by turbolent** [comment]
I guess the problem is that for the LCS inputs `AnyResource` and `Never` the result is the `Any` type, which is specially returns `InvalidType` if the result is `AnyType`. 

The LCS function probably needs to somehow handle the case, or we specially handle the case in the nil-coalescing checking

**Comment by SupunS** [comment]
on a side note: It seems like the Invalid type somehow goes to interpreter. Should've been reported by the checker and terminate there.

**Comment by turbolent** [comment]
> It seems like the Invalid type somehow goes to interpreter. Should've been reported by the checker and terminate there.

Good point! It looks like most, but not all calls of `LeastCommonSuperType` are followed by a check if the result is `InvalidType` at the call-site. Maybe we should add this to all call-sites, or even move the error into the LCS function so it is not forgotten, like in the nil-coalescing case.
