### ISSUE TITLE
View checking incorrectly assumes code type-checks 

### ISSUE THREAD

**Issue by j1010001** [onflow/cadence#3529]
TN migration for `ac391223d88c98e4.PuffPalz` runs into `runtime error: invalid memory address or nil pointer dereference`.

Investigate the root cause and evaluate if it is feasible to fix this for Mainnet migration.

Slack: https://flow-foundation.slack.com/archives/C074F78ECNL/p1723592715418549

**Comment by turbolent** [comment]
This occurs in the `view` checking, seemingly because it assumes the code successfully type checks.

Minimal reproducer:

```cadence
view fun f() { a[b] = 1 }
```

Here, the indexing expression of the assignment is invalid, because neither `a` or `b` are defined.
