### ISSUE TITLE
`0x` literal crashes checker in language server

### ISSUE THREAD

**Issue by Robin-Bonnin** [onflow/cadence#353]
### Problem
repo : https://github.com/Robin-Bonnin/Toke
In a script, when the getAccount looks like 0x, cadence crashes

### Steps to Reproduce

Using the VS code extension, in **script1.cdc** of the following 
Delete **TODELETE** string. 
Save. 
Then cadence crashes and never recovers

I cannot recover logs as the history is deleted by the number of line generated.

### Acceptance Criteria

<if any>

### Context

OWB application

**Comment by turbolent** [comment]
Thanks for the bug report @Robin-Bonnin! I fixed this in #354
