### ISSUE TITLE
Cadence migration is non-deterministic since crescendo RC3.

### ISSUE THREAD

**Issue by j1010001** [onflow/cadence#3536]
RC3 produces consistent results. RC4 crashes on MN state. RC5 produces non-deterministic results. So [somewhere between RC3-RC5](https://github.com/onflow/flow-go/compare/v0.37.0-crescendo-RC3...v0.37.0-crescendo-RC5) we have added source of non-determinism to the migration.

**Comment by fxamacker** [comment]
Finished initial investigation and extracted 3 files with payloads that can be used by Cadence team for creating a reproducer for the discrepency with `IDCapabilityValue.ID`.

If creating and resolving the reproducer doesn't fix the non-determinism, then I can look for additional issues. :pray:
