### ISSUE TITLE
When will @onflow/cadence-parser release v1.0?

### ISSUE THREAD

**Issue by Hexi1997** [onflow/cadence#3550]
### Issue to be solved

 The current version is 0.42.1, which does not support the latest cadence 1.0

### Suggested Solution

release v1.0

**Comment by Hexi1997** [comment]
@turbolent  It looks like this issue has been resolved, but the npm package is still not updated?
![image](https://github.com/user-attachments/assets/c3c869eb-e2f4-45bc-b436-9110db96ec0a)

**Comment by turbolent** [comment]
Cadence 1.0 isn't released yet, so there's no package yet. We can publish a prerelease one if that helps. Releases are not automatically built and pushed, we need to do that manually

**Comment by Hexi1997** [comment]
> Cadence 1.0 isn't released yet, so there's no package yet. We can publish a prerelease one if that helps. Releases are not automatically built and pushed, we need to do that manually

Yes, I think there will be developers who need a pre-release, since candence 1.0 has already been released on the testnet

**Comment by turbolent** [comment]
@Hexi1997 https://www.npmjs.com/package/@onflow/cadence-parser/v/1.0.0-preview.50 is published now, please give it a try

**Comment by Hexi1997** [comment]
> @Hexi1997 [npmjs.com/package/@onflow/cadence-parser/v/1.0.0-preview.50](https://www.npmjs.com/package/@onflow/cadence-parser/v/1.0.0-preview.50) is published now, please give it a try

Thanks, this helped me a lot
