### ISSUE TITLE
Add string formatting function 

### ISSUE THREAD

**Issue by bluesign** [onflow/cadence#3579]
### Issue to be solved

context: https://discord.com/channels/613813861610684416/1162086721471647874/1283181721562517607

It would be nice to have some basic string formatting.

**Comment by SupunS** [comment]
Based on the discord discussion issue can be have two parts:
- [ ] Introduce a `Stringer` interface.
  - Make all string-convertible types are subtypes of this newly added interface
  - See the existing `HashableStruct` type for inspiration.
- [ ] Support string templates, where formatting can be inlined in the string-literal itself.
  - See [Kotlin's sprint templates](https://kotlinlang.org/docs/strings.html#string-templates) and [Swift's string interpolation](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/stringsandcharacters/#String-Interpolation) for some ideas.

**Comment by bluesign** [comment]
> If the Stringer implementation is native to the language, then they could be safely used in this example

@jribbink I agree user defined Stringer is dangerous (I raised some concerns on this before), but also a quick note, in general for your use case, native Stringer can be also dangerous. 

In general you need 3 properties; deterministic, uniqueness and immutable ( more like crypto hashing ) I think output of ‘log’ lacks some.

**Comment by SupunS** [comment]
Thanks @jribbink and @bluesign for the feedback! Given the concerns, we opened a FLIP for the `Stringer` interface specifically: https://github.com/onflow/flips/pull/294 to discuss these concerns further and find a solution that works. We can also discuss in one of the upcoming working groups.
