### ISSUE TITLE
Allow returning references from scripts

### ISSUE THREAD

**Issue by alxocity** [onflow/cadence#358]
### Issue To Be Solved

It should be possible to return references from scripts, however, such programs are currently rejected.

### Suggested Solution

- [ ] Sema: Allow returning a reference from a script
- [ ] Runtime: return the value that the reference points to

**Comment by turbolent** [comment]
@alxocity can you please elaborate on this? What are you trying to do and what is currently not possible or not working?

**Comment by turbolent** [comment]
Updated the description and planning to implement this over the next two weeks.
