### ISSUE TITLE
Add ability to get address of account running transaction within the contract function

### ISSUE THREAD

**Issue by alxocity** [onflow/cadence#359]
### Issue To Be Solved

Currently the only way to detect the account running a function is for them to pass their AuthAccount (bad) or send in a resource reference from their collection (tedious).

### Suggest A Solution

Would be nice to have a "sender" like in solidity

or

Have some syntactical sugar for this boilerplate code:

```
// Contract snippet
pub resource Author { }
pub fun createAuthor(): @Author {
  return <-create Author()
}
pub fun mintNFT(author: &Author): @NFT {
  return <-create NFT(author: author.owner!.address)
}
```

```
// Transaction snippet
acct.save(<-NFT.createAuthor(), to: /storage/NFTAuthor)
let authorRef = acct.borrow<&NFT.Author>(from: /storage/NFTAuthor)!
let nft <- NFT.mintNFT(author: authorRef)
destroy <-acct.load<@NFT.Author>(from: /storage/NFTAuthor)
```

**Comment by bjartek** [comment]
Why can you not send in their Address manually as a parameter to the script/transaction?

**Comment by alxocity** [comment]
@bjartek anyone can impersonate anyone else in that case

**Comment by bjartek** [comment]
And the AuthAccount is bad because you really do not want access to their private stuff? 

So what you kind of want is a PublicAccount that is an proposer that has signed the payload?

**Comment by turbolent** [comment]
An equivalent is intentionally not supported, see https://cadence-lang.org/docs/solidity-to-cadence#msgsender-considered-harmful
