### ISSUE TITLE
Allow dereferencing of references to value-typed objects

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#397]
### Issue To Be Solved

It is currently not possible to get the underlying value of a reference to a value-typed objects, e.g. it is not possible to get an `Address` from a `&Address`.

This should stay invalid for resources.

### Suggest A Solution

Enable dereferencing references to value-typed objects, for example, through the force operator (`!`).

**Comment by SupunS** [comment]
Same as https://github.com/onflow/cadence/issues/2803

Feature was added in https://github.com/onflow/cadence/pull/2982
