### ISSUE TITLE
 for-in loop should bind index

### ISSUE THREAD

**Issue by Hendrik6** [onflow/cadence#402]
My issue was posted in the cadence discord right here: 
https://discordapp.com/channels/613813861610684416/621847359894061056/738918199940350036

### Issue To Be Solved

Is there an easy way to get the index of an item in an array? 
In Go, for example, you can do something like

```go
for i, j := range array {
    // ... 
}
```

in cadence I found 

```swift
let array = [45, 65, 32]
for element in array {
    if element == 32 {
        //return index (2)? 
    }
}
```

**Now the for-in loop only binds the value and not the index**

### Suggest A Solution

Would it be possible to handle the index in a for-loop in the same way this happens, by example, in Go? 

```go
for **index**, element := range array {
... 
}
```

### 

I feel like this is a more intuitive way of getting the index so we don't have to make an index variable.

**Comment by turbolent** [comment]
for-in statements currently don't support this, but it's definitely a great idea and something that should be added.

Also, the same would be useful for dictionaries, iterating over both value and key at the same time.

For now, you can simply maintain a separate index variable:

```
let array = [45, 65, 32]
var index = 0
for element in array {
    if element == 32 {
        return index
    }
    index = index + 1
}
```
