### ISSUE TITLE
BUG: Contract Interface conformance does not register

### ISSUE THREAD

**Issue by joshuahannan** [onflow/cadence#41]
### Instructions

When requiring a `access(self)` field in a resource in a contract interface, if the resource in the implementation has the same access control modifier, an error is reported. There should be no error.

### Steps to Reproduce

1. Use this contract:
```
pub contract interface ContractTypeConform {
    pub resource Res {
        access(self) var private: Int
    }
}

pub contract Example: ContractTypeConform {
    pub resource Res {
        access(self) var private: Int

        init () {
            self.private = 0
        }
    }
}
```
2. See that the resource `Res` in `Example` does not match the interface according to the static checker.

### Acceptance Criteria

The resource must conform correctly

### Context

Making nft storage fields private in an NFT collection

**Comment by turbolent** [comment]
The error is misleading here: 

`access(self)` in the type requirement should not be allowed, but is: just like in interfaces, all members are/need to be public. The type requirement is than converted to an interface type, and the invalid `access(self)` is dropped. 
The error is then correct: The concrete type uses `access(self)` but the type requirement requires public access.

So the code is rejected correctly, but with the wrong message. I'll fix this by checking type requirements' member access modifiers like interface types' member access modifiers (they always need to be effectively public)

**Comment by turbolent** [comment]
Also, please don't move issues to in progress yet, I haven't started on this yet.

**Comment by turbolent** [comment]
Improving this requires fixing hundreds of test cases :-/
