### ISSUE TITLE
Allow Events to take Path arguments

### ISSUE THREAD

**Issue by cybercent** [onflow/cadence#418]
### Issue To Be Solved

Events should be able to use `Path`s as arguments.

Example:
```
pub event ItemWithdrawn(id: UInt64, owner: Address?, path: Path?)

pub event ItemListed(id: UInt64, price: UFix64, owner: Address?, path: Path?)
```

**Comment by turbolent** [comment]
@cybercent thank you for the issue!

This should be very easy to support, basically we need to 
- Add another case to https://github.com/onflow/cadence/blob/df605a2832f1e0547856c82a30f579f9dd1f6e7f/runtime/sema/check_event_declaration.go#L57
- Add tests
- Update the documentation

**Comment by lkadian** [comment]
@turbolent If I'm not mistaken we can close this, it was added here:
https://github.com/onflow/cadence/commit/bb1ff2f8e23b40d739f30abe6f4a73c76c09017c#diff-48605e4a2911063c4ff5af7c345335ba45db20111c16c431756c6133ebb9fd59

**Comment by turbolent** [comment]
@lkadian Thanks for noticing that!
