### ISSUE TITLE
Add storage capacity and usage fields to accounts 

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#421]
## Issue To Be Solved

To enforce storage limits in accounts it is necessary to query storage usage information.

## Suggest A Solution

- [ ] Add a two new read-only fields to accounts (`AuthAccount` and `PublicAccount`):
  - `let storageCapacity: UInt64`: the maximum amount of storage that the account may store
  - `let storageUsed: UInt64`: the currently used amount of storage
    - TBD: Does this return the current amount or when the transaction started?
- [ ] Extend the runtime interface:
  ```go
  // GetStorageUsed gets storage used in bytes by the address at the moment of the function call.
  GetStorageUsed(address Address) (value uint64, err error)
  // GetStorageCapacity gets storage capacity in bytes on the address.
  GetStorageCapacity(address Address) (value uint64, err error)
  ```
- [x] Tests
- [x] Documentation

**Comment by turbolent** [comment]
@janezpodhostnik What types should the fields have, i.e. what is the unit of the storage amount?

**Comment by janezpodhostnik** [comment]
@turbolent they should be of type uint64 the unit is 1 byte

**Comment by turbolent** [comment]
@janezpodhostnik perfect, I updated the description
