### ISSUE TITLE
Proving access to an authorized account

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#423]
### Issue To Be Solved

A common use-case is proving access to an authorized account `AuthAccount`.

### Suggest A Solution

- Declare a new type `Identity` that cannot be constructed
- Add a new field `let identity: &Identity` to `AuthAccount`. The reference ensures the value cannot be stored

**Comment by jacob-tucker** [comment]
Hello, has there been any update on this front? I know it has been a long time, but I believe it will be very beneficial to have this paradigm. I use this a lot in my own smart contracts, although I have to develop the &Identity myself. If it was built in, it'd be amazing! 

For context, I think this would be super beneficial to proving ownership of an account. You can pass in the &Identity and use identity.owner!.address to get the address of the identity, and you can be sure who you are interacting with.

**Comment by turbolent** [comment]
The [FLIP proposing the addition of this feature](https://github.com/onflow/flow/pull/945) has been rejected, so closing this issue. Please see the comment on the FLIP for the reasoning.
