### ISSUE TITLE
The field `Type` in `cadence.Field` returns `nil` for optional types

### ISSUE THREAD

**Issue by yndc** [onflow/cadence#456]
### Problem

Referencing to [this forum post](https://forum.onflow.org/t/event-fields-with-nil-type/634/2).

All event field types (`Type` from `cadence.Field`) returns a `nil` value for all optional types.

List of event field that has this issue so far in the mainnet `<eventID> <eventField>`:
```
flow.AccountKeyAdded publicKey
flow.AccountKeyRemoved publicKey
flow.AccountCodeUpdated codeHash
flow.AccountCodeUpdated contracts
A.0b2a3299cc857e29.TopShot.Withdraw from
A.c1e4f4f4c4257510.Market.MomentWithdrawn owner
A.0b2a3299cc857e29.TopShot.Deposit to
A.c1e4f4f4c4257510.Market.CutPercentageChanged seller
A.c1e4f4f4c4257510.Market.MomentListed seller
A.ead892083b3e2c6c.DapperUtilityCoin.TokensWithdrawn from
A.ead892083b3e2c6c.DapperUtilityCoin.TokensDeposited to
A.e544175ee0461c4b.TokenForwarding.ForwardedDeposit from
A.c1e4f4f4c4257510.Market.MomentPurchased seller
A.0b2a3299cc857e29.TopShot.PlayCreated metadata
A.1654653399040a61.FlowToken.TokensWithdrawn from
A.1654653399040a61.FlowToken.TokensDeposited to
```

I expect them to have `cadence.OptionalType` as the correct type.

### Steps to Reproduce

Currently using `cadence v0.11.1` and `flow-go-sdk v0.12.1`.
Reading an event on the mainnet: 

```
package main

import (
	"context"
	"fmt"

	"github.com/onflow/cadence/encoding/json"
	"github.com/onflow/flow-go-sdk"
	"github.com/onflow/flow-go-sdk/client"
	"google.golang.org/grpc"
)

func main() {
	access, _ := client.New("access-004.mainnet1.nodes.onflow.org:9000", grpc.WithInsecure())
	txr, _ := access.GetTransactionResult(context.Background(), flow.HexToID("2ea2e9ba55600c4662237cf07c0fffb0d1a245cb676af93503fc46cecfd373e5"))
	encoded, _ := json.Encode(txr.Events[0].Value.Fields[1])
	fmt.Println(txr.Events[0].Value.EventType.Fields[1].Type) 	// <nil>
	fmt.Println(txr.Events[0].Value.Fields[1])     			// {df73817b133cd960}
	fmt.Println(string(encoded))					// {"type":"Optional","value":{"type":"Address","value":"0xdf73817b133cd960"}}
}
```

I'm printing the field `from` which is an optional type for `Address`. As shown from the example above I'm able to get the value, and `json.Encode` correctly added the field type on it, but getting the type from `cadence.Field` returns `nil`.

### Acceptance Criteria

`cadence.Field`'s `Type` should be not `nil` for optionals, but `OptionalType`. And for the example above, the `Type` should be `Address?`.

**Comment by turbolent** [comment]
@yndc Thank you for reporting this bug! I've opened a PR to fix it: #458
