### ISSUE TITLE
Warn when casting a value to a supertype

### ISSUE THREAD

**Issue by robmyers** [onflow/cadence#500]
# Proposal

Casting a value to a supertype should be at least a warning, possibly a static error:
```
pub fun shouldWarn(res: @MyResource) {
    let r <- res as! @MyResource
    ...
```

# Justification

The presence of casts to the established type of a value may indicate code quality issues or a misunderstanding of Cadence semantics.

In any case they are redundant, and should be removed by the developer.

**Comment by turbolent** [comment]
Agreed, we should report a warning that this will always succeed, and the cast is unnecessary.
