### ISSUE TITLE
Deprecate @ nested type requirement syntax

### ISSUE THREAD

**Issue by rheaplex** [onflow/cadence#501]
# Proposal

Deprecate the @interface syntax for arguments, e.g.:

https://github.com/onflow/flow-ft/blob/master/contracts/ExampleToken.cdc#L90
```
pub fun deposit(from: @FungibleToken.Vault) { ...
```

where @FungibleToken.Vault is a resource interface rather than a concrete resource.

# Rationale

This syntax may lead the reader of a program to believe that an interface type is a concrete resource type.

# Problem

Where we do not know the concrete type of a resource at compile time (e.g. in a generic marketplace) but still wish to accept one as a move argument (e.g. in the deposit function above), what is the syntax?

**Comment by turbolent** [comment]
This syntax was supported for nested type requirements, not interfaces in general. As nested type requirements got removed, this issue can be closed now.
