### ISSUE TITLE
Cannot decode prefix "flow" in DecodeTypeID

### ISSUE THREAD

**Issue by yndc** [onflow/cadence#509]
### Problem

When trying to get a transaction result from the Go SDK, I get this error from the `cadence` library: `invalid type ID: cannot decode prefix flow` on https://github.com/onflow/cadence/blob/6b7f2bed62c185f0dace5c029c0726fd7c005505/runtime/common/location.go#L79-L94

It's happening when it's trying to decode an event prefixed with `flow`, e.g. `flow.AccountCreated`. I think the `flow` prefix has not yet been registered.

### Steps to Reproduce

With the Go SDK, get the transaction result of the transaction with this ID: `0x74afbda5528d9931b0d995893f5dd33a65d166c45c7a75516855c8645b1de091`. 

It will returns this error: `client: failed to construct flow.TransactionResult entity from protobuf value: convert: failed to decode value: invalid JSON Cadence structure`

Related packages:
```
github.com/onflow/cadence v0.12.0
github.com/onflow/flow-go-sdk v0.13.1
```

**Comment by yndc** [comment]
By the way this isn't a problem in `v0.11.2`

**Comment by turbolent** [comment]
@yndc The Flow Go SDK hasn't been updated yet, it's still at 0.11.2: https://github.com/onflow/flow-go-sdk/blob/master/go.mod#L10
