### ISSUE TITLE
Non-local type inference

### ISSUE THREAD

**Issue by cybercent** [onflow/cadence#512]
### Problem

Type inference of array literals does not take into account the variable declaration's type annotation.

### Steps to Reproduce

```kotlin
let someInts: [UInt32] = [2, 3]
```

```
Execution failed: Checking failed: mismatched types. expected `[UInt32]`, got `[Int]`
```

**Comment by turbolent** [comment]
@cybercent Thanks for reporting this! Type inference in Cadence is local, i.e. the type of the array literal is inferred from the first element, which in fact is inferred to be `Int`. Non-local inference, like inferring the type of the array literal taking the type annotation on the variable declaration into account is not supported yet.

For now, specify the type of the array element: `let someInts: [UInt32] = [2 as UInt32, 3]`.

**Comment by SupunS** [comment]
Non-local type inferencing for expressions is now supported (https://github.com/onflow/cadence/pull/875), except for function call arguments.

**Comment by turbolent** [comment]
This should be done now, closing
