### ISSUE TITLE
Minor Typo in Cadence Docs

### ISSUE THREAD

**Issue by LorienEsla** [onflow/cadence#514]
While going through the Cadence documentation I noticed a typo:

The perceived issue can be seen here: https://docs.onflow.org/cadence/language/composite-types/#nested-resources

![image](https://user-images.githubusercontent.com/76882895/103465572-0fccef80-4d0b-11eb-9c61-e45e36065679.png)

I believe that child.name should be "Child 1" and not "Child". 

This could just as likely be an interpretation mistake as a typo, but I figured I would share.

**Comment by turbolent** [comment]
@LorienEsla Thanks for reporting this. I fixed it in 21f6a6c
