### ISSUE TITLE
Unify error messages for function/constructor overloading

### ISSUE THREAD

**Issue by SupunS** [onflow/cadence#520]
### Problem

When overloaded functions and overloaded constructors are written, the errors reported by the compiler are different.

### Steps to Reproduce

Consider the below example:
```
pub struct SomeStruct {

    pub init(code: Int) {
    }

    pub init(code: Int, value: String) {     // ------(1)
    }



    pub fun foo(code: Int) {
    }

    pub fun foo(code: Int, value: String) {     // ------(2)
    }
}
```
(1) Gives a error message as: `initializer overloading is not supported yet`. Entire initializer is marked as erroneous (underlined in red) in VSCode.
(2) Gives a error message as: ``cannot redeclare function: `foo` is already declared``. Only the func-name is marked as erroneous  (underlined in red) in VSCode.

### Acceptance Criteria

Good to have a unified experience for a user upon errors

### Context

N/A

**Comment by turbolent** [comment]
@PratikDhanave Awesome, contributions are very welcome! Let us know if you have any questions / need any pointers

**Comment by PratikDhanave** [comment]
@turbolent please assign this issue to me.
