### ISSUE TITLE
Reorganize repository

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#526]
### Issue To Be Solved

Historically the bulk of the code for Cadence is located in a directory named `runtime`. 
This is confusing from a language perspective, as it might be confused with a language's runtime.

Also, the parser is currently located in a package called `parser2`, as it is the second parser for Cadence. However, given the first parser was removed, the package should be renamed.

### Suggested Solution

- [x] Move all directories nested in the `runtime` directory to the root of the repository, e.g. `ast`, `sema`, etc.
- [x] Rename `parser2` to `parser`

**Comment by SupunS** [comment]
It would be also good to separate out the compiler front-end and the back-end. That leaves us the freedom to plug in different compiler back-ends for different runtimes in future.
```
Cadence
    |
    |_compiler
    |    |_compiler_frontend
    |    |   |_ast
    |    |   |_parser
    |    |   |_semantic_analyzer
    |    |   |_df_analyzer
    |    |   |_...
    |    |_compiler_backend
    |        |_wasm_gen
    |        |_llvm_gen*
    |_runtime
    |    |_values (runtime values / common code)
    |    |_intepreter
    |    |_vm*
```
_*some hypothetical uses-cases_

**Comment by turbolent** [comment]
To start with, maybe we can move the child packages under `runtime` one level up, so they are siblings to the `runtime` package, and leave the `runtime` package as-is.
