### ISSUE TITLE
Make Crypto contract compatible with Ethereum

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#537]
### Issue To Be Solved

It would be nice to verify Ethereum signatures in a Cadence contract.

### Suggested Solution

- [x] Add Keccak hashing algorithm
- [x] Allow providing a custom tag, e.g. the Ethereum personal signed message prefix

**Comment by KSlashh** [comment]
We need keccak256 !

**Comment by KSlashh** [comment]
To deal with cross chain message from EVM compatible chain, keccak256 is necessary.

**Comment by btspoony** [comment]
> To deal with cross chain message from EVM compatible chain, keccak256 is necessary.

I think there are two things we are missing:
1. keccak256 Hash Algorithm support
2. a `recover` function for keys using ECDSA Algorithm , since EVM Tx only have `signature` and `recoverId`

**Comment by superdcc** [comment]
We need keccak256 !

**Comment by turbolent** [comment]
Adding the Keccak256 hash algorithm was requested in #1326 and implemented in #1327

**Comment by turbolent** [comment]
Is there still a need for a custom tag? cc @tarakby

**Comment by tarakby** [comment]
@turbolent custom tags can be used when verifying ECDSA signatures so I guess you can tick the second item of the issue.

**Comment by turbolent** [comment]
@tarakby Sounds good! Does that mean we can close the issue as done?

**Comment by tarakby** [comment]
Yes, enabling Keccak and custom tags is done (the items on the issue description). However this doesn't mean the crypto of Cadence is totally compatible with Ethereum (title of the issue) because the equivalent of `ecrecover` isn't supported by Cadence. 
We could close this issue and `ecrecover` can be the subject of another issue.
