### ISSUE TITLE
Add `check` functionality to AuthAccount

### ISSUE THREAD

**Issue by joshuahannan** [onflow/cadence#564]
### Issue To Be Solved

Currently we use `check` on capabilities to check if the type of the capability can actually be used to create a reference.
It would be nice to have the same thing for an `AuthAccount` storage path

### Suggest A Solution

`AuthAccount.check<&T>(StoragePath): Bool`

**Comment by darkdrag00nv2** [comment]
@turbolent I was going through the implementation of `check` for capability and have a minor question/comment.

In the documentation for the `check` function, it is written that 
> T is the type parameter for the reference type. A type argument for the parameter must be provided explicitly.

But in the code, it seems like the type parameter is only required if the `borrowType` is `nil` - https://github.com/onflow/cadence/blob/c6117d12ced0daa87e5097bc275c9c8e50744d0d/runtime/sema/type.go#L6581-L6585.

**Comment by bluesign** [comment]
@darkdrag00nv2 Capability can have borrow type like `Capability<T>` or it can be just `Capability`.

if Capability has already borrow type, you can just call `check()` otherwise you need to provide type: `check<T>()`.

**Comment by turbolent** [comment]
Thanks for the great answer Deniz! 👍

In the case for the `AuthAccount.check` function, it would always have a required type parameter.
