### ISSUE TITLE
Standardizing Resouce paths

### ISSUE THREAD

**Issue by rahul-kothari** [onflow/cadence#58]
So assets/tokens etc. are stored locally on an account's storage as a resource and not on a smart contract. Also, 2 resources can't have the same path.

So are we expecting users of Flow to not just remember their account address and private key but also where they store what resource?

Creating some kind of resource standard (and hoping that users comply) wouldn't work because what if they already had some resource stored there, or if a malicious user poses as my erc20 token and convinces the user to store it at that particular resource?

Storing a database table of the resource path for each account that uses my contract is also hard because as a developer, how will I know who is using my smart contract, until the event on the SC is fired.

**1 idea that may work is to block certain resource paths on ALL accounts.**
So for the flow token, what if you block "`/storage/FlowToken" everywhere. And do this is for every SC created which deals with assets.
**And there is a community-based GitHub repo that shows which resource paths are blocked for which asset.**

Doing this allows automation too. Now I can automatically create a link from storage to the public domain for each account allowing anyone to seamlessly send tokens to someone else.

**Comment by joshuahannan** [comment]
Suggestion from @daniel in the discord:
maybe incorporating something that is unique to the contract in the path or under the path's internal implementation would work ?

Example:
`/internal-contract-id/storage/my-token`

As a developer I would only specify `/storage/my-token` , Flow would take care of generating the `internal-contract-id` for me, and allow this contract to create resources only under the `internal-contract-id`?

This could also work, but would expose the contract id in the path: 
`/storage/contract-id/my-token`

The contract ID could be derived from the user's account ID, like a Xorshift .

**Comment by turbolent** [comment]
Hi @rahul-ki, thank you for your issue!

We've worked hard on making this repository welcoming for contributors and have created several templates for creating issues:
onflow/cadence/issues/new/choose.
The templates help us a lot, so we would greatly appreciated them being used! Thank you for understanding

Regarding the reported issue:

We've so far defined and implemented the storage API, but still have to define how it will be used for Flow. 

So far we were thinking that contract might define paths as part of their interface under which it would store / expect resources / resource interfaces. 

For example, the Flow Fungible Token contract would e.g. assume that an account has a "default receiver" capability available at `/public/flowTokenReceiver` and borrow it as `{FlowToken.Receiver}`.

> if a malicious user poses as my erc20 token and convinces the user to store it at that particular resource?

Can you elaborate? When a resource is borrowed from storage, the requested type is checked against the type of the resource. If it does not match, the borrow will fail.

**Comment by dete** [comment]
> So are we expecting users of Flow to not just remember their account address and private key but also where they store what resource?

We anticipate that all decent wallet software will keep track of this on behalf of the user. The same way all decent Ethereum wallets keep track of which ERC-20s you own.

The reason we did it this way is that we imagine that sophisticated users may want to use wallet software that allows them to track multiple Vaults within the same account. By leaving the storage layout flexible, we leave it up to the wallet and users to decide how they want to organize their assets.

The one thing we do need to standardize (as @turbolent pointed out) is where the standard receiver interface lives. Without a standardized place to find the default receiver for an account, it makes it very difficult to send tokens without a lot of coordination between parties. But even if a dummy token were somehow to fool you and your wallet software into "filling the slot" intended for some other token receiver, it's still your account: You can override what receiver link is stored in what path.

I do like the idea of putting the contract or type id (both of which are globally unique) as part of the standardized path, so that there aren't any accidentally conflicts due to naming clashes. Perhaps a syntax like `/public/'FooToken/'Receiver` where the back-tick means "expand this type identifier into its unique type id". So, even if there were two different FooTokens, they would have their own unique receiver paths.

**Comment by rahul-ki** [comment]
@turbolent sorry for not using the template. I didn't know how to go about it, given this isn't a bug per se, but rather a discussion on how to take things forward with resource paths. My apologies nevertheless!

> So far we were thinking that contract might define paths as part of their interface under which it would store / expect resources / resource interfaces.

Yes agreed. The cleanest architecture would be one where anytime a user interacts with the SC (smart contract), the vault will be automatically stored in the defined path. And this should be same across every account.

The problem I see (and this extends what I meant by the whole malicious user thing):
How do you ensure that the paths defined in the SC are unique across all users? What if a user already has an asset at that path? By malicious user, I meant the following scenario: I have a SC for a token. You realize where I am getting users to store their resources. So you deliberately get some users to store your assets in that same path. Now those users will not be able to save my token on that path.

Then, if I am making a website to interact with my dApp, I will have to also expect users to give me a path. So either the user remembers where they stored the resource or I store it in a database table. 

I agree with @dete  about having a contractor automatically added onto the path. This automation would ensure paths are always unique.

**Comment by rahul-ki** [comment]
Will the contractID feature be added in the event and the beta mainnet release in a few days?
Would be fun to try it out with the new wallet release in the js-fcl package.

**Comment by joshuahannan** [comment]
We haven't gotten the chance to work on the contractID feature to storage paths yet unfortunately. @turbolent is this something that could be added fairly easily down the line and be able to be picked up by existing resources and storage path without too much hassle? Or would it require that every account has to move each of their resources to the new path syntax manually?

**Comment by turbolent** [comment]
There seem to be three different proposals in this issue:

1. @rahul-kothari originally proposed blocking resource paths. Is the goal here to avoid that a well-known path that is expected to store a capability of a certain type actually contains something else? That is, the "blocking" actually is just limiting the capability path to a specific type?

2. @cybercent proposed automatically incorporating the contract ID into storage paths. How exactly would this behave? Would Cadence automatically expand path literals when they appear within a contract declaration?

3. @dete proposed allowing types to be used in path literals. In your example, `/public/'FooToken/'Receiver`, are the two last components of the path each individual types? Or is there some sort of connection between them, e.g. does `Receiver` relate to the `Receiver` nested in `FooToken`? Would `/`FooToken/'BarToken` be valid?

**Comment by rahul-kothari** [comment]
Yea I think #2 is the best approach. I imagine just like account ids, contracts could have an id automatically. 

Problem with @dete’s answer happens when you have 2 contracts with the same name. Would they end up having the same paths then?

**Comment by turbolent** [comment]
Contract's can have the same name if they are declared in different accounts.

In @dete's idea, in `/public/'FooToken`, `FooToken` is a type and the path will not just contain the name of the contract itself, but it's fully qualified identifier, i.e it would include the address of the account where the type is defined.

**Comment by rahul-kothari** [comment]
So say 0x01 deploys FooToken and say an account 0x10 saves the tokens on this path: /FooTokenVault. 
Then if I deploy another FooToken contract on 0x02 - can 0x10 save its tokens on /FooTokenVault?

Ideally for a given comtract, all accounts using it should be saving it on the same path. This would make creating dapps easier (users can just hit transfer tokens button on a dapp’s UI and the dapp devs can just do it on their behalf because they know where the tokens are stored).

**Comment by cybercent** [comment]
Maybe this would work `/storage/0x01/NFT`.
Assuming 0x01 has the NFT contract deployed under his code field.

We’ll need to include the unique ID to use borrow so maybe using the contract address would make sense.

**Comment by cybercent** [comment]
If we generate a new ID, as in my first proposal we’d need a way to associate this new ID to the contact in order to know which ones of the NFTs are we using (assuming the user has more than one resource named NFT under his storage)

**Comment by turbolent** [comment]
No progress in a long time, closing for now. Please open a new issue if you still feel like this should exist
