### ISSUE TITLE
Detect invalid contract updates

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#588]
### Issue To Be Solved

Currently a transaction may change a contract in a way that Cadence does not support.
We should detect and reject these cases.

### Suggested Solution

- [x] Diff ASTs, detect the following illegal cases
	- [x] Field added
	- [x] Field type changed
- [x] When a contract is updated, perform check, abort if illegal change is performed

Some valid cases:
  - Adding type
  - Removing a field
  - Changing a function (body or signature)

### Context

- `interpreterRuntime.newAuthAccountContractsChangeFunction`

**Comment by SupunS** [comment]
I think we cannot detect the following case:
```
pub contract A {
    pub struct Foo {
        pub var x: Int
    }
}
```
```
pub contract B {
    pub var y: A.Foo
}
```
After both are deployed, if someone change the type of  `x` (`Foo`'s field) to `String`, that will corrupt reading the `y` field from storage.

Catch here is, we can't determine whether `Foo` is used in storage, using a flow analysis (incoming dependencies are not known)

A simple (and the most strict) solution is to not let anyone change the field types of **any public composite declaration**. Same for adding new fields as well.

**Comment by caseyturnerarrington** [comment]
@SupunS is this task still open and being worked on?

**Comment by SupunS** [comment]
@caseyturnerarrington pretty much done with the requirements mentioned in the issue. Kept it open to see if there's anything more we can/need to do on the same line.
I think we are good for now. Can open a new issue if some more requirements pops-up.
