### ISSUE TITLE
Dictionary .contains method

### ISSUE THREAD

**Issue by janezpodhostnik** [onflow/cadence#595]
### Improvement proposal

A `.contains` method could make code like:

```cadence
if dict[key] == nil {
    // do something
}
```

a lot more readable:

```cadence
if dict.contains(key) {
    // do something
}
```

There is already a `.contains` method on the `Array` so I think adding it for the `Dictionary` makes sense.

**Comment by turbolent** [comment]
Agreed, this should be added 👍
