### ISSUE TITLE
cadence 0.12.11 did not get marked as "latest release"

### ISSUE THREAD

**Issue by chenrui333** [onflow/cadence#599]
👋 it looks like the latest release 0.12.11 did not get marked as `latest release`, let me know if that is intentional. Thanks! 

relates to https://github.com/Homebrew/homebrew-core/pull/70751

**Comment by turbolent** [comment]
Hi @chenrui333! Sort of, I haven't gotten around to releasing the patches yet and writing proper release notes for them.

**Comment by turbolent** [comment]
I've released the latest tags

**Comment by chenrui333** [comment]
Thanks @turbolent for the quick turnaround.
