### ISSUE TITLE
BUG: Panics when storing a function, should statically reject

### ISSUE THREAD

**Issue by joshuahannan** [onflow/cadence#62]
### Problem

When trying to store a function in a smart contract, the runtime panics and crashes.

### Steps to Reproduce

1. Copy this contract:
```
pub contract Controller {

    pub var operator: AnyStruct?

    init(){  
        self.operator = fun(): Int{
            return 1
        }
    }
}
```
2. Try to deploy the contract.
3. See the runtime panic.

### Acceptance Criteria

The checker should reject this

### Definition of Done

The focus of this issue is just to not allow functions to be stored in fields.
In the future we will also have to reject more types, this is a starting place.

- [ ] Interpreter: Add an allow list to member assignments; include all types, except function types
  - In `CompositeValue.SetMember`: check if valid value (`StringValue`, `BoolValue`, ...), recurse into nested value (e.g. arrays)
- [ ] Checker: Remove rule that function types are not subtype of `AnyStruct`
- [ ] Checker: Add an allow list: Fields can't have function type
  - In `Checker.declareCompositeMembersAndValue`:
    - after/before `compositeType.Members = members`:
      check `check member.TypeAnnotation.Type` is valid type (`StringType`, `BoolType`, ...),
      recurse into nested type (e.g. arrays)

**Comment by joshuahannan** [comment]
Could this be a `good first issue` @turbolent ?

**Comment by turbolent** [comment]
I think we can address this particular issue by not treating functions as subtypes of `AnyStruct`. In general, in a separate issue, we need to restrict functions as discussed: they may only be used for parameter and local types, i.e. they can't be used fields, can't be returned from functions, etc.

**Comment by turbolent** [comment]
Synced with @zhangchiqing, added the actionables to the description

**Comment by turbolent** [comment]
Follow up issue for other types is #169

**Comment by zhangchiqing** [comment]
This issue will be addressed by two PRs:

1. checker to reject composite types with non-storable fields.
2. interpreter to reject fields with `AnyXXX` types defined in composite types to be assigned with non-storable values.

**Comment by turbolent** [comment]
This should be done now
