### ISSUE TITLE
Update CommandSubmitTransaction to use CLI library

### ISSUE THREAD

**Issue by psiemens** [onflow/cadence#639]
### Issue To Be Solved

Update the LSP `CommandSubmitTransaction` to call the CLI package directly.

Depends on: https://github.com/onflow/flow-cli/issues/96

**Comment by turbolent** [comment]
@MaxStalker What is the current status here?

**Comment by MaxStalker** [comment]
Implemented in https://github.com/onflow/cadence/pull/751

**Comment by turbolent** [comment]
Awesome! Closing
