### ISSUE TITLE
Update CommandExecuteScript to use CLI library

### ISSUE THREAD

**Issue by psiemens** [onflow/cadence#640]
### Issue To Be Solved

Update the LSP `CommandExecuteScript` to call the CLI package directly.

Depends on: https://github.com/onflow/flow-cli/issues/97

**Comment by turbolent** [comment]
@MaxStalker What is the current status here?

**Comment by MaxStalker** [comment]
I believe, we've implemented this in https://github.com/onflow/cadence/pull/751

**Comment by turbolent** [comment]
Awesome! Closing
