### ISSUE TITLE
Update CommandCreateAccount to use CLI library

### ISSUE THREAD

**Issue by psiemens** [onflow/cadence#642]
### Issue To Be Solved

Update the LSP `CommandCreateAccount` to call the CLI package directly.

Depends on: https://github.com/onflow/flow-cli/issues/98

**Comment by turbolent** [comment]
@MaxStalker What is the current status here?

**Comment by MaxStalker** [comment]
Implemented in https://github.com/onflow/cadence/pull/751

**Comment by turbolent** [comment]
Awesome! Closing
