### ISSUE TITLE
Update language server to load project config from flow.json

### ISSUE THREAD

**Issue by psiemens** [onflow/cadence#643]
### Issue To Be Solved

In order to integrate the LSP server with the new [CLI package](https://github.com/onflow/flow-cli/issues/80), it should be able to read the contents of the `flow.json` file in the current active project.

I see two ways to do this:
- Language server reads `flow.json` directly from the filesystem
- Language server reads `flow.json` from the [active workspace](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_workspaceFolders)

I think the second option is better if we can make it work. `flow.json` will already be in the set of files that the LSP is watching, and this way we can keep things consistent. The LSP can even make edits to `flow.json` using the [applyEdit](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_applyEdit) function (e.g. to add a newly created account).

**Comment by turbolent** [comment]
@MaxStalker What is the current status here?
