### ISSUE TITLE
Allow import of Capability values (cadence.Capability)

### ISSUE THREAD

**Issue by SupunS** [onflow/cadence#712]
### Issue To Be Solved

It should be possible to import Capability values (cadence.Capability), e.g. when sending them as an argument in a transaction or script.

### Suggested Solution

- [x] Add support for importing a **public** `cadence.Capability`
  - [x] Convert `cadence.Capability` in `importValue` to `interpreter.CapabilityValue`
  - [x] Check that the domain is public, fail if not
  - [x] Check that the type exists, fail if not
- [x] Update argument validation (if necessary)
  - [x] https://github.com/onflow/cadence/pull/724/files#diff-863660c79fae3d9b381c2dff3025cd88dc46eb62571b754e7695acbfeab4fbfeR1211
  - [x] https://github.com/onflow/cadence/pull/724/files#diff-863660c79fae3d9b381c2dff3025cd88dc46eb62571b754e7695acbfeab4fbfeR1226
- [x] Tests

#### Related issues:
- Allow import of type values #491

**Comment by turbolent** [comment]
@SupunS If we want to allow that, we must ensure the capability is not private. I updated the description with that constraint and added a TODO item in the proposed solution to check it.

**Comment by turbolent** [comment]
This is done 🎉
