### ISSUE TITLE
BUG: Objects shouldn't be able to use themselves as arguments to their functions

### ISSUE THREAD

**Issue by joshuahannan** [onflow/cadence#73]
### Problem

If a resource or struct has a member function that takes a resource of the same type as an argument, then it should not be able to use itself as an argument.

### Steps to Reproduce

1. Copy this contract:
```
pub contract Nodes {

    pub resource Test {
        pub fun deposit(from: @Test) {
            destroy from
        }
    }

    init() {

        let test <- create Test()

        // this line should fail
        test.deposit(from: <-test)
    }
}
```
2. See that there is no error reported

### Acceptance Criteria

Should invalidate the object that is being invoked so it cannot be used as an argument to itself.

**Comment by turbolent** [comment]
What basically happens here is that the resource which the function is invoked on is temporarily moved into the function body, and moved out after the invocation, i.e. this can be thought of as having `self` be an implicit parameter of the function and also an implicit additional return value. 

This needs to be addressed by temporarily invalidating the resource variable on which the function is invoked on, before the arguments are invalidated, and removing the invalidation after the invocation. 

This will likely require some refactoring in the resource invalidation code, as it currently does not support removing invalidations.
