### ISSUE TITLE
2 Misleading/ Wrong comments in documentation of composite types

### ISSUE THREAD

**Issue by Tworck** [onflow/cadence#734]
The 1st comment can be found in the last code example of:
https://github.com/onflow/cadence/blob/master/docs/language/composite-types.mdx#resources-in-arrays-and-dictionaries

```
let resources <- {"r1": <-create R()}
// `resources.length` is `1`

let first <- resource.remove(key: "r1")
// `resources.length` is `0`
destroy first

let old <- resources.insert(key: "r1", <-create R())
// `old` is nil, as there was no value for the key "r1"
// `resources.length` is `1`

let old2 <- resources.insert(key: "r1", <-create R())
// `old2` is the old value for the key "r1"
// `resources.length` is `2`

destroy old
destroy old2
destroy resources
```

Should be changed to **resources.length is 2** should be changed to **resources.length is 1**

The second can be found in the first code example:
https://github.com/onflow/cadence/blob/master/docs/language/composite-types.mdx#accessing-fields-and-functions-of-composite-types-using-optional-chaining

```
// Access the `number` field using optional chaining
let twoOpt = value?.number
// Because `value` is an optional, `twoOpt` has type `Int?`
let two = zeroOpt ?? 0
// `two` is `2`
```

**zeroOpt** should be changed to **twoOpt**

**Comment by turbolent** [comment]
Thank you for reporting this!

Fixed in 26e48932ad86abac366b073ea398a45756ae8e53 and f5fe50fc30b656ff8cf82a963edbaa6cb81b0089
