### ISSUE TITLE
Optimize encoding of composites

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#744]
### Issue To Be Solved

The encoding of composites to CBOR values can be optimized.

###  Suggestion

- Switch from CBOR map to CBOR array

### Definition of Done

- [ ] Optimize composite encoding
- [ ] Change decoding to only support this current format (i.e. remove old backwards-compatibility decoding code)
- [ ] Remove unnecessary field sorting when decoding
- [ ] Tests
  - [ ] Encode new format
  - [ ] Decode new format
  - [ ] Decode old format, incl. round-trip, i.e. encoding should match new encoding

**Comment by fxamacker** [comment]
@turbolent  In `decodeComposite`, it seems decoding type ID (`encodedCompositeValueTypeIDFieldKey`) is only for backwards compatibility.  It's superceded by qualified identifier (`encodedCompositeValueQualifiedIdentifierFieldKey`) in `prepareCompositeValue`.  Can I remove this entire block of code in decode.go?

https://github.com/onflow/cadence/blob/3bbc8c8a1a85f729a6a7ae1537769f6cb8de4964/runtime/interpreter/decode.go#L626-L650
