### ISSUE TITLE
Inconsistent SigningAlgorithm identifiers between flow-go and cadence repositories.

### ISSUE THREAD

**Issue by wildework** [onflow/cadence#760]
### Instructions

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.

### Problem

On the currently running testnet, when creating a PublicKey that uses `secp256k1` I get an `unkown error` with a pointer to the algorithm identifier `SignatureAlgorithm.ECDSA_secp256k1`.

```
let publicKey = PublicKey(
    publicKey: "1234".decodeHex(),
    signatureAlgorithm: SignatureAlgorithm.ECDSA_secp256k1
)
```

### Steps to Reproduce

Send this transaction with a valid secp256k1 public key to testnet.

```
transaction(publicKey: String) {
  prepare(signer: AuthAccount) {
    let account = AuthAccount(payer: signer);
    let key = PublicKey(
      publicKey: publicKey.decodeHex(),
      signatureAlgorithm: SignatureAlgorithm.ECDSA_secp256k1
    );
    account.keys.add(
      publicKey: key,
      hashAlgorithm: HashAlgorithm.SHA3_256,
      weight: 1.0
    );
  }
}
```

### Acceptance Criteria

Not sure.

### Context

In the `flow-go` repository (flow-go/crypto/types.go) you have the following string identifiers.

```go
func (f SigningAlgorithm) String() string {
	return [...]string{"UNKNOWN", "BLS_BLS12381", "ECDSA_P256", "ECDSA_secp256k1"}[f]
}
```

My assumption, when building the transaction initially, was that these identifiers will be understood by Cadence. But for some reason Cadence only accepts `SignatureAlgorithm.ECDSA_Secp256k1`, emphasis on the uppercase **S**.

**Comment by turbolent** [comment]
@SupunS Can you please have a look at this? Reported on testnet, which runs the latest release

**Comment by SupunS** [comment]
@wildework Thanks for reporting this!

In Cadence, the Signing Algorithms are represented using an enum: https://docs.onflow.org/cadence/language/crypto/#signing-algorithms. It currently supports two predefined members `ECDSA_P256` and `ECDSA_Secp256k1`. The enum cases are case-sensitive, so we have to use precise member names. It is similar to accessing a field from a struct.

This signing algorithm at cadence is actually independent of the signature-algo at `flow-go/crypto/types.go` which is separated by an interface that does the conversion from Cadence types to flow-go types. (see: https://github.com/onflow/flow-go/blob/master/fvm/crypto.go#L69-L78). Also, the conversion does not depend on the name, but rather the value of the enum.

With respect to the naming convention/best-practice, I would like to get @tarakby s input (`ECDSA_Secp256k1` vs `ECDSA_secp256k1`)

**Comment by tarakby** [comment]
As @SupunS explained, the constant names used by Cadence are not correlated to the constant names used by the Flow Crypto library. 

Flow crypto library uses the lowercase version `secp256k1` to follow the curve naming defined by SEC in this [document](https://www.secg.org/sec2-v2.pdf) (end of page 4/33). We found out recently that Cadence uses the uppercase version, but updating it now would result in a breaking change for users.

@SupunS, @turbolent I let you decide whether you wanna rename the Cadence constant. If yes, this could be done as part of the upcoming crypto-related breaking changes.

**Comment by wildework** [comment]
@SupunS @tarakby What if you guys just added another enum value.

```
pub enum SignatureAlgorithm: UInt8 {
    /// ECDSA_P256 is Elliptic Curve Digital Signature Algorithm (ECDSA) on the NIST P-256 curve.
    pub case ECDSA_P256 = 1

    /// ECDSA_Secp256k1 is Elliptic Curve Digital Signature Algorithm (ECDSA) on the secp256k1 curve.
    pub case ECDSA_Secp256k1 = 2
    pub case ECDSA_secp256k1 = 3
}
```

That way nothing would break for existing users and it would map right back to the same algorithm, `secp256k1`.

**Comment by SupunS** [comment]
That's a good idea. But unfortunately, right now the [enum](https://docs.onflow.org/cadence/language/enumerations/)'s raw value is implicit and corresponds to the defined order: https://github.com/onflow/cadence/issues/296. Specifying the raw value is not supported yet, though we have explicitly stated the raw value in the signing-algorithm documentation for user reference.

If we add a temporary one and removed it later, that would impact the rest of the enum-cases, as some of the raw values may be used by a different algorithm than the one before. This raw value is internally used for different purposes like data persistence, etc, and hence re-using the same raw value may lead to future incompatibilities.

So, I think we can stick with the current enum/algorithms as it doesn't break any functionality, and maybe we could rename it along with the other breaking changes when we introduce them.
