### ISSUE TITLE
Optimize encoding for remaining types still using CBOR map

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#764]
### Issue To Be Solved

The encoding of 12 types to CBOR values can be optimized.

### Suggestion

Switch from CBOR map to CBOR array for:
- StorageReferenceValue
- PathValue
- CapabilityValue
- common.AddressLocation
- LinkValue
- CompositeStaticType
- InterfaceStaticType
- ConstantSizedStaticType
- ReferenceStaticType
- DictionaryStaticType
- RestrictedStaticType
- TypeValue

### Definition of Done

- [ ] Optimize encoding
- [ ] Change decoding to only support this current format (i.e. remove old backwards-compatibility decoding code)
Tests
- [ ] Encode new format
- [ ] Decode new format
- [ ] Decode old format, incl. round-trip, i.e. encoding should match new encoding

**Comment by fxamacker** [comment]
The following text was added to issue #738 yesterday morning:  

> Smaller data will probably begin to catch up in percent improved as more remaining types are optimized. Larger data with big composites and dictionaries will show more modest gains with remaining types.
