### ISSUE TITLE
Add support for enumerating iteration elements in for-loop

### ISSUE THREAD

**Issue by joshuahannan** [onflow/cadence#781]
### Issue To Be Solved

It would be convenient to have the ability to iterate over an array and get the index of the element currently being accessed instead of having to track it explicitly

### Suggest A Solution

```
let array: [Int] = [6,3,4,6]

for index, element in array {
    log(index)
    log(element)
}

// Would output "0,6, 1,3, 2,4, 3,6"
```

**Comment by turbolent** [comment]
Duplicate of #402, was implemented in #1216
