### ISSUE TITLE
Optimize encoding by using streaming encoder

### ISSUE THREAD

**Issue by fxamacker** [onflow/cadence#794]
### Issue To Be Solved

Cadence storage layer and [fxamacker/cbor](https://github.com/fxamacker/cbor) can be optimized to encode faster.  

### Suggestion

By using streaming mode for encoding, we can eliminate intermediate objects being created when encoding large composites and dictionaries.  Other worthwhile optimizations are also possible by providing a low-level API in fxamacker/cbor.

Preliminary benchmark comparisons show performance gains are possible by encoding to CBOR in streaming mode.  Adding streaming mode to fxamacker/cbor was one of the ideas proposed by @dete and @turbolent during our first chat.

The effort required to add streaming mode has been simplified by replacing all `CBORMap` with `CBORArray` in the various PRs for issue #738.  We don't need to deal with maps.  🎉 

### Proposed Changes

Add a streaming encoder to fxamacker/cbor and modify Cadence storage layer to use the new API.

💡 __Phase 1__ can provide a new API that helps eliminate the creation of intermediate objects when encoding large arrays, composites, and dictionaries.  Tests using unoptimized new API show encoding is 12% faster for a 776,155 byte 'Value'.  Memory usage improved more than speed.  See issues #795, #796.

💡 __Phase 2__ can provide additional new API that provides access to more optimized encoding. For example, API to encode specific Go types such as `string` or `int64`.  See issues #805, #807.

💡 All phases can improve test coverage and fuzz tests -- I'd like the new API to pass 1+ billion execs of coverage-guided fuzzing initially (to gather corpus) and then we can drop it down to 250 million execs using the big corpus.

The combination of APIs provided by Phase 1 and Phase 2 can provide cumulative performance gains.

#### DRAFT API FOR PHASE 1 AND PHASE 2

```
// StreamEncoder provides low-level API for sequential encoding. 
// 
// Users of StreamEncoder should be familiar with CBOR data models.  
// When in doubt, please use Encoder instead.
// 
// It is also recommended to use Valid() to check whether 
// generated CBOR data is complete and well-formed.
// 
type StreamEncoder 
    // ------------------------- DRAFT API FOR PHASE 1 ------------------------------

    // NewStreamEncoder returns a new StreamEncoder for sequential encoding.
    func NewStreamEncoder(w io.Writer) *StreamEncoder 

    // Flush writes streamed data to underlying io.Writer.
    func (se *StreamEncoder) Flush() error 

    // EncodeArrayHead encodes CBOR array head of specified size.
    func (se *StreamEncoder) EncodeArrayHead(size uint64) 

    // EncodeTagHead encodes CBOR tag head with num as tag number.
    func (se *StreamEncoder) EncodeTagHead(num uint64) 

    // ------------------------- DRAFT API FOR PHASE 2 ------------------------------

    // EncodeString encodes string value.
    func (se *StreamEncoder) EncodeString(s string) 

    // EncodeInt64 encodes int64 value.
    func (se *StreamEncoder) EncodeInt64(i int64)

    // And etc. for other Go types...

```

### Caveats

There are tradeoffs between speed and error checking/handling.  Encoding can potentially be more aggressive but decoding should remain paranoid in order to handle malicious/malformed data.  We decided we'll simplify stream encoding by having users continue to call Valid() instead of complicating the library code.

### Updates

April 15, 2021 9:38 AM PT -- add issues #805, #807 and update Caveats.

**Comment by turbolent** [comment]
Discussion notes for this proposal:

- Q: How do we encode elements?
  - StreamEncoder wraps existing Encoder, we can keep using Encode(interface{})
- Q: How do we handle errors? How much safety should the low-level streaming API provide?
  - Validation difficult, needs to keep state
  - We're already validating the 
  - Decision: No validation in library, keep validation step in Cadence
- Q: Where do we implement the new streaming API?
  - Decision: Feature branch in CBOR library repo
