### ISSUE TITLE
Implement Phase 1 of new streaming encoding API in CBOR library 

### ISSUE THREAD

**Issue by turbolent** [onflow/cadence#795]
### Issue To Be Solved

The Cadence storage layer can be optimized by [fxamacker/cbor](https://github.com/fxamacker/cbor) providing a streaming encoding API.

### Suggestion

By using streaming mode for encoding, we can eliminate intermediate objects being created when encoding large composites and dictionaries.  Other worthwhile optimizations are also possible by providing a low-level API in fxamacker/cbor.

Preliminary benchmark comparisons show performance gains are possible by encoding to CBOR in streaming mode.  Adding streaming mode to fxamacker/cbor was one of the ideas proposed by @dete and @turbolent during our first chat.

The effort required to add streaming mode has been simplified by replacing all `CBORMap` with `CBORArray` in the various PRs for issue #738.  We don't need to deal with maps.  🎉 

### Proposed Changes

Add a streaming encoder to fxamacker/cbor.

💡 __Phase 1__ can provide a new API that helps eliminate the creation of intermediate objects when encoding large arrays, composites, and dictionaries.  Tests using unoptimized new API show encoding is 12% faster for a 776,155 byte 'Value'.  Memory usage improved more than speed.

#### DRAFT API FOR PHASE 1

```
// StreamEncoder provides low-level API for sequential encoding. 
// 
// Users of StreamEncoder should be familiar with CBOR data models.  
// When in doubt, please use Encoder instead.
// 
// It is also recommended to use Valid() to check whether 
// generated CBOR data is complete and well-formed.
// 
type StreamEncoder interface{
    // ------------------------- DRAFT API FOR PHASE 1 ------------------------------

    // NewStreamEncoder returns a new StreamEncoder for sequential encoding.
    func NewStreamEncoder(w io.Writer) *StreamEncoder 

    // Flush writes streamed data to underlying io.Writer.
    func (se *StreamEncoder) Flush() error 

    // EncodeArrayHead encodes CBOR array head of specified size.
    func (se *StreamEncoder) EncodeArrayHead(size uint64) 

    // EncodeTagHead encodes CBOR tag head with num as tag number.
    func (se *StreamEncoder) EncodeTagHead(num uint64) 
}
```

### Additional Info

- The streaming encoding API will not perform validation
- The API will be implemented in a feature branch of fxamacker/cbor

**Comment by fxamacker** [comment]
@turbolent I just created a branch called feature/stream-encode at fxamacker/cbor.  Here's the commit for the changes:  https://github.com/fxamacker/cbor/commit/980a4ddd8f27a6d6b88a9df52bd234df3db4b6d7

Getting the fuzz tests done for this took longer than expected (handling random scenarios like NaN being used in map keys and also how that affects sorting).

I only fuzzed it for 30 million execs so this feature shouldn't deploy to mainnet yet.
