### ISSUE TITLE
404 on index https://docs.onflow.org/cadence/index from https://docs.onflow.org/cadence/tutorial/01-first-steps link broken

### ISSUE THREAD

**Issue by comtechnet** [onflow/cadence#810]
### Instructions

link from Please see the Cadence introduction for more information about the high level design of the language.
broken

### Problem

see instructions

### Steps to Reproduce

click Cadence introduction link

### Acceptance Criteria

link works

### Context

Just starting looking at Flow - have found several errors in docs - have posted on ur forum  / Joshua H requested I create GH issues or PRs

**Comment by turbolent** [comment]
fixed in https://github.com/onflow/flow/commit/9f899e4081fd6c7807e4e978f716b0a0aa8735db
