### ISSUE TITLE
Storage access with private and storage domains giving false sense of security

### ISSUE THREAD

**Issue by bluesign** [onflow/cadence#816]
### Issue To Be Solved

Storage access with private and storage domains giving false sense of security. From the discord conversations with people, I think people think 'storage' and 'private' domains are not only 'write' protected, but also 'read' protected. 

I think it is more like maybe documentation issue, but I saw people thinking to store in there some sensitive stuff. 

### Suggest A Solution

Solution 1: 

- Make clear in docs, they are not for sensitive stuff. 

Solution 2 (this one is more complex) : 

- Make storage and private domains 'read-only' accessible with PublicAccount

**Comment by turbolent** [comment]
@bluesign Interesting, thanks for bringing this up! 

Re #1: I hadn't seen this interpretation / perspective on it yet, agreed we should point out that all data on the blockchain is public, and private/storage mean writeable, not "hidden".

Re #2: Agreed, that has been on the list for a long time, see https://github.com/onflow/cadence/blob/master/ROADMAP.md#high-priority
