### ISSUE TITLE
Runtime error in playground when saving capabilities

### ISSUE THREAD

**Issue by timongll** [onflow/cadence#840]
<img width="457" alt="Screen Shot 2021-04-25 at 1 39 46 AM" src="https://user-images.githubusercontent.com/25440724/115968852-5ec5bb80-a56c-11eb-81be-032b623053a5.png">
<img width="1151" alt="Screen Shot 2021-04-25 at 2 02 13 AM" src="https://user-images.githubusercontent.com/25440724/115968858-64230600-a56c-11eb-963f-2fe5967e6784.png">
Saving a capability would cause this runtime error on flow playground

**Comment by turbolent** [comment]
Thank you for reporting this, I will have a look

**Comment by turbolent** [comment]
@timongll The bug you ran into was already fixed by #666. The Playground is still using an older version v0.12.5 and needs to be updated to include this fix.
