### ISSUE TITLE
A low level API to decode values

### ISSUE THREAD

**Issue by SupunS** [onflow/cadence#847]
### Issue To Be Solved

Currently, when decoding values, the cbor library does all the decoding and returns a go-representation of values.

In order to achieve #844, we also need a low-level API that allows us to do the decoding by ourselves, in accordance with the cbor format.

### Suggest A Solution

The cbor library's StreamingEncoder (https://github.com/onflow/cadence/pull/830) supports a set of APIs such as, `EncodeRawBytes(b []byte)`, `EncodeBool(b bool)`, `EncodeUint(i uint)` etc.

We need a similar set of APIs for decoding as well. e.g:
- `func DecodeRawBytes() []byte {}`
- `func DecodeBool() bool {}`
- `func DecodeUint() unit {}`
- etc.

**Comment by fxamacker** [comment]
This is closed by fxamacker/cbor branch feature/stream-mode.  🎉
