### ISSUE TITLE
interface conversion: interpreter.NilValue is not interpreter

### ISSUE THREAD

**Issue by Tzunami** [onflow/cadence#860]
### Instructions

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.

### Problem
DEBU[0010] ️✉️   Transaction submitted                   txID=bc0ff0694ada0e6f3026af39a59794001c92aa8731acc42e773a66031c4780da
panic: interface conversion: interpreter.NilValue is not interpreter.EquatableValue: missing method Equal [recovered]
	panic: interface conversion: interpreter.NilValue is not interpreter.EquatableValue: missing method Equal [recovered]

### Steps to Reproduce

Compile the contracts, and run set_account, then mint_nft.cdc
line 119, last line of my NFTMinter

### Acceptance Criteria

<if any>

### Context
I'm trying to have a private Collection, so when the user mints, it mints to my collection instead.
[testnet-dev.zip](https://github.com/onflow/cadence/files/6403197/testnet-dev.zip)

<what are you currently working on that this is blocking?>

**Comment by turbolent** [comment]
@Tzunami Thank you for reporting this issue. The missing function had already been implemented earlier, so this is already fixed in the current version.
