### ISSUE TITLE
VSCode Cadence crash when launch project

### ISSUE THREAD

**Issue by script-money** [onflow/cadence#930]
### Instructions

VSCode Cadence crash when every launch

### Problem

I am writing cdc file, lint disable suddenly, I check VSCode output has some error log 
[This is crash log](https://gist.github.com/script-money/f2e27ccaaeecd855b820149649b7e97d), and show "*The Cadence server crashed 5 times in the last 3 minutes. The server will not be restarted.*"  in pop message window. I relaunch and reinstall extension, show same output immediately.

### Steps to Reproduce

1. `git clone https://github.com/script-money/FanNFT`
2. `flow cadence install-vscode-extension`
3. `cd  FanNFT && code .`
4. check OUTPUT in VSCode's terminal

#### flow
flow-cli version: v0.20.2
cadence: v0.5.0
#### vscode
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z (1 wk ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.3.0

**Comment by turbolent** [comment]
Hi @script-money! 

Thank you for reporting this bug, along with all the details and the stack trace. 

This should already fixed by #867, which made it into the latest Cadence release. We'll release a new CLI with the latest Emulator and Cadence version shortly

**Comment by turbolent** [comment]
ref onflow/flow-cli#265
