### ISSUE TITLE
Doc Error in Values and Types

### ISSUE THREAD

**Issue by comtechnet** [onflow/cadence#964]
### Instructions

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.

### Problem

// Declare a non-optional integer
// which is initialized to `c` if `a` is non-nil.
// If `c` is nil, the program aborts.
let d: Int = c!
// `d` is initialized to 3 because c isn't nil.

Should read ...

// Declare a non-optional integer
// which is initialized to `c` if `c` is non-nil.
// If `c` is nil, the program aborts.
let d: Int = c!
// `d` is initialized to 3 because c isn't nil.

### Steps to Reproduce

see above

### Acceptance Criteria

change the doc

### Context

Learning Cadence and Flow

**Comment by comtechnet** [comment]
The above error is in https://docs.onflow.org/cadence/language/values-and-types

in the Force Unwrap (!) documentation section

**Comment by turbolent** [comment]
@comtechnet good catch! fixed in  809632d
