### ISSUE TITLE
The documentation incorrectly suggests you can pass an internal type to a transaction

### ISSUE THREAD

**Issue by briandilley** [onflow/cadence#965]
### Instructions
Update the documentation to be correct.

### Problem
The documentation [at this link](https://docs.onflow.org/cadence/language/accounts#add-account-keys) suggests that you
can pass a `PublicKey` as a parameter to a transaction but this is not possible because you cannot pass internal types to
a transaction.

### Steps to Reproduce
Attempt to execute the transaction in the documentation.

### Context
I'm working on the JVM SDK and using it to create accounts.

**Comment by turbolent** [comment]
@SupunS Could you have a look here? Short term we should update the docs, long-term it would be nice to support this (again?)

**Comment by SupunS** [comment]
Yup, added #967 as a quick/temporary fix for the docs.

I'll see if I can add the support for importing native types (#717) at the same time.

**Comment by SupunS** [comment]
Unfortunately, `PublicKey` is no longer importable as an argument, because we introduced methods to the `PublicKey` type (e.g: `verify()` method). So, for this particular case, updating the documentation seems like the proper solution.
