### ISSUE TITLE
Update the crypto contract

### ISSUE THREAD

**Issue by tarakby** [onflow/cadence#993]
### Issue To Be Solved

Update the crypto contract to use the new built-in features and improve readability.

- [x] Update the key list verification to use the tag "FLOW-V0.0-user" instead of "user", as defined in the [SDK](https://github.com/onflow/flow-go-sdk/blob/master/sign.go#L37) (the padding is not needed).
- [x] Remove the verification [interface](https://github.com/onflow/cadence/blob/master/runtime/stdlib/contracts/crypto.cdc#L2-L12) and use the the built-in `PublicKey` structure. 
- [x] (Optional) Rename the [function](https://github.com/onflow/cadence/blob/master/runtime/stdlib/contracts/crypto.cdc#L108) `isValid` to `Verify` to be more consistent with the method `Verify` of `PublicKey` and avoid the confusion with the field `isValid` of `PublicKey`.
- [x] Audit the contract for possible cleanup.

**Comment by turbolent** [comment]
@tarakby I've completed the first three item in #999. Are you going to audit the contract, do you maybe want to sync on what could be done?
